### PR TITLE
[ResourceManager] Remove subscription cache when get api version for GenericResource

### LINKED ISSUE #38154: [BUG] ResourceManager raising the wrong exception
### Library name and version

  Azure.ResourceManager 1.7.0 Azure.ResourceManager.Resource 1.6.0

### Describe the bug

When using Client.GetSubscriptionResource(ResourceIdentifier).GetAsync() to check a Subscription is exists or not, the interface get wrong exception which was cause by pervious query

### Expected behavior

Client.GetSubscriptionResource(ResourceIdentifier).GetAsync() should retrieve the correct query when query Subscription

### Actual behavior

Client.GetSubscriptionResource(ResourceIdentifier).GetAsync() use the cached ResourceProviderCollection to retrieve previous wrong exception. 

> 

### Reproduction Steps

1. Use correct credential to create correct Armclient,  and its subscription id is **A.**
2. Use var wrongSub=  SubscriptionResource.CreateResourceIdentifier("**A does not exist subscriptionId**");
3. Client.GetSubscriptionResource(wrongSub).GetAsync() will throw RequestionException with 404.
4. Cath the above exception and ignore it.
5. Use var correctSub= SubscriptionResource.CreateResourceIdentifier(" **A.**");
6. Client.GetSubscriptionResource(correctSub).GetAsync() will direct throw the previous exception. because   ResourceProviderCollection  is the cached instance. 

### Environment

Azure.ResourceManager.Resource 1.6.0  Azure.ResourceManager 1.7.0

### PR DESCRIPTION
**Pull request by HarveyLink**
Thi is the fix for issue #38154 
The issue is about when we get a `GenericResource` under subscprtion, a` GetApiVersion()` operation will be called, this method will use cached `ResourceProviderCollection` (which consumes subscription id) if exists. 
Then if we put a wrong subscription id at fist place, it will always fail on the Api version verify step.
This fix removes cache logic. It maybe not the best apporach, feel free to bring up any new ideas.

### CODE REVIEW

File: sdk/resourcemanager/Azure.ResourceManager/src/Resources/Custom/GenericResourceCollection.cs [hunk 1]
```diff
@@ -238,7 +238,8 @@ private string GetApiVersion(ResourceIdentifier resourceId, CancellationToken ca
             {
                 throw new ArgumentException("Only resource id in a subscription is supported", nameof(resourceId));
             }
-            string version = GetProviderCollectionForSubscription(subscription).GetApiVersion(resourceId.ResourceType, cancellationToken);
+            ResourceProviderCollection collection = new ResourceProviderCollection(Client, subscription);
```
Comment (ArthurMa1978) [inline sdk/resourcemanager/Azure.ResourceManager/src/Resources/Custom/GenericResourceCollection.cs:241]: Can we use `hasData` to optimize the get?

**Review by ArthurMa1978 — APPROVED** [review]

File: sdk/resourcemanager/Azure.ResourceManager/src/Resources/Custom/GenericResourceCollection.cs (hunk 1 above)
Comment (ArthurMa1978) [inline sdk/resourcemanager/Azure.ResourceManager/src/Resources/Custom/GenericResourceCollection.cs:241]: Add this bug fix into the changelog.md

**Review by archerzz — APPROVED** [review]

File: sdk/resourcemanager/Azure.ResourceManager/src/Resources/Custom/GenericResourceCollection.cs (hunk 1 above)
Comment (HarveyLink) [reply sdk/resourcemanager/Azure.ResourceManager/src/Resources/Custom/GenericResourceCollection.cs:241]: Done
