### PR TITLE
[MPG Generator] Fix paging action operations to not resource-wrap return types

### LINKED ISSUE #57110: [MPG C# Generator] Paging action operations should not resource-wrap return types
## Bug Description

The MPG C# generator incorrectly wraps paging results in resource types for **action** operations. When a paging operation is an ARM **action** (not a list), the generator should return the raw data type (e.g., `Pageable<ServerConfigurationData>`), not the resource-wrapped type (e.g., `Pageable<NodeConfigurationResource>`).

**Example TypeSpec:** [ServerConfiguration.tsp](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresqlhsc/resource-manager/Microsoft.DBforPostgreSQL/PostgresqlHsc/ServerConfiguration.tsp) — the `listByServer` operation is an `ArmResourceActionSync` (action on `ClusterServer`), not a resource list on `ServerConfiguration`.

## tspCodeModel evidence

The emitter correctly identifies the operation as an **Action** in the resource metadata:

```json
{
    "methodId": "Microsoft.DBforPostgreSQL.Configurations.listByServer",
    "kind": "Action",
    "operationPath": ".../{clusterName}/servers/{serverName}/configurations",
    "resourceScope": ".../{clusterName}/servers/{serverName}"
}
```

However, the method-level metadata only says `kind: "paging"` — the Action vs List distinction is only in the resource operation metadata.

## Expected behavior

Since the operation is an **Action** (not a **List**), the generated method should return:

```csharp
public virtual Pageable<CosmosDBForPostgreSqlServerConfigurationData> GetConfigurations(...)
```

## Actual behavior

The generator sees the `paging` kind + a matching `NodeConfigurationResource` class, and produces:

```csharp
public virtual Pageable<CosmosDBForPostgreSqlNodeConfigurationResource> GetConfigurations(...)
```

## Root cause

The generator does not check the ARM resource operation `kind` (Action vs List) when deciding whether to resource-wrap paging results. It only checks the method-level `kind: "paging"` and the existence of a matching resource class.

## Current workaround

Use `CodeGenSuppress` in a `Customized/` file to suppress the generated method and replace it with a hand-written version returning the raw data type.

### PR DESCRIPTION
**Pull request by haiyuazhang**
## Description

This PR fixes #57110 - paging action operations were incorrectly having their return types resource-wrapped.

When a paging operation is an ARM **action** (e.g., `ArmResourceActionSync`), not a **list**, the generator should return the raw data type (`Pageable<ConfigurationData>`), not the resource-wrapped type (`Pageable<ConfigurationResource>`).

### Root cause

`PageableOperationMethodProvider.InitializeTypeInfo()` performs a fallback lookup via `TryGetResourceClientProvider` to find a matching resource for the paged item's data type. This lookup doesn't distinguish between Action and List operation kinds - it always wraps if a matching resource exists.

### Fix

Added a `skipResourceWrapping` parameter to `PageableOperationMethodProvider` that bypasses the resource data type to resource type lookup. This flag is set to `true` when the ARM operation kind is `ResourceOperationKind.Action` in both:
- `ResourceClientProvider.BuildMethods()`
- `MockableResourceProvider.BuildResourceServiceMethod()`

### Changes

| File | Change |
|------|--------|
| `PageableOperationMethodProvider.cs` | Added `skipResourceWrapping` parameter to constructor and `InitializeTypeInfo` |
| `ResourceClientProvider.cs` | Pass `skipResourceWrapping: true` for Action operations |
| `MockableResourceProvider.cs` | Thread `skipResourceWrapping` through for Action operations |
| `PageableOperationMethodProviderTests.cs` | **New** - 2 tests verifying paging actions don't resource-wrap |
| `InputFactory.cs` | Added `crossLanguageDefinitionId` param to `PagingServiceMethod` helper |

### Testing

- 2 new unit tests for sync/async paging action return types
- All 121 existing tests pass

Fixes #57110

> **Note:** This PR was authored by GitHub Copilot.

### CODE REVIEW

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/OperationMethodProviders/PageableOperationMethodProvider.cs [hunk 1]
```diff
@@ -41,7 +41,8 @@ public PageableOperationMethodProvider(
             InputPagingServiceMethod method,
             bool isAsync,
             string? methodName = null,
-            ResourceClientProvider? explicitResourceClient = null)
+            ResourceClientProvider? explicitResourceClient = null,
+            bool skipResourceWrapping = false)
```
Comment (live1206) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/OperationMethodProviders/PageableOperationMethodProvider.cs]: consider to rename this to isResourceAction

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/OperationMethodProviders/PageableOperationMethodProvider.cs [hunk 2]
```diff
@@ -66,10 +68,15 @@ private static void InitializeTypeInfo(
             CSharpType itemType,
             ref CSharpType actualItemType,
             ref ResourceClientProvider? resourceClient,
-            ResourceClientProvider? explicitResourceClient = null
+            ResourceClientProvider? explicitResourceClient = null,
+            bool skipResourceWrapping = false
             )
         {
             actualItemType = itemType;
+            if (skipResourceWrapping)
```
Comment (live1206) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/OperationMethodProviders/PageableOperationMethodProvider.cs]: consider to put this check where this method is invoked, so that we can skip the method invoke and parameter passing

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/ResourceClientProvider.cs [hunk 3]
```diff
@@ -371,9 +371,11 @@ protected override MethodProvider[] BuildMethods()
 
                 if (method is InputPagingServiceMethod pagingMethod)
                 {
+                    // Action operations should not resource-wrap paging results
+                    var isAction = methodKind == ResourceOperationKind.Action;
```
Comment (live1206) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/ResourceClientProvider.cs]:
```suggestion
                    var isResourceAction = methodKind == ResourceOperationKind.Action;
```

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/test/Common/InputFactory.cs [hunk 4]
```diff
@@ -501,7 +502,8 @@ public static InputPagingServiceMethod PagingServiceMethod(
            IReadOnlyList<InputMethodParameter>? parameters = null,
            InputServiceMethodResponse? response = null,
            InputServiceMethodResponse? exception = null,
-           InputPagingServiceMetadata? pagingMetadata = null)
+           InputPagingServiceMetadata? pagingMetadata = null,
+           string? crossLanguageDefinitionId = null)
```
Comment (live1206) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/test/Common/InputFactory.cs]: why is this needed?

Comment (haiyuazhang) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/test/Common/InputFactory.cs]: removed

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/OperationMethodProviders/PageableOperationMethodProvider.cs (hunk 2 above)
Comment (haiyuazhang) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/OperationMethodProviders/PageableOperationMethodProvider.cs]: I tried this but then _`actualItemType = _itemType` needs to be set in two places (constructor for actions, method for non-actions). I'd rather keep it as-is so all actualItemType
   initialization stays in one place

**Review by live1206 — APPROVED** [review]
