### PR TITLE
Change kind values for EventHubs spans

### LINKED ISSUE #9092: Distributed tracing: Span kinds changes
**Describe the bug**
EventHub spans(activities) kinds were not correct in the previous guidance. They should be changed to
- Message: 'producer' kind (was 'internal')
- Send: 'client' kind (was 'producer')
- Processing: 'consumer' kind (was 'server') 

This complies with [OpenTelemetry semantics](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#spankind) and helps backend tools understand they are dealing with async message processing and visualize it accordingly.

This change does not break existing integration with Application Insights SDK, but helps other potential backends visualize Eventhubs correctly. 

**Setup (please complete the following information):**
 - OS: N/A
 - IDE : N/A
 - Version of the Library used: EventHubs 5.0.0-preview

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by pakrym**
Fixes: #9092

### CODE REVIEW

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs [hunk 1]
```diff
@@ -836,7 +836,7 @@ public virtual async Task StopProcessingAsync(CancellationToken cancellationToke
             await foreach (var partitionEvent in consumer.ReadEventsFromPartitionAsync(partitionId, startingPosition, ProcessingReadEventOptions, cancellationToken).ConfigureAwait(false))
             {
                 using DiagnosticScope diagnosticScope = EventDataInstrumentation.ClientDiagnostics.CreateScope(DiagnosticProperty.EventProcessorProcessingActivityName);
-                diagnosticScope.AddAttribute("kind", "server");
+                diagnosticScope.AddAttribute("kind", "consumer");
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs]: nit:  Could use make use of the constants from the `DiagnosticProperty` class here to avoid hardcoding the strings directly?

**Review by jsquire — APPROVED** [review]
LGTM.   One small nit request, if you'd be  so kind.
