### PR TITLE
Document cancellation behavior of UpdateConcurrency when reducing concurrency

### LINKED ISSUE #56447: [BUG] ServiceBus: UpdateConcurrency with lower value than previously set cancels tasks in progress
### Library name and version

Azure.Messaging.ServiceBus 7.20.1

### Describe the bug

While clearly intentional, the decision in ServiceBusProcess.ReconcileConcurrencyAsync to cancel "excess" tasks is in no way documented, and as currently described I'd say it's a bug that it does so. The cancellation isn't necessarily immediate, so IMO it's a bit strange that the setting is both delayed and forced through cancellation.

The easy fix would be to document this behavior, but a much more useful solution would be able to specify whether the cancellation is desired or not.
 

### Expected behavior

Tasks in progress should be allowed to complete.

### Actual behavior

Excess tasks are cancelled.

### Reproduction Steps

N/A

### Environment

_No response_

### PR DESCRIPTION
**Pull request by EldertGrootenboer**
## Description

Adds `<remarks>` XML documentation to `UpdateConcurrency` on both `ServiceBusProcessor` and `ServiceBusSessionProcessor` documenting that reducing concurrency cancels excess in-progress message handlers via their `CancellationToken`.

The current behavior in `ReconcileConcurrencyAsync` intentionally cancels excess tasks when concurrency is reduced, but this is not mentioned anywhere in the API documentation. This has caused confusion for users who expect in-progress handlers to complete naturally.

The new remarks clarify:
- Reducing concurrency signals the `CancellationToken` of excess in-progress handlers
- The cancellation is cooperative (handlers that don't observe the token continue running)
- Increasing concurrency takes effect immediately

Fixes #56447 (documentation portion)

**Note:** The reporter also requested an enhancement to optionally allow graceful draining instead of cancellation. That is tracked separately and not addressed by this PR.

### CODE REVIEW

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs [hunk 1]
```diff
@@ -1031,6 +1031,13 @@ public async ValueTask DisposeAsync()
         /// </summary>
         /// <param name="maxConcurrentCalls">The new max concurrent calls value. This will be reflected in the <see cref="ServiceBusProcessor.MaxConcurrentCalls"/>
         /// property.</param>
+        /// <remarks>
+        /// When reducing concurrency, any in-progress message handlers that exceed the new concurrency limit will have their
```
Comment (jsquire) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs]: I think the key thing to know is that there's no determinism in what gets cancelled - I think?   The pool just identifies that its over-allocated and cancels X number of tasks on a "look what I found"  basis.

_(assuming that I'm reading that correctly;  I'm not fully familiar with this specific code path)_

Comment (EldertGrootenboer) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs]: Good catch, added a note about the non-deterministic selection in the latest commit.

**Review by jsquire — APPROVED** [review]

**Review by jsquire — APPROVED** [review]
