### PR TITLE
[Resources] Improvement

### LINKED ISSUE #27092: Improve Azure.ResourceManager.Resources
1. In Azure.ResourceManager.Resources, we have a method `WhatIf` to return changes that will be made by the deployment if executed at different scope like tenant, subscription, resource group, etc.
    
    Currently the unify of the different scope in to one method `WhatIf` brings up an issue when checking if the `location` parameter is null or not. This property is required at tenant and management scope, so the method implements the check of the value and throws exception when it's null. However, `location` is not allowed at resource group and subscription scope but we can't set its value to null. A work around is set its value to be string.Empty but it's really strange. I'd prefer to use customization or something else to improve this method.

2. As we already used customization to support directly passing string to `Template` and `Parameters` in the model `DeploymentProperties`, it's reasonable to also adopt this change in `DeploymentWhatIfProperties`.

### PR DESCRIPTION
**Pull request by Yao725**
Fix #27092 and here are the details:
1. Disable payload flatten flag and use directive to make all the `WhatIf` method to use the parameter `DeploymentWhatIf`
2. Support directly passing string to the `Template` and `Parameters` in the model `DeploymentWhatIfProperties`
3. Add test case for the DeploymentWhatIf at the scope resource group

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

File: sdk/resources/Azure.ResourceManager.Resources/src/Generated/Deployment.cs [hunk 1]
```diff
@@ -338,58 +338,57 @@ public virtual Response<DeploymentExportResult> ExportTemplate(CancellationToken
...
         /// </summary>
         /// <param name="waitForCompletion"> Waits for the completion of the long running operations. </param>
-        /// <param name="location"> The location to store the deployment data. </param>
         /// <param name="properties"> The deployment properties. </param>
+        /// <param name="location"> The location to store the deployment data. </param>
         /// <param name="cancellationToken"> The cancellation token to use. </param>
-        /// <exception cref="ArgumentNullException"> <paramref name="location"/> or <paramref name="properties"/> is null. </exception>
-        public async virtual Task<ArmOperation<WhatIfOperationResult>> WhatIfAsync(bool waitForCompletion, string location, DeploymentWhatIfProperties properties, CancellationToken cancellationToken = default)
+        /// <exception cref="ArgumentNullException"> <paramref name="properties"/> is null. </exception>
+        public async virtual Task<ArmOperation<WhatIfOperationResult>> WhatIfAsync(bool waitForCompletion, DeploymentWhatIfProperties properties, string location = null, CancellationToken cancellationToken = default)
```
Comment (Yao725) [inline sdk/resources/Azure.ResourceManager.Resources/src/Generated/Deployment.cs:356]: The parameter `location` is not allowed at the resource group and subscription scope, so I think it's reasonable here to set its default value. The null check of this value will happen in the rest operation at the tenant and management group scope.

**Review by ArcturusZhang — APPROVED** [review]
