### PR TITLE
Strip orphaned virtual modifier from base properties after removing derived new/override properties

### LINKED ISSUE #56495: InheritableSystemObjectModelVisitor should strip orphaned virtual modifier from base properties after removing derived new/override properties
## Problem

When a TypeSpec defines model inheritance where derived models redeclare base properties (e.g., to add default values), the core generator creates an inheritance hierarchy where the base property gets `virtual` and derived properties get `new` or `override`.

The mgmt generator's `InheritableSystemObjectModelVisitor` removes the derived properties with `new`/`override` modifiers ([lines 104, 128](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/InheritableSystemObjectModelVisitor.cs#L104)) and also removes properties that duplicate base property names ([lines 112-114, 130-134](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/InheritableSystemObjectModelVisitor.cs#L130-L134)).

However, it does **not** strip the now-orphaned `virtual` modifier from the base model properties. A property should not be `virtual` unless there is a corresponding `override`.

## Example: RedisEnterprise

The [TypeSpec spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/redisenterprise/RedisEnterprise.Management/models.tsp) defines:

`	ypespec
model DatabaseProperties {
  accessKeysAuthentication?: AccessKeysAuthentication;
  // ...other properties
}

model DatabaseCreateProperties extends DatabaseProperties {
  // Redeclares with default value
  accessKeysAuthentication?: AccessKeysAuthentication = AccessKeysAuthentication.Disabled;
}

model DatabaseUpdateProperties extends DatabaseProperties {
  // Redeclares
  accessKeysAuthentication?: AccessKeysAuthentication;
}
`

Both `DatabaseCreateProperties` and `DatabaseUpdateProperties` extend `DatabaseProperties` and **redeclare** `accessKeysAuthentication`. The core generator marks the base property as `virtual` and derived properties as `new`/`override`.

After `InheritableSystemObjectModelVisitor` removes the derived properties, `DatabaseProperties.AccessKeysAuthentication` is left with an orphaned `virtual`:

`csharp
// Generated code  virtual with no corresponding override
public virtual AccessKeysAuthentication? AccessKeysAuthentication { get; set; }
`

This then propagates when `FlattenPropertyVisitor` flattens these properties into `RedisEnterpriseDatabaseData` and `RedisEnterpriseDatabasePatch`, which also incorrectly become `virtual`.

## Expected Behavior

When `InheritableSystemObjectModelVisitor` removes derived `new`/`override` properties, it should also strip the `virtual` modifier from the corresponding base properties that no longer have any overrides.

## Discovered In

PR [#55406](https://github.com/Azure/azure-sdk-for-net/pull/55406)  review comments:
- https://github.com/Azure/azure-sdk-for-net/pull/55406#discussion_r2856359120
- https://github.com/Azure/azure-sdk-for-net/pull/55406#discussion_r2856381202
- https://github.com/Azure/azure-sdk-for-net/pull/55406#discussion_r2856384024

### PR DESCRIPTION
**Pull request by live1206**
## Fix

When `InheritableSystemObjectModelVisitor` removes derived properties with `new`/`override` modifiers (or properties that duplicate base property names), the corresponding base model properties retain their `virtual` modifier even though no overrides remain. A property should not be `virtual` unless there is a corresponding `override`.

This adds a `StripOrphanedVirtualModifiers` helper that walks the base model hierarchy and removes the orphaned `virtual` modifier from properties whose names match the removed derived properties. It is called from both `Update` (system object model inheritance) and `UpdateRegularModelInheritance` (regular model inheritance).

### Generated output changes

- `PropertyOverrideBaseProperties.OverridableProperty`: `public virtual string` → `public string`
- `DuplicatePropertyTestData.OverridableProperty`: `public virtual string` → `public string`

Fixes #56495

### CODE REVIEW

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/InheritableSystemObjectModelVisitor.cs [hunk 1]
```diff
@@ -100,6 +100,12 @@ private void Update(InheritableSystemObjectModelProvider baseSystemType, ModelPr
             return;
         }
 
+        // Collect names of properties being removed to strip orphaned virtual from base
+        var removedPropertyNames = new HashSet<string>(
```
Comment (live1206) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/InheritableSystemObjectModelVisitor.cs]: can we extract this to a method, it is duplicated with L141.
And also, can we do this after baseSystemPropertyNames is constructed? so that, we can get this done together in a method to remove the duplicates

**Review by ArcturusZhang — COMMENTED** [review]
I am fine with the changes here, if in the future the inheritable system object type feature in MTG, will lead to a refactor of code here.

**Review by haiyuazhang — APPROVED** [review]
