### PR TITLE
[Event Hubs] Add timeout for starting background processes in the buffered Producer

### LINKED ISSUE #40052: [Event Hubs] Enforce timeout when starting background processes for the EventHubBufferedProducerClient
# Summary

The `EventHubBufferedProducerClient` is intended to be a long-running client that does its work in the background.  As a result, the default retry policy it uses is more generous than our normal defaults, allowing for greater resilience in those background operations.  Unfortunately, this also makes it inappropriate for use with interactive operations, as the end-to-end retries will take 20+ minutes.

For the first call to `EnqueueEventAsync` or `EnqueueEventsAsync`, the producer will attempt to start its background process, which includes connecting to the service and querying metadata.  If a transient failure occurs during this time and retries are attempted, the calling application will observe the producer appearing to hang for a long period of time, as no exception is surfaced until all retries are exhausted.

## Scope

- When the producer is starting up background processes, the initial network call to [UpdatePartitionInformation](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/src/Producer/EventHubBufferedProducerClient.cs#L1819C27-L1819C53) should enforce a timeout via the cancellation token passed to it, allowing an exception to be surfaced to callers after the `TryTimeout` interval has passed for the call.

- Callers enqueuing an event should observe a transient `EventHubsException` surfaced with the default `ServiceCommunicationProblem` reason and a message that indicates querying Event Hub metadata took longer than expected and failed.

### PR DESCRIPTION
**Pull request by m-redding**
These changes add a timeout when starting background processes in the buffered producer. This allows service errors on startup to surface more quickly, preventing the buffered producer from hanging for 30 minutes upon the first call to enqueue if there are connection issues.

Resolves https://github.com/Azure/azure-sdk-for-net/issues/40052 (see issue for more background / information)

### CODE REVIEW

File: sdk/eventhub/Azure.Messaging.EventHubs/src/Producer/EventHubBufferedProducerClient.cs [hunk 1]
```diff
@@ -1803,7 +1811,25 @@ private async Task StartPublishingAsync(CancellationToken cancellationToken)
...
+                    var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
+                    linkedCts.CancelAfter(_options.RetryOptions.TryTimeout);
+
+                    try
+                    {
+                        await UpdatePartitionInformation(linkedCts.Token).ConfigureAwait(false);
+                    }
+                    catch (OperationCanceledException)
+                    {
+                        throw new EventHubsException(true, EventHubName, "Querying the Event Hub metadata took longer than expected and failed.", EventHubsException.FailureReason.ServiceCommunicationProblem);
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs/src/Producer/EventHubBufferedProducerClient.cs:1827]: I would make this a `ServiceTimeout` reason code and tweak the verbiage to something like "The buffered producer took too long to start."

File: sdk/eventhub/Azure.Messaging.EventHubs/src/Producer/EventHubBufferedProducerClient.cs [hunk 2]
```diff
@@ -1803,7 +1811,25 @@ private async Task StartPublishingAsync(CancellationToken cancellationToken)
 
                 if ((_partitions == null) || (_partitionHash == null))
                 {
-                    await UpdatePartitionInformation(cancellationToken).ConfigureAwait(false);
+                    // The retry policy for the buffered producer is, by default, generous to allow for long running background work to be done
+                    // effectively. For startup, a more conservative retry policy is needed to prevent the producer from hanging, so cancel
+                    // after one TryTimeout interval.
+
+                    var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs/src/Producer/EventHubBufferedProducerClient.cs:1818]:
```suggestion
                    using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
```

File: sdk/eventhub/Azure.Messaging.EventHubs/src/Producer/EventHubBufferedProducerClient.cs [hunk 3]
```diff
@@ -1803,7 +1811,25 @@ private async Task StartPublishingAsync(CancellationToken cancellationToken)
...
+                    {
+                        await UpdatePartitionInformation(linkedCts.Token).ConfigureAwait(false);
+                    }
+                    catch (OperationCanceledException)
+                    {
+                        throw new EventHubsException(true, EventHubName, "Querying the Event Hub metadata took longer than expected and failed.", EventHubsException.FailureReason.ServiceCommunicationProblem);
+                    }
+                    finally
+                    {
+                        linkedCts.Dispose();
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs/src/Producer/EventHubBufferedProducerClient.cs:1831]: If you go with the `using`, no need to explicitly dispose.

File: sdk/eventhub/Azure.Messaging.EventHubs/src/Producer/EventHubBufferedProducerClient.cs [hunk 4]
```diff
@@ -884,6 +889,7 @@ public virtual async Task<string[]> GetPartitionIdsAsync(CancellationToken cance
         /// <exception cref="InvalidOperationException">Occurs when no <see cref="SendEventBatchFailedAsync" /> handler is currently registered.</exception>
         /// <exception cref="InvalidOperationException">Occurs when both a partition identifier and partition key have been specified in the <paramref name="options"/>.</exception>
         /// <exception cref="InvalidOperationException">Occurs when an invalid partition identifier has been specified in the <paramref name="options"/>.</exception>
+        /// <exception cref="EventHubsException">Occurs when querying Event Hub metadata took longer than expected.</exception>
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs/src/Producer/EventHubBufferedProducerClient.cs:892]:
```suggestion
        /// <exception cref="EventHubsException">Occurs when the <see cref="EventHubBufferedProducerClient" /> was unable to start within the configured timeout period.</exception>
```

**Review by jsquire — COMMENTED** [review]
Can we also please add a changelog entry?

File: sdk/eventhub/Azure.Messaging.EventHubs/src/Producer/EventHubBufferedProducerClient.cs [hunk 5]
```diff
@@ -1803,7 +1811,21 @@ private async Task StartPublishingAsync(CancellationToken cancellationToken)
...
+                    using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
+                    linkedCts.CancelAfter(_options.RetryOptions.TryTimeout);
+
+                    try
+                    {
+                        await UpdatePartitionInformation(linkedCts.Token).ConfigureAwait(false);
+                    }
+                    catch (OperationCanceledException)
+                    {
+                        throw new EventHubsException(true, EventHubName, "The buffered producer took too long to start.", EventHubsException.FailureReason.ServiceTimeout);
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs/src/Producer/EventHubBufferedProducerClient.cs:1827]: Just realized - we should be using the [resources dictionary](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Resources.resx) for the message.   Once we do that, I think we're good to go!

**Review by jsquire — APPROVED** [review]
