### PR TITLE
[DataProtectionBackup] Change ResourceUri type in DataSourceInfo and DataSourceSetInfo class

### LINKED ISSUE #35526: Invalid URI: The format of the URI could not be determined.
### Library name and version

Azure.ResourceManager.DataProtectionBackup 1.1.1

### Query/Question

The error originates from [DataSourceInfo.Serialization.cs](https://github.com/Azure/azure-sdk-for-net/blob/Azure.ResourceManager.DataProtectionBackup_1.1.1/sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Generated/Models/DataSourceInfo.Serialization.cs)(probably on Line#112 -
 `resourceUri = new Uri(property.Value.GetString());`)
Here is the code snippet that throws the exception - 
`

               var resourceId = DataProtectionBackupVaultResource.CreateResourceIdentifier(
                                _subscriptionId,
                                _resourceGroupName,
                                _vaultName);
                var resource =
                    _armClient.GetDataProtectionBackupVaultResource(resourceId
                        );

                var backupVault = await resource.GetAsync();

                var backupInstancesCollection = backupVault.Value.GetDataProtectionBackupInstances().GetAllAsync();
`

Here is another code snippet that throws the same exception.
`

                 var resourceId = DataProtectionBackupInstanceResource.CreateResourceIdentifier(
                                _subscriptionId,
                                _resourceGroupName,
                                _vaultName,
                                _backupInstanceName);
                var resource =
                    _armClient.GetDataProtectionBackupInstanceResource(resourceId
                        );
               
                var backupInstance = await resource.GetAsync();

`
Both the snippets provided are trying to get a BackupInstanceResource object

Based on my research, the resourceUri property that gets returned in the REST api call is not a valid Uri. In the Azure portal it shows up like this. _Added placeholders to show some confidential Ids_.
`"resourceUri": "/subscriptions/{subscriptionId}/resourceGroups/myRg/providers/Microsoft.Storage/storageAccounts/samplestorageaccount"`

### Environment

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.2.5

image

### PR DESCRIPTION
**Pull request by HarveyLink**
Fixes #35526 

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

File: sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceInfo.cs [hunk 1]
```diff
@@ -30,16 +30,19 @@ public DataSourceInfo(ResourceIdentifier resourceId)
...
             ObjectType = objectType;
             ResourceId = resourceId;
             ResourceLocation = resourceLocation;
             ResourceName = resourceName;
             ResourceType = resourceType;
-            ResourceUri = resourceUri;
+            ResourceUriString = resourceUriString;
+#pragma warning disable CS0618 // Type or member is obsolete
+            ResourceUri = null;
+#pragma warning restore CS0618 // Type or member is obsolete
```
Comment (ArcturusZhang) [inline sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceInfo.cs:45]: We do not need to assign anything to this. When uninitialized, a property is `null`

File: sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceInfo.cs
Comment (ArcturusZhang) [inline sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceInfo.cs:1]: Why we have to move the whole file to the customized directory?
We just need the deprecated property `ResourceUri` here actually.

File: sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceInfo.Serialization.cs
Comment (ArcturusZhang) [inline sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceInfo.Serialization.cs:1]: Since the old property never worked and we do not need it in the serialization, we could just remove the customization code here and let the generator to handle it

**Review by ArcturusZhang — COMMENTED** [review]
We should always minimize the amount of customized code.

File: sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceInfo.cs (hunk 1 above)
Comment (HarveyLink) [reply sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceInfo.cs]: Fixed

File: sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceInfo.cs
Comment (HarveyLink) [reply sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceInfo.cs:1]: Fixed

File: sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceInfo.Serialization.cs
Comment (HarveyLink) [reply sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceInfo.Serialization.cs:1]: Fixed

**Comment by HarveyLink** [comment]
Fix for #35526

File: sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceInfo.cs [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+// Licensed under the MIT License.
+
+#nullable disable
+
+using System;
+using System.ComponentModel;
+
+namespace Azure.ResourceManager.DataProtectionBackup.Models
+{
+    /// <summary> Datasource to be backed up. </summary>
```
Comment (ArcturusZhang) [inline sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceInfo.cs:11]: Let us remove this document (because the other partial class already has it)

File: sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceSetInfo.cs [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+// Licensed under the MIT License.
+
+#nullable disable
+
+using System;
+using System.ComponentModel;
+
+namespace Azure.ResourceManager.DataProtectionBackup.Models
+{
+    /// <summary> DatasourceSet details of datasource to be backed up. </summary>
```
Comment (ArcturusZhang) [inline sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceSetInfo.cs:11]: Let us remove this document (because the other partial class already has it)

File: sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/tests/ScenarioTests/BackupVaultTests.cs [hunk 4]
```diff
@@ -0,0 +1,143 @@
...
+{
+    public class BackupVaultTests : DataProtectionBackupManagementTestBase
+    {
+        public BackupVaultTests(bool isAsync)
+            : base(isAsync)//, RecordedTestMode.Record)
+        {
+        }
+
+        [Test]
+        [Ignore("Only need to verify serialize and deserialize")]
```
Comment (ArcturusZhang) [inline sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/tests/ScenarioTests/BackupVaultTests.cs:26]: We could introduce unit test, just do not inherit the test base class.
And we should not have the `Ignore` attribute
Please move this test class out side the ScenarioTests directory because this is not a scenario test.
Here is an example: https://github.com/Azure/azure-sdk-for-net/blob/605125066d507c13a2491c295535ad4cad364d79/sdk/compute/Azure.ResourceManager.Compute/tests/Unit/GalleryDiskImageTests.cs#L9

File: sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceSetInfo.cs (hunk 3 above)
Comment (HarveyLink) [reply sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceSetInfo.cs]: Fixed

File: sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceInfo.cs (hunk 2 above)
Comment (HarveyLink) [reply sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Customized/Models/DataSourceInfo.cs]: Fixed

File: sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/tests/ScenarioTests/BackupVaultTests.cs (hunk 4 above)
Comment (HarveyLink) [reply sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/tests/ScenarioTests/BackupVaultTests.cs]: Fixed

**Review by ArcturusZhang — APPROVED** [review]
