### PR TITLE
Validation fixes and allow unlimited unsettled messages

### LINKED ISSUE #16182: Unsettled message handling
> cc @jsquire, @JoshLove-msft

Looks like we should make this change in the new library as well.

_Originally posted by @JoshLove-msft in https://github.com/Azure/azure-sdk-for-net/pull/16163#issuecomment-714686714_

### PR DESCRIPTION
**Pull request by JoshLove-msft**
- Fixes https://github.com/Azure/azure-sdk-for-net/issues/16182
- Adds validation for partitionKey/sessionId
- Fixes issue where empty message batch would throw a nullref

### CODE REVIEW

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusMessage.cs [hunk 1]
```diff
@@ -216,7 +225,7 @@ public TimeSpan TimeToLive
             }
             set
             {
-                Argument.AssertPositive(value, nameof(TimeToLive));
+                Argument.AssertPositive(value, nameof(value));
```
Comment (JoshLove-msft) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusMessage.cs:228]: According to Framework Design Guidelines, we should use `value` rather than the property name for ArgumentExceptions thrown from setters.

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusMessage.cs [hunk 2]
```diff
@@ -133,7 +134,11 @@ public string PartitionKey
             }
             set
             {
-                ValidatePartitionKey(value);
+                Argument.AssertNotTooLong(value, Constants.MaxPartitionKeyLength, nameof(value));
+                if (SessionId != null && SessionId != value)
+                {
+                    throw new ArgumentOutOfRangeException(nameof(value), $"PartitionKey:{value} cannot be set to a different value than SessionId:{SessionId}.");
```
Comment (jsquire) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusMessage.cs:140]: Should we consider moving this message into the `Constants` to match the other validations?

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusMessage.cs [hunk 3]
```diff
@@ -174,7 +179,11 @@ public string SessionId
 
             set
             {
-                ValidateSessionId(value);
+                Argument.AssertNotTooLong(value, Constants.MaxSessionIdLength, nameof(value));
+                if (PartitionKey != null && PartitionKey != value)
+                {
+                    throw new ArgumentOutOfRangeException(nameof(value), $"SessionId:{value} cannot be set to a different value than PartitionKey:{PartitionKey}.");
```
Comment (jsquire) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusMessage.cs:185]: Should we consider moving this message into the `Constants` to match the other validations?

**Review by jsquire — APPROVED** [review]

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusMessage.cs (hunk 3 above)
Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusMessage.cs:185]: You mean Resources.resx? I was thinking we should just get rid of that. No other libs use it.
