### PR TITLE
Fix App Service Type issue

### LINKED ISSUE #37833: [BUG] ArgumentNullException When Accessing LogsSiteConfigResource
### Library name and version

Azure.ResourceManager.AppService 1.0.2 & 1.1.0-beta.1 

### Describe the bug

Hello,

I'm encountering an issue with the Azure.ResourceManager.AppService NuGet package where an ArgumentNullException is thrown when attempting to retrieve the LogsSiteConfigResource. This problem is experienced in both versions 1.0.2 and the 1.1.0-beta.1.

## Details:

**Error message:**
"Value cannot be null. (Parameter 'uriString')"

**Stack Trace:**
```
System.ArgumentNullException : Value cannot be null. (Parameter 'uriString')
   at System.Uri..ctor(String uriString)
   at Azure.ResourceManager.AppService.Models.AppServiceTableStorageApplicationLogsConfig.DeserializeAppServiceTableStorageApplicationLogsConfig(JsonElement element)
   at Azure.ResourceManager.AppService.Models.ApplicationLogsConfig.DeserializeApplicationLogsConfig(JsonElement element)
   at Azure.ResourceManager.AppService.SiteLogsConfigData.DeserializeSiteLogsConfigData(JsonElement element)
   at Azure.ResourceManager.AppService.WebAppsRestOperations.GetDiagnosticLogsConfigurationAsync(String subscriptionId, String resourceGroupName, String name, CancellationToken cancellationToken)
   at Azure.ResourceManager.AppService.LogsSiteConfigResource.GetAsync(CancellationToken cancellationToken)
```

### Expected behavior

The expectation is to be able to successfully retrieve the LogsSiteConfigResource without any exceptions being thrown.

### Actual behavior

When trying to retrieve the LogsSiteConfigResource, the System.ArgumentNullException is thrown with the message "Value cannot be null. (Parameter 'uriString')".

### Reproduction Steps

Here's a snippet of the code that triggers the error:

```csharp
var client = new AzureClient(tokenCred);
var webSiteConfigId = LogsSiteConfigResource.CreateResourceIdentifier(subscriptionId, webAppResourceGroupName, webAppName);
var webSiteConfigResource = await client.GetLogsSiteConfigResource(webSiteConfigId).GetAsync();
```

### Environment

.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

IDE: Visual Studio 17.6.5

### PR DESCRIPTION
**Pull request by mcgallan**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/37833

# Contributing to the Azure SDK
This PR is for fixing [Issue37833](https://github.com/Azure/azure-sdk-for-net/issues/37833)

### CODE REVIEW

File: sdk/websites/Azure.ResourceManager.AppService/src/Customization/Models/AppServiceTableStorageApplicationLogsConfig.cs [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+namespace Azure.ResourceManager.AppService.Models
+{
+    public partial class AppServiceTableStorageApplicationLogsConfig
+    {
+        /// <summary> Uri of the resource. </summary>
+        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
+        [ObsoleteAttribute("This property has been replaced by ResourceUriString", false)]
+        public System.Uri SasUri { get; set; }
+
+        public AppServiceTableStorageApplicationLogsConfig(System.Uri SasUri)
```
Comment (ArcturusZhang) [inline sdk/websites/Azure.ResourceManager.AppService/src/Customization/Models/AppServiceTableStorageApplicationLogsConfig.cs:19]: Let me double confirm - this property never works right?
if so, since the Uri property is obsoleted, we should also add EBNever and Obsolete to this public ctor as well.

File: sdk/websites/Azure.ResourceManager.AppService/src/Customization/Models/AppServiceTableStorageApplicationLogsConfig.cs [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+using System.ComponentModel;
+using Azure.Core;
+
+namespace Azure.ResourceManager.AppService.Models
+{
+    public partial class AppServiceTableStorageApplicationLogsConfig
+    {
+        /// <summary> Uri of the resource. </summary>
+        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
+        [ObsoleteAttribute("This property has been replaced by ResourceUriString", false)]
```
Comment (ArcturusZhang) [inline sdk/websites/Azure.ResourceManager.AppService/src/Customization/Models/AppServiceTableStorageApplicationLogsConfig.cs:16]: When we use an attribute, we usually do not include the `Attribute` suffix. Let us remove the suffix here

File: sdk/websites/Azure.ResourceManager.AppService/src/Customization/Models/AppServiceTableStorageApplicationLogsConfig.cs [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+{
+    public partial class AppServiceTableStorageApplicationLogsConfig
+    {
+        /// <summary> Uri of the resource. </summary>
+        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
+        [ObsoleteAttribute("This property has been replaced by ResourceUriString")]
+        public System.Uri SasUri { get; set; }
+
+        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
+        [ObsoleteAttribute("This property has been replaced by ResourceUriString")]
```
Comment (ArcturusZhang) [inline sdk/websites/Azure.ResourceManager.AppService/src/Customization/Models/AppServiceTableStorageApplicationLogsConfig.cs:20]: Two issues here:
1. We should remove the `Attribute` suffix here. We usually do not append this suffix when using attributes
2. We should add `false` to `Obsolete` to make sure less impacts to our customers. This tells the compiler to generate warnings when using the obsoleted members instead of generating errors.
```csharp
[Obsolete("the message", false)]
```

**Review by ArcturusZhang — APPROVED** [review]

**Review by live1206 — COMMENTED** [review]
Please update the changelog for this bugfix.

**Comment by mcgallan** [comment]
> Please update the changelog for this bugfix.

fixed

**Review by ArthurMa1978 — APPROVED** [review]

**Review by live1206 — APPROVED** [review]
