### PR TITLE
Use JsonConverterAttribute in SerializeProperties

### LINKED ISSUE #12490: [BUG] JsonConverterAttribute is ignored on polymorphic base class properties
**Describe the bug**
A class serialized with [`PolymorphicSerializeJsonConverter`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.rest.serialization.polymorphicserializejsonconverter-1) does not apply [`JsonConverterAttribute`](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonConverterAttribute.htm) declared on instance properties during serialization.

**Expected behavior**
[`JsonConverterAttribute`](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonConverterAttribute.htm) is applied during serialization whether or not the class is serialized using [`PolymorphicSerializeJsonConverter`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.rest.serialization.polymorphicserializejsonconverter-1).

**Actual behavior (include Exception or Stack Trace)**
[`JsonConverterAttribute`](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonConverterAttribute.htm) is only applied for properties of classes which don't use [`PolymorphicSerializeJsonConverter`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.rest.serialization.polymorphicserializejsonconverter-1).

**To Reproduce**
```csharp
using System;
using Microsoft.Rest.Serialization;
using Newtonsoft.Json;

[JsonObject("animal")]
class Animal
{
    [JsonConverter(typeof(DateJsonConverter))]
    [JsonProperty("birthday")]
    public DateTime Birthday { get; set; }
}

class Program
{
    static void Main()
    {
	var animal = new Animal
	{
	    Birthday = new DateTime(2020, 2, 29),
	};

	var serializeSettings = new JsonSerializerSettings();
	serializeSettings.Converters.Add(new PolymorphicSerializeJsonConverter<Animal>("dType"));
        Console.WriteLine(JsonConvert.SerializeObject(animal, Formatting.Indented, serializeSettings));
    }
}
```
produces

    {
      "dType": "animal",
      "birthday": "2020-02-29T00:00:00"
    }

(Note that `birthday` *was not* converted using [`DateJsonConverter`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.rest.serialization.datejsonconverter).) If `serializeSettings.Converters.Add` is removed, it produces:

    {
      "birthday": "2020-02-29"
    }

(Note that `birthday` *was* converted using [`DateJsonConverter`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.rest.serialization.datejsonconverter).)

**Environment:**
 - Name and version of the Library package used: Microsoft.Rest.ClientRuntime 3.0.3 with Newtonsoft.Json 12.0.3
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): .NET Core SDK 3.1.300

**Discussion:**
The problem is that [`JsonConverterHelper.SerializeProperties`](https://github.com/Azure/azure-sdk-for-net/blob/Microsoft.Rest.ClientRuntime_2.3.21/sdk/mgmtcommon/ClientRuntime/ClientRuntime/Serialization/JsonConverterHelper.cs#L40) doesn't consider the [`JsonProperty.PropertyConverter`](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_Serialization_JsonProperty_Converter.htm) when serializing.

After a bit of poking around, I don't see an easy fix without copying a lot more logic from [`JsonSerializerInternalWriter`](https://github.com/JamesNK/Newtonsoft.Json/blob/12.0.3/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs).  I also suspect there may be a lot more differences in serialization behavior due to the differences with `JsonSerializerInternalWriter.SerializeObject`, not to mention potential future divergence as features are added to Json.NET.

An alternative approach would be to use a proxy [`JsonWriter`](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonWriter.htm) which doesn't pass the opening [`WriteStartObject`](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_JsonWriter_WriteStartObject.htm) or closing [`WriteEndObject`](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_JsonWriter_WriteEndObject.htm) and removes the "properties." prefix from names.  A potential issue with this approach is that I don't see a foolproof way to recognize additional properties (from [`JsonExtensionDataAttribute`](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonExtensionDataAttribute.htm)) to avoid removing "properties.".  (I don't understand why this is done, so I'm not sure how much of an issue this is.)

Thoughts?

### PR DESCRIPTION
**Pull request by kevinoid**
If a property is declared with [`JsonConverterAttribute`](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonConverterAttribute.htm) and has a non-`null`
value, use the converter to write the value in
[`JsonConverterHelper.SerializeProperties`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.rest.serialization.jsonconverterhelper.serializeproperties), to match Json.NET behavior.

Fixes: #12490

### CODE REVIEW

**Review by jsquire — APPROVED** [review]
Hi @kevinoid.   Thank you very much for your contribution!   The changes look good to me.   I'm going to defer to @pakrym and @MiYanni for the final approval and merge.

**Comment by kevinoid** [comment]
My pleasure.  Thanks @jsquire!

**Review by isra-fel — APPROVED** [review]
Looks good to me! Thanks for you contribution!

**Comment by pakrym** [comment]
Do we need a similar change on the deserialization side?

**Comment by kevinoid** [comment]
> Do we need a similar change on the deserialization side?

Yes indeed.  Good catch!

I've updated the PR to use `JsonConverterAttribute` for deserialization as well (and also check `CanRead`/`CanWrite` before calling the converter to match Json.NET).

**Comment by pakrym** [comment]
LGTM

**Comment by kevinoid** [comment]
I just noticed I had forgotten to push the `CanRead`/`CanWrite` check.  Sorry about that.  Now fixed.

Thanks all for reviewing it!

**Comment by pakrym** [comment]
Can we add a test for the check?

**Comment by kevinoid** [comment]
> Can we add a test for the check?

I was afraid you'd ask for that.  Ha.  Will do.

**Comment by kevinoid** [comment]
I just added a commit with `CanRead`/`CanWrite` tests.  See what you think.

File: sdk/mgmtcommon/ClientRuntime/ClientRuntime/Serialization/JsonConverterHelper.cs [hunk 1]
```diff
@@ -77,7 +77,17 @@ public static void SerializeProperties(JsonWriter writer, object value, JsonSeri
                         propertyName = property.PropertyName.Substring("properties.".Length);
                     }
                     writer.WritePropertyName(propertyName);
-                    serializer.Serialize(writer, memberValue);
+
+                    if (memberValue != null
+                        && property.Converter != null
+                        && property.Converter.CanWrite)
```
Comment (MiYanni) [inline sdk/mgmtcommon/ClientRuntime/ClientRuntime/Serialization/JsonConverterHelper.cs:83]: Can be `memberValue != null && property.Converter?.CanWrite == true`.

File: sdk/mgmtcommon/ClientRuntime/ClientRuntime/Serialization/PolymorphicDeserializeJsonConverter.cs [hunk 2]
```diff
@@ -103,7 +103,21 @@ private JToken SelectTokenCaseInsensitive(JObject obj, string path)
                     var property = SelectTokenCaseInsensitive(item, expectedProperty.PropertyName);
                     if (property != null)
                     {
-                        var propertyValue = property.ToObject(expectedProperty.PropertyType, serializer);
+                        object propertyValue;
+                        if (expectedProperty.Converter != null
+                            && expectedProperty.Converter.CanRead)
```
Comment (MiYanni) [inline sdk/mgmtcommon/ClientRuntime/ClientRuntime/Serialization/PolymorphicDeserializeJsonConverter.cs:108]: Can be `expected.Converter?.CanRead == true`

**Review by MiYanni — CHANGES_REQUESTED** [review]

**Review by MiYanni — APPROVED** [review]
