### PR TITLE
ClientClosed exception reason removal

### LINKED ISSUE #12856: ObjectDisposedException vs ServiceBusException with FailureReason=ClientClosed
We are throwing an `ObjectDisposedException` in some places, but an `ServiceBusException` in others when the underlying resource is disposed. Since we don't actually expose a `CloseAsync` method on the client or `ServiceBusSender`/`ServiceBusReceiver`, but instead leverage `DisposeAsync` from `IAsyncDisposable`, I wonder if we should just throw `ObjectDisposedException` for all of these cases and do away with `FailureReason` of `ClientClosed`.

### PR DESCRIPTION
**Pull request by MiYanni**
Fixes: https://github.com/Azure/azure-sdk-for-net/issues/12856

Removed ClientClosed as a type of ServiceBusException. Replaced the instance of ClientClosed with a ObjectDisposed exception.

### CODE REVIEW

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Core/Argument.cs [hunk 1]
```diff
@@ -146,10 +146,7 @@ public static void AssertNotClosed(bool wasClosed, string targetName)
         {
             if (wasClosed)
             {
-                throw new ServiceBusException(
-                    string.Format(CultureInfo.CurrentCulture, Resources.ClosedInstanceCannotPerformOperation, targetName),
-                    ServiceBusException.FailureReason.ClientClosed,
-                    targetName);
+                throw new ObjectDisposedException(targetName, string.Format(CultureInfo.CurrentCulture, Resources.ClosedInstanceCannotPerformOperation, targetName));
```
Comment (JoshLove-msft) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Core/Argument.cs:149]: Do we still need AssertNotClosed or can we use AssertNotDisposed?

Comment (MiYanni) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Core/Argument.cs]: We did not need it anymore! I have updated it to be removed and used AssertNotDisposed instead. 😊

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpClient.cs [hunk 2]
```diff
@@ -120,7 +120,7 @@ internal class AmqpClient : TransportClient
             ServiceBusRetryPolicy retryPolicy,
             string identifier)
         {
-            Argument.AssertNotClosed(_closed, nameof(AmqpClient));
+            Argument.AssertNotDisposed(_closed, nameof(AmqpClient));
```
Comment (MiYanni) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpClient.cs:123]: Note: `_closed` here is only set to true in the DisposeAsync of the AmqpClient. So, it is the same as checking if it was disposed.

Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpClient.cs:123]: nit: can we just rename to _disposed?

**Review by JoshLove-msft — APPROVED** [review]
I think you will need to regenerate the API since we removed a public enum value.

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpClient.cs (hunk 2 above)
Comment (MiYanni) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpClient.cs:123]: In this case, the naming used for the AmqpClient matches that of the TransportClient and the ServiceBusConnection. I also thought about changing the name but it is exposed as `IsClosed`. The other places we call AssertNotDisposed have a `IsDisposed` property instead. I think it is fine if this instance uses it as `_closed`.

Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpClient.cs:123]: Those are all internal so we could just rename everything to IsDisposed, but your call.

Comment (MiYanni) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpClient.cs:123]: I think that they contextually makes sense for them to relate to closing. Currently, there is a 1-to-1 between disposing and closing (meaning DisposeAsync calls CloseAsync). But, I doubt a lot of this will change. If we go through the effort of pealing layers, it would make sense to remove the closing stuff. But, I don't think it is a big deal either way.
