### PR TITLE
[ApiManagement] Fix `BackendResponseCode` serialize issue

### LINKED ISSUE #38076: [BUG] Azure.ResourceManager.ApiManagement "Requested operation requires an element of type 'String', but the target element has type 'Number'" when using GetReportsByRequestAsync.
### Library name and version

Azure.ResourceManager.ApiManagement 1.0.1

### Describe the bug

When trying to use the GetReportsByRequestAsync() function, the request fails and gives the error "Requested operation requires an element of type 'String', but the target element has type 'Number'".

After some investigation we were able to see that the "BackendResponseCode" property is returned as an int when calling the API:

Example

But based on the code for the call, its expecting a string value:
https://github.com/Azure/azure-sdk-for-net/blob/2684d2c215c68f6cfa6c8992124eaf1b78826395/sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Generated/Models/RequestReportRecordContract.Serialization.cs#L30C13-L30C60

Code

In this case, it should be configured to use an int, just like the "responseCode" property is configured.

### Expected behavior

Reports are returned based on the filter provided.

### Actual behavior

Program flow is halted and error is returned.

### Reproduction Steps

Using the following code:

`static async Task Main()
        {
            // get azure access token
            TokenCredential cred = new DefaultAzureCredential();
            // authenticate your client
            ArmClient client = new ArmClient(cred);

 

            //Resource information.
            string subscriptionId = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxx";
            string resourceGroupName = "xxxxxxx";
            string serviceName = "xxxxxxxxx";

 

            //Get resource
            ResourceIdentifier apiManagementServiceResourceId = ApiManagementServiceResource.CreateResourceIdentifier(subscriptionId, resourceGroupName, serviceName);
            ApiManagementServiceResource apiManagementService = client.GetApiManagementServiceResource(apiManagementServiceResourceId);

 

            //Set filter and get reports.
            var filter = "timestamp ge datetime'2022-07-20T00:00:00.000Z' and timestamp le datetime'2023-07-20T23:59:59.999Z'";
            var records = await apiManagementService.GetReportsByRequestAsync(filter).ToListAsync();

 

            //Sample print
            Console.WriteLine(records);
        }`

Error returned:

Error

### Environment

Visual Studio 2022
Console App

.NET SDK:
Version:   7.0.306
Commit:    f500069cb7

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.19045
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  5.0.201 [C:\Program Files\dotnet\sdk]
  7.0.306 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
https://aka.ms/dotnet/info

Download .NET:
https://aka.ms/dotnet/download

### PR DESCRIPTION
**Pull request by melina5656**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/38076

### CODE REVIEW

**Comment by melina5656** [comment]
Linked issue: https://github.com/Azure/azure-sdk-for-net/issues/38076

**Comment by jsquire** [comment]
@melina5656:

Our automation is identifying you as a community contributor.  Please review the Azure SDK onboarding documentation and ensure that your GitHub organization membership and permissions are correct.
- [Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) _(Microsoft internal)_
- [Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) _(Microsoft internal)_

Please also be sure to add yourself to [CODEOWNERS](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS) for this library, if you will be maintaining it going forward.

File: sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Customized/Models/RequestReportRecordContract.cs [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+using System.Net;
+using Azure.Core;
+
+namespace Azure.ResourceManager.ApiManagement.Models
+{
+    /// <summary> Request Report data. </summary>
+    public partial class RequestReportRecordContract
+    {
+        /// <summary> The HTTP status code received by the gateway as a result of forwarding this request to the backend. </summary>
+        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
```
Comment (live1206) [inline sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Customized/Models/RequestReportRecordContract.cs:17]: minor: could be simplified to `[EditorBrowsable(EditorBrowsableState.Never)]`

File: sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Customized/Models/RequestReportRecordContract.cs [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+        [ObsoleteAttribute("This property has been replaced by BackendResponseCodeInteger", false)]
```
Comment (live1206) [inline sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Customized/Models/RequestReportRecordContract.cs:18]: minor: could be simplified to `[Obsolete("This property has been replaced by BackendResponseCodeInteger", false)]`

File: sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/autorest.md [hunk 3]
```diff
@@ -549,5 +552,7 @@ directive:
   - from: swagger-document
     where: $..[?(@.name=='$orderby')]
     transform: $['x-ms-client-name'] = 'orderBy'
-
+  - from: definitions.json
+    where: $.definitions.RequestReportRecordContract.properties.backendResponseCode
+    transform: $.type = "integer"
```
Comment (live1206) [inline sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/autorest.md:557]: out of curiosity, why not update swagger in the spec repo directly instead of using directive?

File: .github/CODEOWNERS [hunk 4]
```diff
@@ -112,7 +112,7 @@
 /sdk/analysisservices/Microsoft.Azure.Management.AnalysisServices/ @athipp @taiwu @minghan
 
 # ServiceLabel: %API Management %Service Attention
-/sdk/apimanagement/Microsoft.Azure.Management.ApiManagement/       @miaojiang
+/sdk/apimanagement/Microsoft.Azure.Management.ApiManagement/       @miaojiang @melina5656
```
Comment (live1206) [inline .github/CODEOWNERS:115]: revert this change since we SDK team will not be the code owner of this specific RP.

**Review by live1206 — COMMENTED** [review]
Please update the changelog to have this fix description, also mention the fixing issue in this PR description.

File: sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Customized/Models/RequestReportRecordContract.cs (hunk 1 above)
Comment (melina5656) [reply sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Customized/Models/RequestReportRecordContract.cs:17]: Resolved

File: sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Customized/Models/RequestReportRecordContract.cs (hunk 2 above)
Comment (melina5656) [reply sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Customized/Models/RequestReportRecordContract.cs:18]: Resolved

File: .github/CODEOWNERS (hunk 4 above)
Comment (melina5656) [reply .github/CODEOWNERS:115]: Resolved

File: sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/autorest.md (hunk 3 above)
Comment (melina5656) [reply sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/autorest.md]: Resolved

File: sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Customized/ArmApiManagementModelFactory.cs [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+        /// <param name="serviceTime"> he time it took to forward this request to the backend and get the response back. </param>
+        /// <param name="apiRegion"> Azure region where the gateway that processed this request is located. </param>
+        /// <param name="subscriptionResourceId"> Subscription identifier path. /subscriptions/{subscriptionId}. </param>
+        /// <param name="requestId"> Request Identifier. </param>
+        /// <param name="requestSize"> The size of this request.. </param>
+        /// <returns> A new <see cref="Models.RequestReportRecordContract"/> instance for mocking. </returns>
+        public static RequestReportRecordContract RequestReportRecordContract(string apiId = null, string operationId = null, string productId = null, string userId = null, RequestMethod? method = null, Uri uri = null, IPAddress ipAddress = null, string backendResponseCode = null, int? responseCode = null, int? responseSize = null, DateTimeOffset? timestamp = null, string cache = null, double? apiTime = null, double? serviceTime = null, string apiRegion = null, ResourceIdentifier subscriptionResourceId = null, string requestId = null, int? requestSize = null)
```
Comment (live1206) [inline sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Customized/ArmApiManagementModelFactory.cs:39]: Since `backendResponseCode` is obsolete, I think we should make this EB.Never and obsolete as well.

Comment (melina5656) [reply sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Customized/ArmApiManagementModelFactory.cs:42]: Resolved

**Comment by live1206** [comment]
The fix itself looks good to me, is it possible to have a test to cover this scenario?

File: sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Customized/Models/RequestReportRecordContract.cs [hunk 6]
```diff
@@ -0,0 +1,21 @@
...
+
+namespace Azure.ResourceManager.ApiManagement.Models
+{
+    /// <summary> Request Report data. </summary>
+    public partial class RequestReportRecordContract
+    {
+        /// <summary> The HTTP status code received by the gateway as a result of forwarding this request to the backend. </summary>
+        [EditorBrowsable(EditorBrowsableState.Never)]
+        [Obsolete("This property has been replaced by BackendResponseCodeInteger", false)]
+        public string BackendResponseCode => BackendResponseCodeInteger.ToString();
```
Comment (ArcturusZhang) [inline sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Customized/Models/RequestReportRecordContract.cs:19]: I kind of prefer we do not rename the property, instead, we introduce the `[CodeGenMemberSerializationHook]` attribute to this property to make sure it could properly serialize and deserialize.
For instance, in this case, previously we are deserializing this property using `property.Value.GetString`, using this attribute, we could change it to use:
`property.Value.GetInt32().ToString()`
this could leave our public API unchanged, but fix the JsonException

Comment (ArcturusZhang) [reply sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Customized/Models/RequestReportRecordContract.cs:19]: You could find some document here: https://github.com/Azure/autorest.csharp/blob/feature/v3/readme.md#change-the-implementation-of-serializationdeserialization-method-of-one-particular-property

Comment (melina5656) [reply sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Customized/Models/RequestReportRecordContract.cs]: Resolved.

**Comment by melina5656** [comment]
> The fix itself looks good to me, is it possible to have a test to cover this scenario?

There are already tests here.
[https://github.com/Azure/azure-sdk-for-net/blob/2614818ac2f65e28df246efc0ed5ea2bb34767e4/sdk/apimanagement/Azure.ResourceManager.ApiManagement/tests/Scenario/ApiManagementServiceResourceTests.cs#L198](url)

**Review by live1206 — APPROVED** [review]
