### PR TITLE
Fix NRE in ListPartitionIdsAsync when called before StartProcessingAsync

### LINKED ISSUE #51777: [BUG] NRE in EventProcessor if ListPartitionIdsAsync is called before StartProcessingAsync
### Library name and version

Azure.Messaging.EventHubs.Processor 5.12.0

### Describe the bug

Starting in version 5.12.0, if `ListPartitionIdsAsync` is called before `StartProcessingAsync` (e.g. if we want to do any pre-processing that requires the partition ids before we want to actually start processing messages), then the `ListPartitionIdsAsync` call throws NullReferenceException.

Commit 1d411119b38da792eb2254dfcd9779769126fab4 introduced an `EventHubProperties` property which is only initialized inside `StartProcessingAsync`, and changed `ListPartitionIdsAsync` to depend on that property.

### Expected behavior

`ListPartitionIdsAsync` should return the list of partition ids even if `StartProcessingAsync` hasn't been called.

### Actual behavior

`ListPartitionIdsAsync` throws NullReferenceException.

### Reproduction Steps

```cs
var processor = new PluggableCheckpointStoreEventProcessor(...);
var connection = processor.CreateConnection();
await processor.ListPartitionIdsAsync(connection, CancellationToken.None);
```

### Environment

Azure Cloud Services (Extended Support)
.NET 8.0.18

### PR DESCRIPTION
**Pull request by j7nw4r**
## Description

Fixes #51777

Starting in version 5.12.0, calling `ListPartitionIdsAsync` before `StartProcessingAsync` throws `NullReferenceException` because `EventHubProperties` is only initialized inside `StartProcessingAsync`.

## Changes

This change adds a null check with fallback to query the service directly when `EventHubProperties` is null, preserving the pre-5.12.0 behavior while maintaining efficiency when the processor is running.

### Before (broken)
\\\csharp
protected virtual Task<string[]> ListPartitionIdsAsync(...)
{
    return Task.FromResult(EventHubProperties.PartitionIds); // NRE if not started
}
\\\

### After (fixed)
\\\csharp
protected virtual async Task<string[]> ListPartitionIdsAsync(...)
{
    if (EventHubProperties != null)
    {
        return EventHubProperties.PartitionIds;
    }
    
    var properties = await connection.GetPropertiesAsync(RetryPolicy, cancellationToken).ConfigureAwait(false);
    return properties.PartitionIds;
}
\\\

## Testing

- [ ] Unit tests for calling `ListPartitionIdsAsync` before `StartProcessingAsync`
- [ ] Verify existing tests still pass

### CODE REVIEW

**Review by jsquire — APPROVED** [review]

File: sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs [hunk 1]
```diff
@@ -1363,7 +1363,34 @@ protected virtual LastEnqueuedEventProperties ReadLastEnqueuedEventProperties(st
...
+
+            if (EventHubProperties != null)
+            {
+                return Task.FromResult(EventHubProperties.PartitionIds);
+            }
+
+            // If EventHubProperties hasn't been initialized (processor not yet started),
+            // fall back to querying the service directly to preserve pre-5.12.0 behavior.
+
+            return ListPartitionIdsFromServiceAsync(connection, cancellationToken);
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs]:
```suggestion
            return await ListPartitionIdsFromServiceAsync(connection, cancellationToken).ConfigureAwait(false);
```

nit:  By convention, we don't elide the await in scenarios such as this in order to be consistent with fully-formed stack traces.

File: sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs [hunk 2]
```diff
@@ -1363,7 +1363,34 @@ protected virtual LastEnqueuedEventProperties ReadLastEnqueuedEventProperties(st
...
+        /// <summary>
+        ///   Queries the Event Hub service for the set of partition identifiers.
+        /// </summary>
+        ///
+        /// <param name="connection">The connection to the Event Hubs namespace to be used for service communication.</param>
+        /// <param name="cancellationToken">A <see cref="CancellationToken"/> instance to signal the request to cancel the operation.</param>
+        ///
+        /// <returns>The set of identifiers for the Event Hub partitions.</returns>
+        ///
+        private async Task<string[]> ListPartitionIdsFromServiceAsync(EventHubConnection connection,
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs]: Not sure that I see the value in encapsulating this in a method.  It creates another state machine for what would be a single line of code:

```csharp
return await connection.GetPartitionIdsAsync(RetryPolicy, cancellationToken).ConfigureAwait(false);
```

I think we'd be better off just removing the method and doing the call inline.

**Review by jsquire — APPROVED** [review]

**Comment by jsquire** [comment]
Something in the pipelines burped and CI was not run.   Closing/reopening to reset.
