### PR TITLE
Exceptions and Event Source Logging

### LINKED ISSUE #9879: ServiceBusException issues
- eliminate unnecessary constructors
- eliminate anything that is only used for EH
- determine whether ctors can be made internal
  - This would make testing across packages more difficult and also make customer testing more difficult if we only expose the protected ctor. These should be fine to leave as public.
- throw correct exceptions for all features being added in Preview 1
- Integrate necessary features of AmqpExceptionHelper(from Track 1) into AmqpError(from EH Track 2)
https://github.com/Azure/azure-sdk-for-net/pull/10000#discussion_r380706470

### PR DESCRIPTION
**Pull request by JoshLove-msft**
- Log appropriate exceptions
- Add event source logging
- Add SessionLockLost handling
- General clean up
- Add new tests and start migrating tests from Track 1

Fixes https://github.com/Azure/azure-sdk-for-net/issues/9879, https://github.com/Azure/azure-sdk-for-net/issues/9875, and https://github.com/Azure/azure-sdk-for-net/issues/10158

### CODE REVIEW

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs [hunk 1]
```diff
@@ -78,13 +77,6 @@ internal class AmqpConnectionScope : TransportConnectionScope
         ///
         private static TimeSpan AuthorizationRefreshTimeout { get; } = TimeSpan.FromMinutes(3);
 
-        /// <summary>
-        ///   The recommended timeout to associate with an AMQP session.  It is recommended that this
-        ///   interval be used when creating or opening AMQP links and related constructs.
-        /// </summary>
-        ///
-        public override TimeSpan SessionTimeout { get; } = TimeSpan.FromSeconds(30);
```
Comment (JoshLove-msft) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs]: This was moved to TransportConnectionScope.

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs [hunk 2]
```diff
@@ -532,17 +688,30 @@ internal void ThrowIfNotPeekLockMode()
...
         {
             Argument.AssertNotClosed(IsClosed, nameof(ServiceBusReceiver));
             ThrowIfNotPeekLockMode();
-            DateTime lockedUntilUtc = await _innerReceiver.RenewMessageLockAsync(
-                message.LockToken,
-                cancellationToken).ConfigureAwait(false);
-            message.LockedUntilUtc = lockedUntilUtc;
-            // MessagingEventSource.Log.MessageRenewLockStart(this.ClientId, 1, lockToken);
+            cancellationToken.ThrowIfCancellationRequested<TaskCanceledException>();
+            ServiceBusEventSource.Log.RenewMessageLockStart(Identifier, 1, message.LockToken);
```
Comment (ShivangiReja) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs]: Missing null check for `message`.

Comment (ShivangiReja) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs]: Can we also add null checks in other methods?

File: sdk/servicebus/Azure.Messaging.ServiceBus/tests/Message/MessageLiveTests.cs [hunk 3]
```diff
@@ -0,0 +1,93 @@
...
+                Assert.IsInstanceOf(typeof(string), receivedMsg.Properties["string"]);
+                Assert.IsInstanceOf(typeof(Uri), receivedMsg.Properties["Uri"]);
+                Assert.IsInstanceOf(typeof(DateTime), receivedMsg.Properties["DateTime"]);
+                Assert.IsInstanceOf(typeof(DateTimeOffset), receivedMsg.Properties["DateTimeOffset"]);
+                Assert.IsInstanceOf(typeof(TimeSpan), receivedMsg.Properties["TimeSpan"]);
+            }
+        }
+
+        [Test]
+        public async Task Can_Send_Message_With_Max_Size()
```
Comment (ShivangiReja) [inline sdk/servicebus/Azure.Messaging.ServiceBus/tests/Message/MessageLiveTests.cs]: nit: Just for the consistency, can we remove `_` from the method names?

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs [hunk 4]
```diff
@@ -194,15 +223,22 @@ public class ServiceBusReceiver : IAsyncDisposable
...
-            finally
+            catch (Exception exception)
             {
-                // TODO: Add log - SeviceBusEventSource.Log.ReceiveBatchAsyncComplete();
+                ServiceBusEventSource.Log.ReceiveMessageException(Identifier, exception);
+                throw;
             }
+
+            cancellationToken.ThrowIfCancellationRequested<TaskCanceledException>();
+            ServiceBusEventSource.Log.ReceiveMessageComplete(Identifier, maxMessages);
```
[the remark this answers is not in the document]
Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs]: I was intentionally leaving these out of the finally block since if an exception is thrown we probably don't want to log that the operation was completed.

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs [hunk 5]
```diff
@@ -62,7 +62,7 @@ internal class AmqpReceiver : TransportReceiver
         ///   The AMQP connection scope responsible for managing transport constructs for this instance.
         /// </summary>
         ///
-        private readonly AmqpConnectionScope _connectionScope;
+        private AmqpConnectionScope _connectionScope { get; }
```
[the remark this answers is not in the document]
Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs]: Do you mean since it is not readonly it should be ConnectionScope?

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs [hunk 6]
```diff
@@ -150,37 +174,42 @@ public class ServiceBusReceiver : IAsyncDisposable
...
             PrefetchCount = options.PrefetchCount;
             EntityName = entityName;
+            IsSessionReceiver = isSessionEntity;
             _innerReceiver = _connection.CreateTransportReceiver(
                 entityName: EntityName,
-                retryPolicy: RetryPolicy,
+                retryPolicy: _retryPolicy,
                 receiveMode: ReceiveMode,
-                prefetchCount: (uint) PrefetchCount,
+                prefetchCount: (uint)PrefetchCount,
```
[the remark this answers is not in the document]
Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs]: We need to cast to uint since the public type is an int, but the type expected by AMQP layer is uint. We have validation in the property getter that ensures it is >= 0.

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs [hunk 7]
```diff
@@ -195,12 +198,12 @@ private void CloseLink(ReceivingAmqpLink link)
...
         ///
-        internal async Task<IList<ServiceBusReceivedMessage>> ReceiveBatchAsyncInternal(
+        private async Task<IList<ServiceBusReceivedMessage>> ReceiveBatchAsyncInternal(
             int maximumMessageCount,
             TimeSpan timeout,
             CancellationToken cancellationToken)
         {
-            Argument.AssertNotClosed(_closed, nameof(ServiceBusReceiver));
+            Argument.AssertNotClosed(_closed, nameof(AmqpReceiver));
             Argument.AssertAtLeast(maximumMessageCount, 1, nameof(maximumMessageCount));
```
[the remark this answers is not in the document]
Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs]: Removed

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Diagnostics/ServiceBusEventSource.cs [hunk 8]
```diff
@@ -36,562 +40,396 @@ private ServiceBusEventSource()
...
             if (IsEnabled())
             {
-                WriteEvent(26, entityName ?? string.Empty, errorMessage ?? string.Empty);
+                WriteEvent(37, identifier, receiveLinkName, receiveLinkState.ToString(), isSessionReceiver, exception.ToString());
+            }
+        }
+
+        [Event(38, Level = EventLevel.Error, Message = "SessionReceiver Link Closed. identifier: {0}, SessionId: {1}, linkException: {2}.")]
+        public void SessionReceiverLinkClosed(string identifier, string sessionId, Exception linkException)
+        {
```
[the remark this answers is not in the document]
Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Diagnostics/ServiceBusEventSource.cs]: Did a reformat

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs [hunk 9]
```diff
@@ -511,16 +534,17 @@ public virtual async Task StopProcessingAsync(CancellationToken cancellationToke
...
+            {
+                ServiceBusEventSource.Log.StopProcessingException(Identifier, exception);
+                throw;
             }
             finally
             {
                 ProcessingStartStopSemaphore.Release();
-                //Logger.EventProcessorStopComplete(Identifier);
             }
+            ServiceBusEventSource.Log.StopProcessingComplete(Identifier);
```
[the remark this answers is not in the document]
Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs]: I was intentionally leaving these out of the finally block since if an exception is thrown we probably don't want to log that the operation was completed.

[the remark this answers is not in the document]
Comment (ShivangiReja) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs]: I'm fine either way but in Event Hubs we log this even if the exception thrown.

This log is just saying "This method has been completed". It is not saying "This method has been successfully completed".

But again no strong opinion :)

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (ShivangiReja) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs]: Same as above.

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (ShivangiReja) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs]: Yes.

**Review by ShivangiReja — APPROVED** [review]

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs (hunk 9 above)
[the remark this answers is not in the document]
Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs]: Yeah, I guess I was going with how this was done in Track 1 SB. Also, don't really have a strong opinion on this, but I think it is fine to leave as is for now.

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs [hunk 10]
```diff
@@ -251,7 +243,7 @@ protected AmqpConnectionScope()
             var connection = await ActiveConnection.GetOrCreateAsync(timeout).ConfigureAwait(false);
             cancellationToken.ThrowIfCancellationRequested<TaskCanceledException>();
 
-            var link = await CreateReceivingLinkAsync(
+            ReceivingAmqpLink link = await CreateReceivingLinkAsync(
```
Comment (SeanFeldman) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs]: Is there a reason not to use `var`?

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessErrorEventArgs.cs [hunk 11]
```diff
@@ -37,12 +40,12 @@ public ProcessErrorEventArgs(Exception exception, ExceptionReceivedEventArgsActi
         public ExceptionReceivedEventArgsAction Action { get; }
 
         /// <summary>The namespace name used when this exception occurred.</summary>
-        public string Endpoint { get; }
+        public string FullyQualifiedNamespace { get; }
```
Comment (SeanFeldman) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessErrorEventArgs.cs]: This is a namespace name. What's a fully qualified namespace? There's an FQDN, but doesn't seem like what you've meant.

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessErrorEventArgs.cs [hunk 12]
```diff
@@ -37,12 +40,12 @@ public ProcessErrorEventArgs(Exception exception, ExceptionReceivedEventArgsActi
...
 
         /// <summary>The entity path used when this exception occurred.</summary>
-        public string EntityPath { get; }
+        public string EntityName { get; }
 
         /// <summary>The Client Id associated with the sender, receiver or session when this exception occurred.</summary>
-        public string ClientId { get; }
+        public string Identifier { get; }
```
Comment (SeanFeldman) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessErrorEventArgs.cs]: A very cryptic name. An identifier is a very overloaded term.

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs [hunk 13]
```diff
@@ -349,18 +370,29 @@ public virtual async Task CloseAsync(CancellationToken cancellationToken = defau
...
             if (ActiveReceiveTask == null && MessageHandlerSemaphore == null)
             {
-                MessageHandlerSemaphore = new SemaphoreSlim(
-                    MaxConcurrentCalls,
-                    MaxConcurrentCalls);
+                ServiceBusEventSource.Log.StartProcessingStart(Identifier);
                 await ProcessingStartStopSemaphore.WaitAsync(cancellationToken).ConfigureAwait(false);
+                if (_processMessage == null)
+                {
+                    throw new InvalidOperationException(string.Format(CultureInfo.CurrentCulture, Resources1.CannotStartEventProcessorWithoutHandler, nameof(ProcessMessageAsync)));
```
Comment (SeanFeldman) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs]: `Resources1`? 😄

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessErrorEventArgs.cs (hunk 12 above)
Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessErrorEventArgs.cs]: This corresponds to the ClientId from the Track 1 library, but we were thinking that ClientId was a bit overloaded based on the ClientId from AAD. 
We are actually planning on making this internal for now, but if we need it to be public we could consider other names.

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs (hunk 13 above)
Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs]: Hehe, yeah we have an issue to go and fix this - https://github.com/Azure/azure-sdk-for-net/issues/9918

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessErrorEventArgs.cs (hunk 11 above)
Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessErrorEventArgs.cs]: So this would be the host name for the account, e.g. {yournamespace}.servicebus.windows.net

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs (hunk 10 above)
Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs]: We have a StyleCop rule to avoid using var except when used with constructors or literals where it is obvious what the type would be. This should make it easier to see the type without digging into the code that is being called.

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessErrorEventArgs.cs (hunk 12 above)
Comment (SeanFeldman) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessErrorEventArgs.cs]: > we were thinking

I really want to be sarcastic here and say "Why not ask the community?" but then it will be bad of me, right? 😉 

The mental jump from SB client to AAD is a substantial leap. I'm not sure this would necessarily be an issue. And even if it would, does any 'client ID' automatically means AAD? Perhaps context is more important? Or an XML document that can explain what it is it if in doubt. Just saying.

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessErrorEventArgs.cs (hunk 11 above)
Comment (SeanFeldman) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessErrorEventArgs.cs]: If this is the hostname for the account, then it's an FQDN (FullyQualifiedDomainName).
What I'm trying to say is that there's no namespace and fully qualified namespace. There are namespace and FQDN. Correct me if I'm wrong, @nemakam.

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs (hunk 10 above)
Comment (SeanFeldman) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs]: Got it, thanks.

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessErrorEventArgs.cs (hunk 12 above)
Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessErrorEventArgs.cs]: What do you think in general about not exposing this property as public?

Comment (SeanFeldman) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessErrorEventArgs.cs]: For customers that do use message handlers (or message processor in track2 I assume), if it's a single client that is failing, not sure how much value it will provide. But the moment they have more than one processor, that's a different conversation. I've stopped using the built-in message pump and it's not something that would help my scenarios.
