### PR TITLE
Fix missing parameters in constructor during multi-layer flatten calls

### LINKED ISSUE #55110: Missing parameters in the constructor of the intermediate layer class during multi-layer flatten calls
This issue occurred in the fleet, and the screenshot of the problem is as follows:

Image

The constructor implementation of the `AutoUpgradeProfileProperties` class is as follows:

``` csharp 
internal AutoUpgradeProfileProperties(AutoUpgradeProfileProvisioningState? provisioningState, ResourceIdentifier updateStrategyId, ContainerServiceFleetUpgradeChannel? channel, AutoUpgradeNodeImageSelection nodeImageSelection, bool? disabled, AutoUpgradeProfileStatus autoUpgradeProfileStatus, string targetKubernetesVersion, bool? longTermSupport, IDictionary<string, BinaryData> additionalBinaryDataProperties)
{
    ProvisioningState = provisioningState;
    UpdateStrategyId = updateStrategyId;
    Channel = channel;
    NodeImageSelection = nodeImageSelection;
    Disabled = disabled;
    AutoUpgradeProfileStatus = autoUpgradeProfileStatus;
    TargetKubernetesVersion = targetKubernetesVersion;
    LongTermSupport = longTermSupport;
    _additionalBinaryDataProperties = additionalBinaryDataProperties;
}
```

The implementation in TSP is as follows:

``` typespec
@resource("autoUpgradeProfiles")
@parentResource(Fleet)
@added(Versions.v2024_05_02_preview)
@doc("The AutoUpgradeProfile resource.")
model AutoUpgradeProfile
  is Azure.ResourceManager.ProxyResource<AutoUpgradeProfileProperties> {
  @doc("The name of the AutoUpgradeProfile resource.")
  @key("autoUpgradeProfileName")
  @segment("autoUpgradeProfiles")
  @pattern("^[a-z0-9]([-a-z0-9]*[a-z0-9])?$")
  @minLength(1)
  @maxLength(50)
  @path
  @visibility(Lifecycle.Create, Lifecycle.Read)
  name: string;

  ...EntityTagProperty;
}

...

@doc("The properties of the AutoUpgradeProfile.")
@added(Versions.v2024_05_02_preview)
model AutoUpgradeProfileProperties {
  @visibility(Lifecycle.Read)
  @doc("The provisioning state of the AutoUpgradeProfile resource.")
  provisioningState?: AutoUpgradeProfileProvisioningState;

  @visibility(Lifecycle.Create, Lifecycle.Read)
  @doc("The resource id of the UpdateStrategy resource to reference. If not specified, the auto upgrade will run on all clusters which are members of the fleet.")
  updateStrategyId?: FleetUpdateStrategyResourceId;

  @doc("Configures how auto-upgrade will be run.")
  channel: UpgradeChannel;

  @doc("The node image upgrade to be applied to the target clusters in auto upgrade.")
  nodeImageSelection?: AutoUpgradeNodeImageSelection;

  @doc("""
    If set to False: the auto upgrade has effect - target managed clusters will be upgraded on schedule.
    If set to True: the auto upgrade has no effect - no upgrade will be run on the target managed clusters.
    This is a boolean and not an enum because enabled/disabled are all available states of the auto upgrade profile.
    By default, this is set to False.
    """)
  disabled?: boolean;

  @doc("The status of the auto upgrade profile.")
  @added(Versions.v2025_03_01)
  autoUpgradeProfileStatus?: AutoUpgradeProfileStatus;

  @doc("""
      This is the target Kubernetes version for auto-upgrade. The format must be `{major version}.{minor version}`. For example, "1.30".
      By default, this is empty.
      If upgrade channel is set to TargetKubernetesVersion, this field must not be empty.
      If upgrade channel is Rapid, Stable or NodeImage, this field must be empty.
    """)
  @added(Versions.v2025_04_01_preview)
  targetKubernetesVersion?: string;

  @doc("""
      If upgrade channel is not TargetKubernetesVersion, this field must be False.
      If set to True: Fleet auto upgrade will continue generate update runs for patches of minor versions earlier than N-2 
      (where N is the latest supported minor version) if those minor versions support Long-Term Support (LTS).
      By default, this is set to False.
      For more information on AKS LTS, please see https://learn.microsoft.com/en-us/azure/aks/long-term-support
    """)
  @added(Versions.v2025_04_01_preview)
  longTermSupport?: boolean;
}

...

@doc("The node image upgrade to be applied to the target clusters in auto upgrade.")
@added(Versions.v2024_05_02_preview)
model AutoUpgradeNodeImageSelection {
  @visibility(Lifecycle.Create, Lifecycle.Read)
  @doc("The node image upgrade type.")
  type: AutoUpgradeNodeImageSelectionType;
}
```

The Swagger-related content is as follows:

``` xml
"AutoUpgradeProfile": {
      "type": "object",
      "description": "The AutoUpgradeProfile resource.",
      "properties": {
        "properties": {
          "$ref": "#/definitions/AutoUpgradeProfileProperties",
          "description": "The resource-specific properties for this resource.",
          "x-ms-client-flatten": true
        },
        "eTag": {
          "type": "string",
          "description": "If eTag is provided in the response body, it may also be provided as a header per the normal etag convention.  Entity tags are used for comparing two or more entities from the same requested resource. HTTP/1.1 uses entity tags in the etag (section 14.19), If-Match (section 14.24), If-None-Match (section 14.26), and If-Range (section 14.27) header fields.",
          "readOnly": true
        }
      },
      "allOf": [
        {
          "$ref": "../../../../../../common-types/resource-management/v5/types.json#/definitions/ProxyResource"
        }
      ]
    },

...

"AutoUpgradeProfileProperties": {
      "type": "object",
      "description": "The properties of the AutoUpgradeProfile.",
      "properties": {
        "provisioningState": {
          "$ref": "#/definitions/AutoUpgradeProfileProvisioningState",
          "description": "The provisioning state of the AutoUpgradeProfile resource.",
          "readOnly": true
        },
        "updateStrategyId": {
          "$ref": "#/definitions/FleetUpdateStrategyResourceId",
          "description": "The resource id of the UpdateStrategy resource to reference. If not specified, the auto upgrade will run on all clusters which are members of the fleet.",
          "x-ms-mutability": [
            "read",
            "create"
          ]
        },
        "channel": {
          "$ref": "#/definitions/UpgradeChannel",
          "description": "Configures how auto-upgrade will be run."
        },
        "nodeImageSelection": {
          "$ref": "#/definitions/AutoUpgradeNodeImageSelection",
          "description": "The node image upgrade to be applied to the target clusters in auto upgrade."
        },
        "disabled": {
          "type": "boolean",
          "description": "If set to False: the auto upgrade has effect - target managed clusters will be upgraded on schedule.\nIf set to True: the auto upgrade has no effect - no upgrade will be run on the target managed clusters.\nThis is a boolean and not an enum because enabled/disabled are all available states of the auto upgrade profile.\nBy default, this is set to False."
        },
        "autoUpgradeProfileStatus": {
          "$ref": "#/definitions/AutoUpgradeProfileStatus",
          "description": "The status of the auto upgrade profile."
        },
        "targetKubernetesVersion": {
          "type": "string",
          "description": "  This is the target Kubernetes version for auto-upgrade. The format must be `{major version}.{minor version}`. For example, \"1.30\".\n  By default, this is empty.\n  If upgrade channel is set to TargetKubernetesVersion, this field must not be empty.\n  If upgrade channel is Rapid, Stable or NodeImage, this field must be empty."
        },
        "longTermSupport": {
          "type": "boolean",
          "description": "  If upgrade channel is not TargetKubernetesVersion, this field must be False.\n  If set to True: Fleet auto upgrade will continue generate update runs for patches of minor versions earlier than N-2 \n  (where N is the latest supported minor version) if those minor versions support Long-Term Support (LTS).\n  By default, this is set to False.\n  For more information on AKS LTS, please see https://learn.microsoft.com/en-us/azure/aks/long-term-support"
        }
      },
      "required": [
        "channel"
      ]
    },

...

"AutoUpgradeNodeImageSelection": {
      "type": "object",
      "description": "The node image upgrade to be applied to the target clusters in auto upgrade.",
      "properties": {
        "type": {
          "$ref": "#/definitions/AutoUpgradeNodeImageSelectionType",
          "description": "The node image upgrade type.",
          "x-ms-mutability": [
            "read",
            "create"
          ]
        }
      },
      "required": [
        "type"
      ]
    },
```

### PR DESCRIPTION
**Pull request by live1206**
## Fix

Fixes #55110

### Problem

When a [CodeGenMember] customization moves a property to a different position in the property list (e.g., Channel from position 3 to last), `BuildConstructorParameters` in `FlattenPropertyVisitor` used a forward-only cursor (`flattenedPropertyIndex`) that would jump past all intermediate properties when finding a name match far ahead. This caused the loop to exit early, leaving remaining constructor parameters without arguments.

For example, in the ContainerServiceFleet `AutoUpgradeProfileProperties` scenario:
- Constructor expects: `provisioningState, updateStrategyId, channel, nodeImageSelection, disabled, ...`
- Flattened properties (with customization): `provisioningState, updateStrategyId, disabled, ..., channel` (channel is last due to `[CodeGenMember]`)
- The old code would match `channel` at the end, skip everything in between, and exit the loop early

### Fix

Replaced the forward-only `flattenedPropertyIndex` cursor with a `HashSet<int>` tracking used indices. This allows name matches to be found at any position without skipping intermediate properties that may be needed for subsequent constructor parameters.

### Testing

- Added a test case in `Mgmt-TypeSpec` that reproduces the fleet scenario:
  - A model with `@flattenProperty` containing a safe-flattened sub-model (`AutoUpgradeNodeImageSelection`) and a required property (`channel`)
  - A `[CodeGenMember]` customization that overrides the `Channel` property, causing it to appear at a different position in the property list
- Verified the bug reproduces without the fix (build failure: `CS7036: There is no argument given that corresponds to the required parameter 'disabled'`)
- Verified the fix resolves the build failure and generates correct constructor calls with all parameters

### CODE REVIEW

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/FlattenPropertyVisitor.cs [hunk 1]
```diff
@@ -258,18 +248,32 @@ private ValueExpression[] BuildConstructorParameters(CSharpType propertyType, Li
                         ? parameter.Property("Value")
```
[the remark this answers is not in the document]
Comment (live1206) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/FlattenPropertyVisitor.cs:248]: since this has been in the code base previously and there is no sdk diff for regen all. I will keep as it is.

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/FlattenPropertyVisitor.cs [hunk 2]
```diff
@@ -258,18 +248,30 @@ private ValueExpression[] BuildConstructorParameters(CSharpType propertyType, Li
...
-                    flattenedPropertyIndex = nameMatchIndex + 1;
+                    usedFlattenedPropertyIndices.Add(nameMatchIndex);
                 }
                 else
                 {
-                    // No name match found, try to match by type with current flattened property
-                    var (flattenedProperty, _) = flattenedProperties[flattenedPropertyIndex];
-                    var flattenedPropertyType = flattenedProperty.Type;
+                    // No name match found, try to match by type with unused flattened properties
+                    var typeMatchIndex = -1;
```
Comment (ArcturusZhang) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/FlattenPropertyVisitor.cs:256]: I thought last time we are matching these by using the property instances storing in the `FlattenedPropertyProvider` derived type of `PropertyProvider` somewhere?
It is not perfect if we are matching properties by name and/or types.

**Review by ArcturusZhang — APPROVED** [review]

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/FlattenPropertyVisitor.cs (hunk 2 above)
Comment (live1206) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/FlattenPropertyVisitor.cs:256]: `FlattenedPropertyProvider` distinguishes which properties are flattened properties from the normal ones. Here, we already got the flattened properties from the input `flattenedProperties`. When we iterate them, we need to take consideration of order changes caused by custom code.
