### PR TITLE
[AppContainers] Fix AppContainersSkuName NullReferenceException

### LINKED ISSUE #56807: [BUG] AppContainersSkuName methods throw NullReferenceException
### Library name and version

Azure.ResourceManager.AppContainers tested with 1.4.1 and 1.5.0

### Describe the bug

Accessing `AppContainersSkuName.Premium` or calling the constructor with `AppContainersSkuName("Premium")` throws a NullReferenceException.

I'm not sure how to set `ContainerAppManagedEnvironmentData.SkuName = ...` to any value since all AppContainersSkuName methods throw a NullReferenceException. This means I cannot create a workload-profiles-enabled Container Apps Environment using the .NET SDK. The `Consumption` and `Premium` SKU names are both inaccessible...

## Repro

```csharp
using Azure.ResourceManager.AppContainers.Models;

var sku1 = AppContainersSkuName.Premium;           // throws
var sku2 = new AppContainersSkuName("Premium");     // throws
```

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Azure.ResourceManager.AppContainers.Models.AppContainersSkuName.get_Premium()
```

### Expected behavior

AppContainersSkuName.Premium returns a proper AppContainersSkuName object.

### Actual behavior

AppContainersSkuName.Premium throws a NullReferenceException.

### Reproduction Steps

var x = AppContainersSkuName.Premium;

### Environment

_No response_

### PR DESCRIPTION
**Pull request by ArcturusZhang**
## Fix

The custom `AppContainersSkuName` struct was written with `throw null;` stubs (API listing format) instead of actual implementations when it was added to preserve backward compatibility after the type was removed from the service spec. This caused `NullReferenceException` on every operation - constructor, static properties, operators, etc.

This PR restores the original generated extensible enum implementation (matching the code from before commit 04dba6ae which removed it).

## Repro (before fix)

```csharp
var sku = AppContainersSkuName.Premium; // throws NullReferenceException
var sku2 = new AppContainersSkuName("Premium"); // throws NullReferenceException
```

Fixes #56807

### CODE REVIEW

File: sdk/containerapps/Azure.ResourceManager.AppContainers/src/Custom/ContainerAppManagedEnvironmentData.cs [hunk 1]
```diff
@@ -16,8 +12,12 @@ namespace Azure.ResourceManager.AppContainers
...
     public partial class ContainerAppManagedEnvironmentData : TrackedResourceData
     {
+        // This property and the AppContainersSkuName type were removed from the service spec
+        // but are preserved here as hidden members to avoid breaking existing consumers.
+        // See https://github.com/Azure/azure-sdk-for-net/issues/56807
+
         /// <summary> SkuName for container app. </summary>
         [EditorBrowsable(EditorBrowsableState.Never)]
-        public Azure.ResourceManager.AppContainers.Models.AppContainersSkuName? SkuName { get; set; }
+        public AppContainersSkuName? SkuName { get; set; }
```
Comment (live1206) [inline sdk/containerapps/Azure.ResourceManager.AppContainers/src/Custom/ContainerAppManagedEnvironmentData.cs:24]: if this property is no longer supported, shall we just throw for it?

Comment (live1206) [inline sdk/containerapps/Azure.ResourceManager.AppContainers/src/Custom/ContainerAppManagedEnvironmentData.cs:24]: And since this is removed from the service, can we just make it obsolete so that user knows? also for the type.

Comment (ArcturusZhang) [reply sdk/containerapps/Azure.ResourceManager.AppContainers/src/Custom/ContainerAppManagedEnvironmentData.cs:24]: since this is a property there is no "implementation" at all, we do not have to intentionally throws.
Adding the Obsolete should be enough as hint to our customers.

**Review by live1206 — APPROVED** [review]
