### PR TITLE
Test failure should fail CI

### LINKED ISSUE #50007: Mgmt CI does fail when the UT of MPG generator failes
https://dev.azure.com/azure-sdk/public/_build/results?buildId=4848906&view=logs&j=5c952eb6-394a-5f6b-81c4-fd6e00460747&t=324a3550-b8a5-548f-4819-7b5944e418be&l=281

### PR DESCRIPTION
**Pull request by live1206**
Currently, the UT in MPG generator are failing but mgmt-ci doesn't fail.
Resolves https://github.com/Azure/azure-sdk-for-net/issues/50007 https://github.com/Azure/azure-sdk-for-net/issues/49742

- Stop on any failure in Test-Emitter.ps1, I could not figure out a good way to continue the run and gather all the errors in the end
- Fix emitter test failures
- Fix generator test failures
- Fix "dotnet test" failure

### CODE REVIEW

File: eng/packages/http-client-csharp/emitter/test/Unit/test-util.ts [hunk 1]
```diff
@@ -119,22 +120,5 @@ export async function createCSharpSdkContext(
     "@typespec/http-client-csharp",
     sdkContextOptions
   );
-  return {
-    ...context,
-    logger: new Logger(program.program, LoggerLevel.INFO),
-    __typeCache: {
```
Comment (live1206) [inline eng/packages/http-client-csharp/emitter/test/Unit/test-util.ts:125]: this is causing stackoverflow, because we depend on cache to break the loop

File: eng/packages/http-client-csharp/emitter/test/Unit/test-util.ts [hunk 2]
```diff
@@ -119,22 +120,5 @@ export async function createCSharpSdkContext(
...
-      models: new Map(),
-      enums: new Map(),
-      clients: new Map(),
-      properties: new Map(),
-      responses: new Map(),
-      updateSdkClientReferences: () => {},
-      updateSdkPropertyReferences: () => {},
-      updateSdkResponseReferences: () => {},
-      updateSdkTypeReferences: () => {},
-      updateTypeCache: () => {}
```
Comment (live1206) [inline eng/packages/http-client-csharp/emitter/test/Unit/test-util.ts:137]: this is causing stackoverflow, because we depend on cache to break the loop

File: eng/packages/http-client-csharp/package-lock.json [hunk 3]
```diff
@@ -444,32 +444,32 @@
       }
```
Comment (jorgerangel-msft) [inline eng/packages/http-client-csharp/package-lock.json:444]: We are updating the lock file but are not checking in an update to the `package.json` files. Did you mean to exclude the lock files from the PR?

File: eng/packages/http-client-csharp/emitter/test/Unit/test-util.ts (hunk 2 above)
Comment (jorgerangel-msft) [reply eng/packages/http-client-csharp/emitter/test/Unit/test-util.ts:137]: Thank you for finding the root cause of this!

File: eng/packages/http-client-csharp/generator/Azure.Generator/test/common/Azure.Generator.Tests.Common.csproj [hunk 4]
```diff
@@ -4,7 +4,7 @@
     <TargetFramework>net8.0</TargetFramework>
     <ImplicitUsings>enable</ImplicitUsings>
     <Nullable>enable</Nullable>
-    <IsTestProject>true</IsTestProject>
+		<IsTestSupportProject>true</IsTestSupportProject>
```
Comment (live1206) [inline eng/packages/http-client-csharp/generator/Azure.Generator/test/common/Azure.Generator.Tests.Common.csproj:7]: this is not a test project, and it is causing error in CI
> Testhost process for source(s) '/mnt/vss/_work/1/s/artifacts/bin/Azure.Generator.Tests.Common/Debug/net8.0/Azure.Generator.Tests.Common.dll' exited with error: Error:
  An assembly specified in the application dependencies manifest (Azure.Generator.Tests.Common.deps.json) was not found:
    package: 'Azure.Core', version: '1.46.1'
    path: 'lib/net8.0/Azure.Core.dll'

https://dev.azure.com/azure-sdk/public/_build/results?buildId=4859942&view=logs&j=5c952eb6-394a-5f6b-81c4-fd6e00460747&t=324a3550-b8a5-548f-4819-7b5944e418be&l=215

File: eng/packages/http-client-csharp/generator/Azure.Generator/test/common/Azure.Generator.Tests.Common.csproj [hunk 5]
```diff
@@ -4,7 +4,7 @@
     <TargetFramework>net8.0</TargetFramework>
     <ImplicitUsings>enable</ImplicitUsings>
     <Nullable>enable</Nullable>
-    <IsTestProject>true</IsTestProject>
+    <IsTestSupportProject>true</IsTestSupportProject>
```
Comment (live1206) [inline eng/packages/http-client-csharp/generator/Azure.Generator/test/common/Azure.Generator.Tests.Common.csproj:7]: this is not a test project, and it is causing error in CI
> Testhost process for source(s) '/mnt/vss/_work/1/s/artifacts/bin/Azure.Generator.Tests.Common/Debug/net8.0/Azure.Generator.Tests.Common.dll' exited with error: Error:
  An assembly specified in the application dependencies manifest (Azure.Generator.Tests.Common.deps.json) was not found:
    package: 'Azure.Core', version: '1.46.1'
    path: 'lib/net8.0/Azure.Core.dll'

https://dev.azure.com/azure-sdk/public/_build/results?buildId=4859942&view=logs&j=5c952eb6-394a-5f6b-81c4-fd6e00460747&t=324a3550-b8a5-548f-4819-7b5944e418be&l=215

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Mgmt/test/Azure.Generator.Mgmt.Tests/Providers/TestData/ResourceClientProviderTests/Verify_AsyncOperationMethod.cs [hunk 6]
```diff
@@ -1,4 +1,4 @@
-﻿using global::Azure.Core.Pipeline.DiagnosticScope scope = _responsetypeClientDiagnostics.CreateScope("Samples.Get");
+﻿using global::Azure.Core.Pipeline.DiagnosticScope scope = _responsetypeClientDiagnostics.CreateScope("ResponseTypeResource.GetAsync");
```
Comment (JoshLove-msft) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Mgmt/test/Azure.Generator.Mgmt.Tests/Providers/TestData/ResourceClientProviderTests/Verify_AsyncOperationMethod.cs:1]: Why is this changing?

**Review by jorgerangel-msft — APPROVED** [review]

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Mgmt/test/Azure.Generator.Mgmt.Tests/Providers/TestData/ResourceClientProviderTests/Verify_AsyncOperationMethod.cs (hunk 6 above)
Comment (JoshLove-msft) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Mgmt/test/Azure.Generator.Mgmt.Tests/Providers/TestData/ResourceClientProviderTests/Verify_AsyncOperationMethod.cs:1]: Or I guess this is fixing a previously failing test?

Comment (live1206) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Mgmt/test/Azure.Generator.Mgmt.Tests/Providers/TestData/ResourceClientProviderTests/Verify_AsyncOperationMethod.cs:1]: yes, it is fixing previously failing tests

**Review by JoshLove-msft — APPROVED** [review]
