### PR TITLE
Fix issue with escaped json reading as string

### LINKED ISSUE #53716: [BUG] `JsonPatch.TryGetValue` throws `InvalidOperationException` when path doesn't exist, violating Try-pattern convention
**Summary:**
The `JsonPatch.TryGetValue` method throws an `InvalidOperationException` when querying a non-existent path, despite following the Try-pattern naming convention which implies the method should return `false` instead of throwing exceptions.

**Affected Component:**
- Package: `System.ClientModel`
- File: JsonPatch.Implementation.cs
- Method: `TryGetEncodedValueInternal`

**Issue Details:**
When a `JsonPatch` instance is initialized from raw JSON (via `new JsonPatch(ReadOnlyMemory<byte> utf8Json)`), the internal `_properties` field is `null`. In this state, when `TryGetValue` is called with a path that doesn't exist in the JSON, the method throws an `InvalidOperationException` instead of returning `false`.

The root cause is in the `TryGetEncodedValueInternal` method, which calls the `GetJson` extension method (lines 42, 61, 78, etc. in JsonPatch.Implementation.cs). The `GetJson` method throws an `InvalidOperationException` when the path is not found (see JsonPathExtensions.cs line 849-856):

```csharp
public static ReadOnlyMemory<byte> GetJson(this ReadOnlyMemory<byte> json, ReadOnlySpan<byte> jsonPath)
{
    if (!TryGetJson(json, jsonPath, out var target))
    {
        throw new InvalidOperationException($"{Encoding.UTF8.GetString(jsonPath.ToArray())} was not found in the JSON structure.");
    }
    return target;
}
```

This violates the Try-pattern convention where `TryXxx` methods should return a boolean indicating success/failure without throwing exceptions for expected failure cases.

**Steps to Reproduce:**

```csharp
using System.ClientModel.Primitives;
using System.Text;

// Simulate a streaming response with partial JSON data
string json = @"{""choices"":[{""delta"":{""content"":""hello""}}]}";
byte[] utf8Json = Encoding.UTF8.GetBytes(json);

JsonPatch patch = new JsonPatch(utf8Json);

// Try to get a property that doesn't exist
// Expected: returns false
// Actual: throws InvalidOperationException
bool found = patch.TryGetValue("$.reasoning"u8, out string? value);
```

**Expected Behavior:**
```csharp
bool found = patch.TryGetValue("$.reasoning"u8, out string? value);
// found should be false
// value should be null
// No exception should be thrown
```

**Actual Behavior:**
```
System.InvalidOperationException: $.reasoning was not found in the JSON structure.
   at System.ClientModel.Primitives.JsonPathExtensions.GetJson(ReadOnlyMemory`1 json, ReadOnlySpan`1 jsonPath)
   at System.ClientModel.Primitives.JsonPatch.TryGetEncodedValueInternal(ReadOnlySpan`1 jsonPath, EncodedValue& value)
   at System.ClientModel.Primitives.JsonPatch.TryGetValue(ReadOnlySpan`1 jsonPath, String& value)
```

**Impact:**
This bug affects any code using `TryGetValue` to safely check for optional properties in streaming JSON responses, particularly in the OpenAI SDK scenarios where `StreamingChatCompletionUpdate.Choices[0].Delta.Patch` is used to access optional fields like `reasoning_content`.

**Proposed Fix:**
Replace all calls to `GetJson` with `TryGetJson` in the `TryGetEncodedValueInternal` method and handle the `false` return value appropriately. Specifically, the following lines in JsonPatch.Implementation.cs need to be updated:

- Line 42: `value = new(encodedValue.Kind, encodedValue.Value.GetJson(jsonPath));`
- Line 61: `value = new(encodedValue.Kind, encodedValue.Value.GetJson(childPath));`
- Line 78: `value = new(ValueKind.Json, GetCombinedArray(jsonPath, arrayItem.GetJson(childPath), EncodedValue.Empty));`
- Line 99: `value = new(encodedValue.Kind, encodedValue.Value.GetJson(childPath));`

These should check the return value of `TryGetJson` and return `false` from `TryGetEncodedValueInternal` when the path is not found.

**Workaround:**
Users can work around this issue by using the `Contains` method before calling `TryGetValue`:

```csharp
if (patch.Contains("$.reasoning"u8) && patch.TryGetValue("$.reasoning"u8, out string? value))
{
    // Use value
}
```

Or by catching the exception:

```csharp
try
{
    if (patch.TryGetValue("$.reasoning"u8, out string? value))
    {
        // Use value
    }
}
catch (InvalidOperationException)
{
    // Path doesn't exist
}
```

**Environment:**
- SDK Version: Latest main branch (as of 2025-11-05)
- .NET Version: All supported versions
- OS: All platforms

### LINKED ISSUE #53718: [BUG] `JsonPatch.TryGetValue` does not decode JSON escape sequences in string values
**Summary:**
When retrieving string values from `JsonPatch` using `TryGetValue`, JSON escape sequences (such as `\n`, `\r`, `\t`, `\"`, `\\`) are not decoded. The method returns the literal escaped text instead of the unescaped characters.

**Affected Component:**
- Package: `System.ClientModel`
- File: JsonPatch.EncodedValue.cs
- Method: `TryDecodeValue(out string? value)` (lines 507-529)

**Issue Details:**

The `EncodedValue.TryDecodeValue(out string? value)` method simply removes the outer quotes and converts UTF-8 bytes directly to a string without processing JSON escape sequences:

```csharp
internal bool TryDecodeValue(out string? value)
{
    var span = Value.Span;

    if (s_null.Span.SequenceEqual(span))
    {
        value = null;
        return true;
    }

    if (span.Length >= 2 && span[0] == (byte)'"' && span[span.Length - 1] == (byte)'"')
    {
        // Trim the quotes
        span = span.Slice(1, span.Length - 2);
    }

    value = Encoding.UTF8.GetString(span);  // ❌ Does not decode escape sequences!
    return true;
}
```

This means escape sequences like `\n` (two bytes: backslash + 'n') are converted to the literal string `"\\n"` (backslash followed by 'n') instead of the newline character `"\n"`.

**Real-World Impact:**

This issue particularly affects streaming scenarios such as OpenAI's SSE (Server-Sent Events) responses, where the `reasoning_content` field may contain newlines and other special characters that are properly escaped in the JSON payload but incorrectly decoded by `JsonPatch`.

Example SSE event:
```
data: {"choices":[{"delta":{"reasoning":"Line 1\nLine 2\tTabbed"}}]}
```

When parsed through `JsonPatch.TryGetValue`, the string becomes:
- Actual: `"Line 1\\nLine 2\\tTabbed"` (literal backslashes)
- Expected: `"Line 1\nLine 2\tTabbed"` (actual newline and tab characters)

### Minimal Reproducible Example

```csharp
using System;
using System.ClientModel.Primitives;
using System.Text;

class Program
{
    static void Main()
    {
        // Simulate JSON data with escape sequences (as it appears in SSE/streaming responses)
        string jsonWithEscapes = @"{""message"":""Hello\nWorld\tTest""}";
        byte[] utf8Json = Encoding.UTF8.GetBytes(jsonWithEscapes);

        JsonPatch patch = new JsonPatch(utf8Json);

        // Try to get the message value
        bool found = patch.TryGetValue("$.message"u8, out string? message);

        Console.WriteLine($"Found: {found}");
        Console.WriteLine($"Value: '{message}'");
        Console.WriteLine($"Length: {message?.Length}");
        Console.WriteLine($"Contains actual newline: {message?.Contains('\n')}");
        Console.WriteLine($"Contains literal backslash-n: {message?.Contains("\\n")}");

        // Expected output:
        // Found: True
        // Value: 'Hello
        // World	Test'
        // Length: 16 (11 chars + newline + tab)
        // Contains actual newline: True
        // Contains literal backslash-n: False

        // Actual output:
        // Found: True
        // Value: 'Hello\nWorld\tTest'
        // Length: 18 (with literal backslashes)
        // Contains actual newline: False
        // Contains literal backslash-n: True
    }
}
```

### Expected Behavior

```csharp
string jsonWithEscapes = @"{""message"":""Line1\nLine2""}";
JsonPatch patch = new JsonPatch(Encoding.UTF8.GetBytes(jsonWithEscapes));

patch.TryGetValue("$.message"u8, out string? message);

// Expected: message == "Line1\nLine2" (with actual newline, length = 11)
Assert.Equal("Line1\nLine2", message);
Assert.Equal(11, message.Length);
Assert.Contains('\n', message);
```

### Actual Behavior

```csharp
string jsonWithEscapes = @"{""message"":""Line1\nLine2""}";
JsonPatch patch = new JsonPatch(Encoding.UTF8.GetBytes(jsonWithEscapes));

patch.TryGetValue("$.message"u8, out string? message);

// Actual: message == "Line1\\nLine2" (with literal backslash-n, length = 12)
Assert.Equal("Line1\\nLine2", message);  // ✓ Passes (but shouldn't)
Assert.Equal(12, message.Length);       // ✓ Passes (but shouldn't)
Assert.Contains("\\n", message);        // ✓ Passes (but shouldn't)
```

### Affected Escape Sequences

All standard JSON escape sequences are affected:
- `\n` → Newline (LF)
- `\r` → Carriage return (CR)
- `\t` → Tab
- `\"` → Double quote
- `\\` → Backslash
- `\/` → Forward slash
- `\b` → Backspace
- `\f` → Form feed
- `\uXXXX` → Unicode character

### Root Cause Analysis

The issue occurs because:

1. `TryGetJson` in JsonPathExtensions.cs (line 816-845) extracts the raw bytes from the JSON, including the escaped sequences as-is
2. `TryDecodeValue` then simply converts these bytes to a string using `Encoding.UTF8.GetString()` without processing escape sequences
3. The proper way to decode JSON strings is to use `Utf8JsonReader.GetString()`, which automatically handles all JSON escape sequences

### Proposed Fix

Modify `EncodedValue.TryDecodeValue(out string? value)` to use `Utf8JsonReader` for proper JSON string decoding:

```csharp
internal bool TryDecodeValue(out string? value)
{
    var span = Value.Span;

    if (s_null.Span.SequenceEqual(span))
    {
        value = null;
        return true;
    }

    // Check if we need to add quotes for Utf8JsonReader
    bool hasQuotes = span.Length >= 2 && span[0] == (byte)'"' && span[span.Length - 1] == (byte)'"';
    
    try
    {
        ReadOnlySpan<byte> jsonSpan;
        byte[]? rentedArray = null;
        
        if (!hasQuotes)
        {
            // Need to add quotes for valid JSON string parsing
            int newLength = span.Length + 2;
            rentedArray = newLength <= 256 
                ? null 
                : ArrayPool<byte>.Shared.Rent(newLength);
            
            Span<byte> buffer = rentedArray != null 
                ? rentedArray.AsSpan(0, newLength)
                : stackalloc byte[newLength];
            
            buffer[0] = (byte)'"';
            span.CopyTo(buffer.Slice(1));
            buffer[buffer.Length - 1] = (byte)'"';
            jsonSpan = buffer;
        }
        else
        {
            jsonSpan = span;
        }

        var reader = new Utf8JsonReader(jsonSpan);
        if (reader.Read() && reader.TokenType == JsonTokenType.String)
        {
            value = reader.GetString();
            return true;
        }

        if (rentedArray != null)
        {
            ArrayPool<byte>.Shared.Return(rentedArray);
        }
    }
    catch
    {
        // Fall through to legacy behavior
    }

    // Fallback: legacy behavior for non-string JSON values
    if (hasQuotes)
    {
        span = span.Slice(1, span.Length - 2);
    }
    
#if NET6_0_OR_GREATER
    value = Encoding.UTF8.GetString(span);
#else
    value = Encoding.UTF8.GetString(span.ToArray());
#endif
    return true;
}
```

### Workaround

Until this is fixed, users can manually decode escape sequences:

**Option 1: Manual replacement**
```csharp
string? GetDecodedValue(JsonPatch patch, ReadOnlySpan<byte> path)
{
    if (patch.TryGetValue(path, out string? val) && val != null)
    {
        return val
            .Replace("\\n", "\n")
            .Replace("\\r", "\r")
            .Replace("\\t", "\t")
            .Replace("\\\"", "\"")
            .Replace("\\\\", "\\");  // Must be last
    }
    return null;
}
```

**Option 2: Using JsonSerializer**
```csharp
string? GetDecodedValue(JsonPatch patch, ReadOnlySpan<byte> path)
{
    if (patch.TryGetValue(path, out string? val) && val != null)
    {
        string jsonString = $"\"{val}\"";
        try
        {
            return System.Text.Json.JsonSerializer.Deserialize<string>(jsonString);
        }
        catch
        {
            return val;
        }
    }
    return null;
}
```

### Environment
- SDK Version: Latest main branch (as of 2025-11-06)
- .NET Version: All supported versions (.NET 6.0+, .NET Framework 4.6.2+)
- OS: All platforms

### Additional Notes

This issue is separate from but related to issue #[previous issue number] regarding `TryGetValue` throwing exceptions. Both issues affect the reliability of `JsonPatch` when used with streaming JSON data.

### PR DESCRIPTION
**Pull request by m-nash**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/53718
Fixes https://github.com/Azure/azure-sdk-for-net/issues/53716

### CODE REVIEW

File: sdk/core/System.ClientModel/src/ModelReaderWriter/JsonPatch.EncodedValue.cs [hunk 1]
```diff
@@ -616,31 +629,40 @@ internal bool TryDecodeNullableValue<T>(out T? value, out bool supportedType)
...
                 return parsed;
             }
 
             supportedType = false;
             return false;
         }
+
+        private static ReadOnlySpan<byte> UnWrapQuotes(ReadOnlySpan<byte> span)
+        {
+            if (span.Length >= 2 && span[0] == (byte)'"' && span[span.Length - 1] == (byte)'"')
```
Comment (jsquire) [inline sdk/core/System.ClientModel/src/ModelReaderWriter/JsonPatch.EncodedValue.cs:661]: Was going to suggest a `static readonly` to elide the cast, but I believe that would trigger boxing, so not a good idea.   Right?

**Review by jsquire — APPROVED** [review]
