### PR TITLE
fix the culture info issue in `LocationMetadata`

### LINKED ISSUE #43116: [BUG] SubscriptionResource.GetLocationsAsync fails with System.FormatException
### Library name and version

Azure.ResourceManager 1.11.0

### Describe the bug

I'm trying to query Azure for the list of locations to work around another bug and I'm getting an error.

### Expected behavior

Return a list of deserialized Azure.ResourceManager.Resources.Models.LocationExpanded

### Actual behavior

`System.FormatException: The input string '-79.8164' was not in a correct format.`
```
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Double.Parse(String s)
   at Azure.ResourceManager.Resources.Models.LocationMetadata.ReadLongitude(JsonProperty property, Nullable`1& longitude)
   at Azure.ResourceManager.Resources.Models.LocationMetadata.DeserializeLocationMetadata(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.Resources.Models.LocationExpanded.DeserializeLocationExpanded(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.Resources.SubscriptionResource.<>c.<GetLocationsAsync>b__47_1(JsonElement e)
   at Azure.Core.PageableHelpers.PageableImplementation`1.<GetAsyncEnumerator>d__15.MoveNext()
   at Azure.Core.PageableHelpers.PageableImplementation`1.<GetAsyncEnumerator>d__15.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
```

### Reproduction Steps

```csharp
var armClient = new ArmClient(new DefaultAzureCredential());
SubscriptionResource subscription = _armClient.GetSubscriptionResource("xxxxxxxxxxxxxxxxxxxxx");
var response = subscription.GetLocationsAsync();
var result = await response.ToListAsync(); // <- System.FormatException: 'The input string '-79.8164' was not in a correct format.
```

### Environment

- dotnet 8
- VS 17.9.5

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/43116

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by m-nash — APPROVED** [review]

File: sdk/resourcemanager/Azure.ResourceManager/src/Resources/Custom/Models/LocationMetadata.cs [hunk 1]
```diff
@@ -32,14 +39,20 @@ internal static void ReadLongitude(JsonProperty property, ref double? longitude)
             if (property.Value.ValueKind == JsonValueKind.Null)
                 return;
 
-            longitude = double.Parse(property.Value.GetString());
+            longitude = double.Parse(property.Value.GetString(), CultureInfo.InvariantCulture);
```
Comment (ArthurMa1978) [inline sdk/resourcemanager/Azure.ResourceManager/src/Resources/Custom/Models/LocationMetadata.cs:42]: Please file an issue to track all kind of Parse.

**Review by ArthurMa1978 — APPROVED** [review]

**Comment by ArcturusZhang** [comment]
The version mismatch happens in Azure.Communication.Identity project.

I would like to ignore that failure and merge this PR for several reasons:
1. this change has no impact on that library at all.
2. this change does not change anything there.
3. this error is happening in a "project reference" scenario, and `Azure.Identity` library has an unreleased version or an unstable version which uses the `VersionOverride` to override the global version of `Microsoft.Identity.Client`. This is the root cause of this failure. https://github.com/Azure/azure-sdk-for-net/blob/381c6430a0a268de0abd363f6b3b8f14293efed3/sdk/identity/Azure.Identity/src/Azure.Identity.csproj#L24

I hope the above version override would be temporary.

File: sdk/resourcemanager/Azure.ResourceManager/CHANGELOG.md [hunk 2]
```diff
@@ -8,6 +8,8 @@
 
 ### Bugs Fixed
 
+- Fixed the `Longitude` and `Latitude` in `LocationMetadata` class to use invariant culture during serialization and deserialization. (https://github.com/Azure/azure-sdk-for-net/issues/43116)
```
Comment (ArthurMa1978) [inline sdk/resourcemanager/Azure.ResourceManager/CHANGELOG.md:11]: Release a 1.14.1 package

Comment (ArcturusZhang) [reply sdk/resourcemanager/Azure.ResourceManager/CHANGELOG.md:7]: done and it should be 1.13.1

**Review by ArthurMa1978 — APPROVED** [review]
