### PR TITLE
[Mgmt CodeGen] Fix: Expand Legacy.RoutedOperations with dynamic parent types into concrete resources

### LINKED ISSUE #58137: [Mgmt CodeGen] Resources using Legacy.RoutedOperations with dynamic parent types are not generated as Resource/Collection/Data classes
## Problem

The MPG TypeSpec codegen (`@azure-typespec/http-client-csharp-mgmt`) does **NOT** generate Resource, Collection, and Data classes for resources that use the `Legacy.RoutedOperations` pattern with **dynamic/parameterized parent types** in their URL paths.

Three resources in **EventGrid** are affected:

1. **NetworkSecurityPerimeterConfiguration** — path uses `{resourceType}/{resourceName}` as dynamic parent
2. **PrivateEndpointConnection** — path uses `{parentType}/{parentName}` as dynamic parent
3. **PrivateLinkResource** — path uses `{parentType}/{parentName}` as dynamic parent + uses `@customAzureResource`

### Expected (Old AutoRest SDK on main branch)

Each resource had **separate Resource/Collection/Data classes per parent type**:

| Resource | Generated Classes (main branch) |
|---|---|
| **PrivateEndpointConnection** | `EventGridDomainPrivateEndpointConnectionResource`, `EventGridTopicPrivateEndpointConnectionResource`, `EventGridPartnerNamespacePrivateEndpointConnectionResource` + corresponding Collections + shared `EventGridPrivateEndpointConnectionData` |
| **PrivateLinkResource** | `EventGridDomainPrivateLinkResource`, `EventGridTopicPrivateLinkResource`, `PartnerNamespacePrivateLinkResource` + corresponding Collections + shared `EventGridPrivateLinkResourceData` |
| **NetworkSecurityPerimeter** | `DomainNetworkSecurityPerimeterConfigurationResource`, `TopicNetworkSecurityPerimeterConfigurationResource` + corresponding Collections + shared `NetworkSecurityPerimeterConfigurationData` |

### Actual (New TypeSpec codegen)

**No** Resource, Collection, or Data classes are generated. Instead, operations are emitted as plain methods on `MockableEventGridResourceGroupResource`:

```csharp
// Operations are on MockableEventGridResourceGroupResource instead of proper Resource classes
public virtual async Task<Response<EventGridPrivateEndpointConnection>> GetAsync(
    PrivateEndpointConnectionsParentType parentType, string parentName, 
    string privateEndpointConnectionName, CancellationToken cancellationToken = default)
```

---

### 1. Resources NOT in `@armProviderSchema`

The `@armProviderSchema` decorator on the root client lists **27 resources**, but **none** of the three affected resources are included:

```
0: Microsoft.EventGrid.CaCertificate
1: Microsoft.EventGrid.Namespace
2: Microsoft.EventGrid.Channel
...
26: Microsoft.EventGrid.TopicTypeInfo
```

Missing:
- ❌ `NetworkSecurityPerimeterConfiguration`
- ❌ `PrivateEndpointConnection`
- ❌ `PrivateLinkResource`

The codegen generates Resource classes **only** for resources listed in `@armProviderSchema` ([ManagementInputLibrary.cs BuildArmProviderSchema()](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/ManagementInputLibrary.cs#L209-L256)). Since these three are not listed, no Resource classes are generated.

### 2. Why are they missing from `@armProviderSchema`?

These resources use `Azure.ResourceManager.Legacy.RoutedOperations` with hardcoded full route paths and dynamic parent type parameters:

**PrivateEndpointConnection.tsp:**
```typespec
@armResourceOperations
interface PrivateEndpointConnectionOps
  extends Azure.ResourceManager.Legacy.RoutedOperations<
      {
        ...ApiVersionParameter,
        ...SubscriptionIdParameter,
        ...ResourceGroupParameter,
        @path parentType: PrivateEndpointConnectionsParentType,
        @path parentName: string,
      },
      {},
      ResourceRoute = #{
        route: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/microsoft.EventGrid/{parentType}/{parentName}",
      }
    > {}

@armResourceOperations(#{ allowStaticRoutes: true })
interface PrivateEndpointConnections {
  @get
  @route("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/microsoft.EventGrid/{parentType}/{parentName}/privateEndpointConnections/{privateEndpointConnectionName}")
  get is PrivateEndpointConnectionOps.ActionSync<...>;
  // ...
}
```

**NetworkSecurityPerimeterConfiguration.tsp:**
```typespec
@armResourceOperations
interface NetworkSecurityPerimeterConfigurationOps
  extends Azure.ResourceManager.Legacy.RoutedOperations<
      {
        ...ApiVersionParameter,
        ...SubscriptionIdParameter,
        ...ResourceGroupParameter,
        @path resourceType: NetworkSecurityPerimeterResourceType,
        @path resourceName: string,
      },
      {},
      ResourceRoute = #{
        route: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/microsoft.EventGrid/{resourceType}/{resourceName}",
      }
    > {}
```

**PrivateLinkResource.tsp:**
```typespec
@Azure.ResourceManager.Legacy.customAzureResource
model PrivateLinkResource {
  properties?: PrivateLinkResourceProperties;
  id?: armResourceIdentifier;
  name?: string;
  type?: armResourceType;
}

@armResourceOperations
interface PrivateLinkResourceOps
  extends Azure.ResourceManager.Legacy.RoutedOperations<
      {
        @path parentType: PrivateLinkResourcesParentType,
        @path parentName: string,
      },
      {},
      ResourceRoute = #{
        route: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/microsoft.EventGrid/{parentType}/{parentName}",
      }
    > {}
```

The pattern is: the TypeSpec compiler's ARM library does not recognize these `Legacy.RoutedOperations` with dynamic parent segments as proper ARM resources, so they are not included in the `@armProviderSchema` output. The codegen then treats them as standalone operations on extension methods rather than building proper Resource hierarchies.

### 3. Swagger definitions use parameterized paths

In the swagger (`EventGrid.json`), these operations use parameterized parent type segments:

```json
"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.EventGrid/{parentType}/{parentName}/privateEndpointConnections/{privateEndpointConnectionName}": {
    "get": { "operationId": "PrivateEndpointConnections_Get" },
    "put": { "operationId": "PrivateEndpointConnections_Update", "x-ms-long-running-operation": true },
    "delete": { "operationId": "PrivateEndpointConnections_Delete", "x-ms-long-running-operation": true }
}
```

The old AutoRest codegen handled this by expanding `{parentType}` into concrete parent types and generating separate Resource classes per parent. The new TypeSpec codegen does not support this pattern.

---

## Impact

This is a **significant breaking change** for SDK consumers migrating from the AutoRest-generated SDK:

1. **No Resource lifecycle management** — Users cannot use standard ARM resource patterns (`Get`, `CreateOrUpdate`, `Delete` on typed resource objects)
2. **No Collection pattern** — Users cannot enumerate resources using typed collections
3. **No Data classes** — Resources are returned as plain model types (`EventGridPrivateEndpointConnection`) instead of proper resource data types with ARM metadata
4. **Breaking API surface** — All existing code using `EventGridDomainPrivateEndpointConnectionResource`, `EventGridTopicPrivateLinkResource`, etc. will break

---

## Suggested Fix

The codegen (or TypeSpec ARM library) needs to handle the `Legacy.RoutedOperations` pattern with dynamic parent types by:

1. **Recognizing** these resources as ARM resources in `@armProviderSchema`
2. **Expanding** dynamic parent types into concrete parent-specific resources (e.g., `{parentType}` → `topics`, `domains`, `partnerNamespaces`, `namespaces`)
3. **Generating** separate Resource/Collection classes per concrete parent type, with a shared Data class

---

## Generator Version

- `@azure-typespec/http-client-csharp-mgmt@1.0.0-alpha.20260407.1`
- TypeSpec Compiler: `1.10.0`

### PR DESCRIPTION
**Pull request by live1206**
## Fix: Expand Legacy.RoutedOperations with dynamic parent types into concrete resources

Fixes #58137

### Problem

Resources using `Legacy.RoutedOperations` with dynamic/parameterized parent types (e.g., `{parentType}/{parentName}` in URL paths) were NOT generated as Resource/Collection/Data classes. Instead, their operations ended up as plain methods on mockable extension resources.

Three resources in EventGrid are affected:
- **PrivateEndpointConnection** — `{parentType}` enum: topics, domains, partnerNamespaces
- **PrivateLinkResource** — same pattern + uses `@customAzureResource`
- **NetworkSecurityPerimeterConfiguration** — `{resourceType}` enum: topics, domains

### Root Causes

1. **Incorrect operation classification**: `RoutedOperations` only provides `ActionSync`/`ActionAsync` templates (no Read/Get template). Services use `ActionSync` with HTTP verb overrides (`@get`, `@put`, `@delete`), but the decorator still says `@legacyResourceOperation(Resource, "action")`. The emitter classified ALL operations as Action instead of Read/Create/Delete.

2. **Dynamic parent types need expansion**: Paths like `.../{parentType}/{parentName}/privateEndpointConnections/{name}` need expansion into concrete resources per enum value (e.g., topics, domains).

#### Emitter (`resource-detection.ts`, `resolve-arm-resources-converter.ts`, `resource-metadata.ts`)

- **Operation reclassification**: Tightened the legacy "action" classification so it inspects the actual HTTP verb and method shape:
  - GET + pageable + resource-list response → List
  - GET → Read
  - PUT → Create
  - PATCH → Update
  - DELETE → Delete
  - POST (and any case where the response shape doesn't match a CRUD operation) → Action (unchanged)

- **Dynamic parent expansion** (`expandArmResources` / `expandDynamicParentResourcesInSchema`): Detects enum-typed path parameters at type-position slots after `/providers/`, and fans the resource out into one concrete entry per enum value. Each expanded resource gets a substituted `resourceIdPattern`, substituted per-method `operationPath`, derived name, and shared model id. Both detection paths run this expansion as their first step before any parent-lookup or post-processing.

- **Parent-lookup contexts** (`buildLegacyParentLookup` / `buildResolveArmResourcesParentLookup`): Each detection path supplies its own `ParentResourceLookupContext` and shares the post-expansion resource list with `postProcessArmResources`. The legacy path keys parents by `resourceModelId` (`@parentResourceModelId` decorator + path-based inference for shared-model siblings); the resolve path keys parents by `resourceInstancePath` (the ARM library's resolved parent chain) and walks up the chain to the nearest known ancestor.

- **Shared disambiguator** (`isResourceIdPatternPrefixMatch`): When a parent itself was expanded (rare nested case) and multiple candidates share the primary lookup key, both paths pick the candidate whose substituted `resourceIdPattern.path` is a prefix of the resource's. The helper lives in `resource-metadata.ts` and is used by both lookups.

#### Generator (`OperationContext.cs`)

- **No new metadata field**: Constant path parameter values are derived on the fly from each resource's `ContextualPath` (i.e., the substituted `resourceIdPattern` produced by the emitter). No `ConstantPathParameters` map is plumbed across the emitter→generator boundary.

- **`BuildParameterMapping` → `SubstituteConstantsFromContextualPath`**: Walks the operation path against `ContextualPath` segment by segment. Whenever the operation segment is a variable and the contextual segment at the same index is a constant, the operation segment is replaced with the literal value and a constant `ParameterContextMapping` is emitted for the original variable name. This mirrors `RequestPath.ApplyHint` from `autorest.csharp`, which:
  - **Hides** the dynamic-parent param from method signatures (existing `OperationMethodParameterHelper` skips contextual params)
  - **Injects** the literal value into REST calls (existing `PopulateArguments` handles contextual expressions)

- No call-site changes are required in `ResourceClientProvider` / `ResourceCollectionClientProvider` beyond dropping the now-unused dictionary argument from `OperationContext.Create`.

#### Tests

- New emitter test verifying RoutedOperations + dynamic parent type enum produces expanded concrete resources with correct types, names, methods, and substituted `resourceIdPattern`.
- New generator tests for `OperationContext.BuildParameterMapping` covering contextual-constant substitution, multi-constant cases, the no-substitution baseline, and the secondary-path overload.
- New `Mgmt-TypeSpec/routedoperations.tsp` scenario in the local test project so end-to-end regen exercises expansion + constant substitution.

### Test Results

- 122/122 emitter tests pass
- 165/165 generator tests pass
- `Generate.ps1` produces zero regen diff in `TestProjects` C# code
- Lint + Prettier pass

### CODE REVIEW

**Review by live1206 — COMMENTED** [review]
Reviewed specifically for root-cause vs. workaround. This looks like a real fix for the current default management generation path, not a service-specific workaround: it corrects Legacy.RoutedOperations classification based on the actual HTTP verb, expands enum-backed dynamic parent type segments into concrete resource metadata, and plumbs those constants through the generator so the generated API shape is correct.

I did not find versioning or ApiCompat issues in this PR, and the relevant emitter/generator validation is green.

One caveat to keep in mind for the longer-term migration: this fixes the active legacy resource-detection path. If/when `use-legacy-resource-detection` flips to `false`, the standardized `resolveArmResources` path will need equivalent support so this scenario stays fixed there as well.

**Review by live1206 — COMMENTED** [review]
Reviewed the management generator changes and regenerated Mgmt-TypeSpec outputs. I found one cleanup issue: a TypeScript incremental build artifact is checked in. No SDK migration customization/versioning findings apply to this generator-focused PR.

File: eng/packages/http-client-csharp-mgmt/emitter/tsconfig.tsbuildinfo [hunk 1]
```diff
@@ -0,0 +1 @@
... is not assignable to type 'ResourceMethod'."}}]}]}]}},{"start":8395,"length":7,"code":2345,"category":1,"messageText":{"messageText":"Argument of type '{ methodId: string; kind: ResourceOperationKind; operationPath: string; scope: { kind: ResourceScopeKind; }; }[]' is not assignable to parameter of type 'ResourceMethod[]'.","category":1,"code":2345,"next":[{"messageText":"Type '{ methodId: string; kind: ResourceOperationKind; operationPath: string; scope: { kind: ResourceScopeKind; }; }' is not assignable to type 'ResourceMethod'.","category":1,"code":2322,"next":[{"messageText":"Types of property 'operationPath' are incompatible.","category":1,"code":2326,"next":[{"messageText":"Type 'string' is not assignable to type 'RequestPath'.","category":1,"code":2322,"canonicalHead":{"code":2322,"messageText":"Type '{ methodId: string; kind: ResourceOperationKind; operationPath: string; scope: { kind: ResourceScopeKind; }; }' is not assignable to type 'ResourceMethod'."}}]}]}]}}]]],"affectedFilesPendingEmit":[458,482,484,483,479,478,480,465,457,463,481,570,593,594,595,596,592,599],"emitSignatures":[457,458,463,465,478,479,480,481,482,483,484,570,592,593,594,595,596,599],"version":"5.8.3"}
```
Comment (live1206) [inline eng/packages/http-client-csharp-mgmt/emitter/tsconfig.tsbuildinfo]: **[artifact]** This looks like a local TypeScript incremental build cache, not source or generated test output. mitter/tsconfig.build.json already points 	sBuildInfoFile at 	emp/tsconfig.tsbuildinfo, and the repo ignores 	emp/, so please remove this checked-in 	sconfig.tsbuildinfo file from the PR.

File: eng/packages/http-client-csharp-mgmt/emitter/src/resource-metadata.ts [hunk 2]
```diff
@@ -1092,3 +1104,223 @@ function relocateCrossResourceListActions(
...
+    )?.operationPath
+  );
+}
+
+function buildExpandedResourceName(
+  enumValue: string,
+  baseResourceName: string
+): string {
+  const singular = pluralize.singular(enumValue);
+  const capitalized = singular.charAt(0).toUpperCase() + singular.slice(1);
```
Comment (live1206) [inline eng/packages/http-client-csharp-mgmt/emitter/src/resource-metadata.ts]: is there any common method we can use to capitalize a word?

Comment (live1206) [reply eng/packages/http-client-csharp-mgmt/emitter/src/resource-metadata.ts]: Looked around for a shared helper:

- The emitter package itself doesn't expose a `capitalize`/`pascalCase` utility, and there's no existing usage of one in `eng/packages/http-client-csharp-mgmt/emitter/src`.
- `@typespec/compiler` does have an internal `capitalize(s)` in `src/casing/index.ts`, but it's not part of its public exports, so we shouldn't import it.
- `change-case` (with `pascalCase`/`capitalCase`) is the de-facto utility used by `@azure-tools/typespec-client-generator-core`, but it's only transitively available — would need to be added as a direct devDependency/dependency of this emitter package to use it safely.

A couple of caveats if we switch to `change-case.pascalCase`: the current inline code only upper-cases the first character and leaves the rest as-is (e.g. `IPAddress` → `IPAddress`), whereas `pascalCase` would normalize the whole token (`IPAddress` → `IpAddress`) and split on internal separators. Given the input here is a single singularized enum value used to prefix a resource name, the current one-liner is intentionally conservative.

Options:
1. Keep the inline `charAt(0).toUpperCase() + slice(1)` (smallest change, preserves casing of the rest of the token).
2. Extract a tiny local helper `capitalizeFirst(s)` in a shared `utils.ts` if we expect to reuse it.
3. Add `change-case` as a direct dependency and use `pascalCase` — only if we're OK with the casing-normalization behavior.

My preference would be (2) — a one-line local helper — unless we're also planning to start using `change-case` more broadly in this emitter.

**Comment by live1206** [comment]
SDK Regen PR: https://github.com/Azure/azure-sdk-for-net/pull/58789

File: eng/packages/http-client-csharp-mgmt/emitter/src/resolve-arm-resources-converter.ts [hunk 3]
```diff
@@ -197,50 +199,113 @@ export function resolveArmResources(
...
+  for (const client of getAllSdkClients(sdkContext)) {
+    for (const method of client.methods) {
+      if (!serviceMethodsMap.has(method.crossLanguageDefinitionId)) {
+        serviceMethodsMap.set(
+          method.crossLanguageDefinitionId,
+          method as SdkMethod<SdkHttpOperation>
+        );
+      }
+    }
+  }
```
Comment (ArcturusZhang) [inline eng/packages/http-client-csharp-mgmt/emitter/src/resolve-arm-resources-converter.ts]: we have quite a few maps, all using crosslanguagedefinitionid as keys. could we combine all of them into one?
I think the other maps can be replaced by this.

Comment (ArcturusZhang) [reply eng/packages/http-client-csharp-mgmt/emitter/src/resolve-arm-resources-converter.ts]: also instead of silently ignoring duplicated methods, we should report a diagnostic for duplicated ids.

File: eng/packages/http-client-csharp-mgmt/emitter/src/resolve-arm-resources-converter.ts [hunk 4]
```diff
@@ -197,50 +199,113 @@ export function resolveArmResources(
...
+          return true;
+        }
+
+        const resourceConstants = resource.metadata.constantPathParameters ?? {};
+        return Object.entries(candidateConstants).every(
+          ([name, value]) => resourceConstants[name] === value
         );
-        if (parentResource) {
-          return parentResource;
+      };
```
Comment (ArcturusZhang) [inline eng/packages/http-client-csharp-mgmt/emitter/src/resolve-arm-resources-converter.ts]: we should not use this style to define methods.
please align the style here.

File: eng/packages/http-client-csharp-mgmt/emitter/src/resolve-arm-resources-converter.ts [hunk 5]
```diff
@@ -197,50 +199,113 @@ export function resolveArmResources(
...
-    }
-  }
+  // Use the shared post-processing function. Dynamic-parent expansion happens
+  // first inside postProcessArmResources, then the builder below mirrors
+  // schema-to-resolved-resource entries for the expanded children and produces
+  // the parent-lookup context based on resolveArmResources' parent chain.
+  const { filteredResources } = postProcessArmResources(
+    resources,
+    nonResourceMethods,
+    (expanded, expandedToOriginal) => {
```
Comment (ArcturusZhang) [inline eng/packages/http-client-csharp-mgmt/emitter/src/resolve-arm-resources-converter.ts]: this is a method invocation from line 227 to line 309 with huge call back?
this is impossible to understand.
please refactor this to find a more understandable way

File: eng/packages/http-client-csharp-mgmt/emitter/src/resolve-arm-resources-converter.ts [hunk 6]
```diff
@@ -197,50 +199,113 @@ export function resolveArmResources(
...
+                parentResources.find((candidate) =>
+                  hasMatchingConstantPathParameters(resource, candidate)
+                ) ?? parentResources[0]
+              );
+            }
+            parent = parent.parent;
+          }
+          return undefined;
+        }
+      };
```
Comment (ArcturusZhang) [inline eng/packages/http-client-csharp-mgmt/emitter/src/resolve-arm-resources-converter.ts]: I do not know why it is necessary that the logic of "how to get parent resource from the current resource" should be configurable.

File: eng/packages/http-client-csharp-mgmt/emitter/src/resource-detection.ts [hunk 7]
```diff
@@ -952,6 +988,66 @@ function isPagingActionListingResources(
...
+ * - PUT + matching resource payload/response → Create
+ * - PATCH + matching resource payload/response → Update
+ * - DELETE + resource/void response → Delete
+ * - POST, mismatched CRUD verb, or unknown → Action (unchanged)
+ */
+function reclassifyLegacyAction(
+  serviceMethod: SdkMethod<SdkHttpOperation> | undefined,
+  resourceModelId?: string,
+  resourceModelIds?: Set<string>
+): ResourceOperationKind {
```
Comment (ArcturusZhang) [inline eng/packages/http-client-csharp-mgmt/emitter/src/resource-detection.ts:962]: Emm why is this needed?
the kind should not be linked with the verb.

File: eng/packages/http-client-csharp-mgmt/emitter/src/resolve-arm-resources-converter.ts (hunk 6 above)
Comment (live1206) [reply eng/packages/http-client-csharp-mgmt/emitter/src/resolve-arm-resources-converter.ts]: The two detection paths derive parents through fundamentally different mechanisms, so the lookup has to be plugged in per path:

- The legacy `buildArmProviderSchema` path infers parents from path-prefix matching plus the `@parentResourceModelId` decorator.
- The `resolveArmResources` path walks the `ResolvedResource.parent` chain returned by the ARM library.

`postProcessArmResources` runs dynamic-parent expansion before the lookup is needed (the expanded children don't exist in either source map yet), and the two callers also need to do path-specific bookkeeping at that exact moment — e.g., the resolve-arm-resources path mirrors `schemaToResolvedResource` entries for the freshly-expanded schemas. Folding this into `postProcessArmResources` would require it to know about both detection mechanisms, which would be a much bigger coupling than the current callback. Happy to revisit if you see a way to unify them without losing information.

File: eng/packages/http-client-csharp-mgmt/emitter/src/resource-detection.ts (hunk 7 above)
Comment (live1206) [reply eng/packages/http-client-csharp-mgmt/emitter/src/resource-detection.ts:962]: Good question — the `kind` is normally orthogonal to the verb, but this branch is specifically scoped to `legacyResourceOperation(Resource, "action")` from `Legacy.RoutedOperations`, where the `"action"` literal is a template artifact rather than authored intent.

`Legacy.RoutedOperations` only ships `ActionSync` / `ActionAsync` — there is no `Read` / `Create` / `Update` / `Delete` legacy template. Both templates hard-code `@legacyResourceOperation(Resource, "action")`, so when a service needs true CRUD on a child resource exposed via dynamic parent types (the scenario this PR enables), they have to use `ActionSync` and override the HTTP verb with `@get` / `@put` / `@patch` / `@delete`. The verb + body/response shape are the only signals left to recover the real kind.

If we drop `reclassifyLegacyAction`:

1. **All CRUD methods on dynamic-parent resources collapse to `Action`.** The new test `RoutedOperations with dynamic parent type expands into concrete resources` models `get`/`update`/`delete` as `ActionSync`/`ActionAsync` with verb overrides, and asserts `hasRead`/`hasCreate`/`hasDelete` (resource-detection.test.ts:4173-4178). Those assertions would fail.
2. **The expanded resources get filtered out entirely.** `postProcessArmResources` drops non-singleton resources without a `Read` method (resource-metadata.ts:880-884), so the dynamic-parent expansion this PR adds would be downstream-invisible.
3. **The generated C# SDK loses the resource client lifecycle surface** — the operations would only appear as action methods on the collection client, not as `Get` / `CreateOrUpdate` / `Delete` on the resource client.

Over-promotion is guarded: reclassification only fires when the body/response matches the resource model. That is verified by `GET legacy action returning non-resource model stays Action` (line 2483) and `PUT/PATCH/DELETE legacy actions with non-resource types stay Action` (line 2547).

Happy to add a comment on the function clarifying this narrow scope, or rename it to something like `inferKindFromVerbForLegacyAction` if you think the current name oversells what it does.

File: eng/packages/http-client-csharp-mgmt/emitter/src/resolve-arm-resources-converter.ts (hunk 6 above)
Comment (live1206) [reply eng/packages/http-client-csharp-mgmt/emitter/src/resolve-arm-resources-converter.ts]: Good call — pushed `d44208cfbf7` that removes the callback shape entirely. The API is now two named steps and each call site reads top-to-bottom:

```ts
const { expandedResources, expandedToOriginal } = expandArmResources(resources, { serviceMethods, diagnosticReporter });
const parentLookup = buildXxxParentLookup(expandedResources, expandedToOriginal, ...);
const filteredResources = postProcessArmResources(expandedResources, nonResourceMethods, parentLookup, { methodResponseModelIdMap });
```

Changes:
- `expandArmResources(resources, options)` is the new exported step that returns `{ expandedResources, expandedToOriginal }`.
- `postProcessArmResources` now takes a fully-built `ParentResourceLookupContext` directly and returns just the filtered list — no callback, no `PostProcessArmResourcesResult`.
- The legacy detection callback was split into three named helpers in `resource-detection.ts`: `inferLegacyParentsFromPaths`, `assignLegacyResourceScopes`, `buildLegacyParentLookup`.
- `buildResolveArmResourcesParentLookup` is now a plain function that takes the post-expansion list + `expandedToOriginal` directly.

Build, lint, prettier, and 122/122 tests pass.

File: eng/packages/http-client-csharp-mgmt/emitter/src/resolve-arm-resources-converter.ts [hunk 8]
```diff
@@ -715,3 +695,140 @@ function assignListOperationsToResources(
...
+ */
+function deriveMethodApiVersionsMap(
+  methodMap: ReadonlyMap<string, SdkMethod<SdkHttpOperation>>
+): Map<string, string[]> {
+  const result = new Map<string, string[]>();
+  for (const [id, method] of methodMap) {
+    result.set(id, method.apiVersions);
+  }
+  return result;
+}
```
Comment (ArcturusZhang) [inline eng/packages/http-client-csharp-mgmt/emitter/src/resolve-arm-resources-converter.ts]: do we really need this map?
I think wherever we are using this map, we could always use
```
methodsDict.get(id).apiVersions
```
instead.

Comment (live1206) [reply eng/packages/http-client-csharp-mgmt/emitter/src/resolve-arm-resources-converter.ts]: Yep, good simplification. Pushed `0e83645c219`:

- Changed `resolveResourceApiVersions` to take `Map<string, SdkMethod<SdkHttpOperation>>` directly and look up `apiVersions` inline.
- Deleted the `deriveMethodApiVersionsMap` helper and the parallel `methodApiVersionsMap` that resource-detection.ts was also building.

Net change is `4 files changed, 22 insertions(+), 41 deletions(-)`. Build, lint, prettier, 122/122 tests all pass.

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Models/OperationContexts/OperationContext.cs [hunk 9]
```diff
@@ -299,21 +308,70 @@ static List<ContextualParameter> BuildSecondaryContextualParametersCore(RequestP
...
     {
+        // If there are constant path parameters, substitute them in the operation path
+        // so that segment matching works correctly between the contextual and operation paths.
+        var (effectiveOperationPath, constantMappings) = ConstantPathParameters is { Count: > 0 }
+            ? SubstituteConstantParameters(operationPath, ConstantPathParameters)
+            : (operationPath, (IReadOnlyList<ParameterContextMapping>)Array.Empty<ParameterContextMapping>());
+
         // we need to find the sharing part between contextual path and the incoming path
-        var sharedSegmentsCount = RequestPathPattern.GetMaximumSharingSegmentsCount(ContextualPath, operationPath);
+        var sharedSegmentsCount = RequestPathPattern.GetMaximumSharingSegmentsCount(ContextualPath, effectiveOperationPath);
```
Comment (ArcturusZhang) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Models/OperationContexts/OperationContext.cs]: if we do this in the emitter, could we avoid introducing the   ConstantPathParameters map?
I kind of remember in our old generator, we do not have this map.

Comment (live1206) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Models/OperationContexts/OperationContext.cs]: Good catch — done in d4a39e6.

Dropped the `ConstantPathParameters` map from both layers and ported autorest.csharp's `RequestPath.ApplyHint` algorithm into the generator: `BuildParameterMapping` now walks the operation path against `ContextualPath` and substitutes any operation variable whose corresponding contextual segment is a constant. The same information was already encoded in the substituted `resourceIdPattern` / `ContextualPath` produced by the emitter during dynamic-parent-type expansion, so the map was redundant.

Result:
- Emitter `ArmResourceMetadata` schema and `tspCodeModel.json` no longer carry `constantPathParameters`.
- Generator `OperationContext` no longer has the property or the `Create` overload parameter.
- The parent disambiguation in `resolve-arm-resources-converter.ts` now compares `resourceIdPattern.path` directly instead of the map.
- Zero diff in the generated C# of the test projects after `Generate.ps1`; the only diff is `tspCodeModel.json` shrinking. All 122 emitter tests + 165 generator tests still pass.

**Review by ArcturusZhang — APPROVED** [review]
