### PR TITLE
ClientModel: Move buffering into the transport

### LINKED ISSUE #41080: ClientModel: Change approach to buffering response.Content
### Problem Description

The APIs we have today in Azure.Core around Response.Content and Response.ContentStream and buffering are not transparent.  It is not clear to the end-user which responses are buffered and which are not.  The only way for users to discover this is to read the docs for a service method.

### High-level proposal

Make a change to the current implementation of the PipelineResponse.Content property such that we no longer throw if the response has not been buffered (i.e. PipelineMessage.BufferResponse has been set to false by the client-author).  This means that end-users can _always_ access PipelineResponse.Content and if it is not buffered, it will buffer the response in the response.Content field.  In the rare situation where response.Content is larger than what we can fit in memory, the user will either get an IOException or -- since we will have wrapped the live network stream in a ReadTimeoutStream -- the buffering will throw a TaskCanceledException due to the network timeout being applied.

### Implementation proposal

(From @KrzysztofCwalina and under investigation per feasibility in https://github.com/Azure/azure-sdk-for-net/pull/41693 and related PRs)

> Could we do the following?
>  
> In the case of unbuffered responses:
> 1.	Service method creates, composes, and sends an instance of HttpMessage.
> 2.	The transport stashed HttpRequestMessage in the Response
> 3.	Service method returns Response to the user.
> 4.	If the user accesses Content first, we read the live stream, buffer into byte[], and return BinaryData wrapping the byte[]. If a subsequent call accesses ContentStream we either throw or return MemoryStream wrapping the byte[]
> 5.	If the user accesses ContentStream first, any subsequent access to Content or ContentStream will throw InvalidOperationException
>  
> In the case of buffered responses:
> 1.	Service method creates, composes, and sends an instance of HttpMessage.
> 1.	The transport reads the live stream into a byte[], stashes the byte[] in Response, disposes the HttpRequestMessage
> 1.	Service method returns Response to the user.
> 1.	If the caller accesses Content, we return BinaryData wrapping the byte[] 
> 1. If the caller accesses ContetnStream, we return MemoryStream wrapping the byte[]
>

#### Prior notes

See this comment thread for details: https://github.com/Azure/azure-sdk-for-net/pull/41016#discussion_r1442418397

This issue tracks the work to change how response buffering works for ClientModel responses.  @KrzysztofCwalina would like to optimize for buffered content in the BinaryData response.Content property and not retain the MemoryStream we used to buffer the content in the ContentStream property.  In a greenfield scenario, this would be great, but with a lot of code built on top of Azure.Core's response.ContentStream property and the idea that Content throws if ContentStream doesn't hold the buffered MemoryStream, we would likely need to go through breaking change review with the arch board to assess the feasibility of this change.  

A proposed implementation that helps identify the CI tests that are affected by this change can be found here: https://github.com/Azure/azure-sdk-for-net/pull/41047

### LINKED ISSUE #41198: ClientModel: Investigate feasibility of moving response buffering into the transport
Investigate   @KrzysztofCwalina's question regarding whether we can/should do buffering in the transport as opposed to doing it in a separate policy.

This issue tracks the request from this PR comment: https://github.com/Azure/azure-sdk-for-net/pull/41085#discussion_r1447695754

Investigation work-in-progress in this PR: https://github.com/Azure/azure-sdk-for-net/pull/41651

### PR DESCRIPTION
**Pull request by annelo-msft**
This PR moves content buffering into the transport and updates the API for PipelineResponse.Content in ClientModel.

Fixes: https://github.com/Azure/azure-sdk-for-net/issues/41198
Fixes: https://github.com/Azure/azure-sdk-for-net/issues/41080

### CODE REVIEW

File: sdk/core/System.ClientModel/src/Internal/ReadTimeoutStream.cs [hunk 1]
```diff
@@ -60,26 +59,26 @@ public override void Flush()
 
     public override int Read(byte[] buffer, int offset, int count)
     {
-        var source = StartTimeout(default, out bool dispose);
+        CancellationTokenSource source = StartTimeout(default, out bool dispose);
```
Comment (jsquire) [inline sdk/core/System.ClientModel/src/Internal/ReadTimeoutStream.cs:62]:
```suggestion
        using CancellationTokenSource source = StartTimeout(default, out bool dispose);
```

File: sdk/core/System.ClientModel/src/Internal/ReadTimeoutStream.cs [hunk 2]
```diff
@@ -90,7 +89,7 @@ public override int Read(byte[] buffer, int offset, int count)
 
     public override async Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
     {
-        var source = StartTimeout(cancellationToken, out bool dispose);
+        CancellationTokenSource source = StartTimeout(cancellationToken, out bool dispose);
```
Comment (jsquire) [inline sdk/core/System.ClientModel/src/Internal/ReadTimeoutStream.cs:92]:
```suggestion
        using CancellationTokenSource source = StartTimeout(cancellationToken, out bool dispose);
```

File: sdk/core/System.ClientModel/src/Internal/CancellationHelper.cs [hunk 3]
```diff
@@ -48,4 +48,24 @@ internal static void ThrowIfCancellationRequested(CancellationToken cancellation
...
+    /// <summary>Throws a cancellation exception if cancellation has been requested via <paramref name="messageToken"/> or <paramref name="timeoutToken"/>.</summary>
+    /// <param name="messageToken">The user-provided token.</param>
+    /// <param name="timeoutToken">The linked token that is cancelled on timeout provided token.</param>
+    /// <param name="innerException">The inner exception to use.</param>
+    /// <param name="timeout">The timeout used for the operation.</param>
+#pragma warning disable CA1068 // Cancellation token has to be the last parameter
+    internal static void ThrowIfCancellationRequestedOrTimeout(CancellationToken messageToken, CancellationToken timeoutToken, Exception? innerException, TimeSpan timeout)
+#pragma warning restore CA1068
+    {
+        ThrowIfCancellationRequested(messageToken);
```
Comment (christothes) [inline sdk/core/System.ClientModel/src/Internal/CancellationHelper.cs:61]: Is it intentional to ignore the `innerException` in this case?

File: sdk/core/System.ClientModel/src/Pipeline/PipelineTransport.cs [hunk 4]
```diff
@@ -1,97 +1,146 @@
...
+        => await ProcessSyncOrAsync(message, async: true).ConfigureAwait(false);
+
+    private async ValueTask ProcessSyncOrAsync(PipelineMessage message, bool async)
     {
-        await ProcessCoreAsync(message).ConfigureAwait(false);
+        Debug.Assert(message.NetworkTimeout is not null, "NetworkTimeout is not set on PipelineMessage.");
+
+        // Implement network timeout behavior around call to ProcessCore.
+        TimeSpan networkTimeout = (TimeSpan)message.NetworkTimeout!;
+        CancellationToken userToken = message.CancellationToken;
```
Comment (christothes) [inline sdk/core/System.ClientModel/src/Pipeline/PipelineTransport.cs:62]: nit: Is `messageToken` more accurate, given that this could either be the default or a user provided value?
```suggestion
        CancellationToken messageToken = message.CancellationToken;
```

File: sdk/core/System.ClientModel/src/Message/PipelineResponse.cs [hunk 5]
```diff
@@ -94,23 +94,72 @@ internal bool TryGetBufferedContent(out MemoryStream bufferedContent)
         return false;
     }
 
-    internal void BufferContent(TimeSpan? timeout = default, CancellationTokenSource? cts = default)
+    internal void ProcessContent(bool bufferResponse, CancellationToken userToken, CancellationTokenSource joinedTokenSource)
```
Comment (christothes) [inline sdk/core/System.ClientModel/src/Message/PipelineResponse.cs:97]: Since buffering is now owned by the transport, should this whole implementation be moved over to `PipelineTransport`?

Comment (annelo-msft) [reply sdk/core/System.ClientModel/src/Message/PipelineResponse.cs:97]: I think it makes sense to keep the buffering logic in the response, but I don't feel too strongly about this.  Only the part where we copy the content out of the network stream into a memory buffer is strictly needed in Response.  Do you see a strong advantage to moving the read-timeout-stream logic into the transport instead of holding it in the Response?

Comment (christothes) [reply sdk/core/System.ClientModel/src/Message/PipelineResponse.cs:97]: I don't see a strong reason for it to live one place or the other except to clarify which component owns the concern. The transport still initiates it by calling `ProcessContent` on the response, but it seems more straight forward for it to handle the buffering logic itself directly. 

The reasons I'd say it makes more sense to stay in Response is if this should be invoked from other callers besides the transport or if we plan to implement additional response types where buffering may be implemented differently.

File: sdk/core/System.ClientModel/src/Pipeline/PipelineTransport.cs (hunk 4 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/src/Pipeline/PipelineTransport.cs:62]: Yeah, that's fair.  I was thinking of it as what either the client-author or end-user might have provided (as I was working to understand the logic we have), but you are right it could also be a default.

File: sdk/core/System.ClientModel/src/Internal/ReadTimeoutStream.cs (hunk 1 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/src/Internal/ReadTimeoutStream.cs:62]: This is existing Azure.Core code - let me see if handling this correctly causes any problems!

File: sdk/core/System.ClientModel/src/Internal/CancellationHelper.cs (hunk 3 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/src/Internal/CancellationHelper.cs:61]: This is existing Azure.Core code -- if it's not easy to plumb this through quickly, I will file an issue to track

File: sdk/core/System.ClientModel/src/Message/PipelineResponse.cs (hunk 5 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/src/Message/PipelineResponse.cs:97]: BufferContent is invoked from ClientResultException, which is why that's needed in Response - I don't think we want to couple the transport into that functionality.  I can think a bit more about whether we need all of ProcessContent anywhere else, but it's also an implementation detail we can shift around after the fact, I think?

Comment (christothes) [reply sdk/core/System.ClientModel/src/Message/PipelineResponse.cs]: Makes sense, thanks. 

One last question - why not retain the name `BufferContent` or some similar name that reflects the intent of "buffer or wrap in a read-only stream"

Comment (christothes) [reply sdk/core/System.ClientModel/src/Message/PipelineResponse.cs]: > BufferContent is invoked from ClientResultException, which is why that's needed in Response

Aren't we moving towards a model evaluating `Content` "just works"? This would mean that only the transport would ever need to buffer explicitly.

Comment (annelo-msft) [reply sdk/core/System.ClientModel/src/Message/PipelineResponse.cs]: > Aren't we moving towards a model evaluating Content "just works"? This would mean that only the transport would ever need to buffer explicitly.

Sure, we can reevaluate what RequestFailedException/ClientResultException do when we close on what happens with response.Content.  I think until we close on that, we should preserve the behavior in the exception types where they buffer the response if that still needs to happen.

Comment (annelo-msft) [reply sdk/core/System.ClientModel/src/Message/PipelineResponse.cs]: I am going to add the response.Content change into this PR, so I'll close this thread since it reworks this area substantially.  If you have remaining comments, though, please add them in a new thread!

File: sdk/core/System.ClientModel/src/Internal/CancellationHelper.cs (hunk 3 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/src/Internal/CancellationHelper.cs]: Addressed

File: sdk/core/System.ClientModel/src/Convenience/ClientResultException.cs [hunk 6]
```diff
@@ -67,7 +67,7 @@ public override void GetObjectData(SerializationInfo info, StreamingContext cont
 
     private static string CreateMessage(PipelineResponse response)
     {
-        response.BufferContent();
+        response.ReadContent();
```
Comment (KrzysztofCwalina) [inline sdk/core/System.ClientModel/src/Convenience/ClientResultException.cs:70]: do we have an async variant of CreateMessage to uses async ReadContentAsync?

File: sdk/core/System.ClientModel/src/Internal/StreamExtensions.cs [hunk 7]
```diff
@@ -86,4 +89,45 @@ public static async Task WriteAsync(this Stream stream, ReadOnlySequence<byte> b
                 ArrayPool<byte>.Shared.Return(array);
         }
     }
+
+    public static async Task CopyToAsync(this Stream source, Stream destination, CancellationToken cancellationToken)
```
Comment (KrzysztofCwalina) [inline sdk/core/System.ClientModel/src/Internal/StreamExtensions.cs:93]: why do we need this method? Stream already has a method to copy from one stream to another.

File: sdk/core/System.ClientModel/src/Pipeline/HttpClientPipelineTransport.Response.cs [hunk 8]
```diff
@@ -39,17 +46,93 @@ protected override PipelineResponseHeaders GetHeadersCore()
...
+            if (async)
+            {
+                await _contentStream.CopyToAsync(bufferStream, cancellationToken).ConfigureAwait(false);
+            }
+            else
+            {
+                _contentStream.CopyTo(bufferStream, cancellationToken);
+            }
+
+            _contentStream.Dispose();
```
Comment (KrzysztofCwalina) [inline sdk/core/System.ClientModel/src/Pipeline/HttpClientPipelineTransport.Response.cs:125]: it would be good to call DisposeAsync in async mode.

File: sdk/core/System.ClientModel/tests/TestFramework/Mocks/MockPipelineResponse.cs [hunk 9]
```diff
@@ -50,6 +53,31 @@ public MockPipelineResponse SetContent(string content)
         set => _contentStream = value;
     }
 
+    public override BinaryData Content
+    {
+        get
+        {
+            if (_contentStream is null)
+            {
+                return BinaryData.FromString("");
```
Comment (KrzysztofCwalina) [inline sdk/core/System.ClientModel/tests/TestFramework/Mocks/MockPipelineResponse.cs:62]: why fromstring? Why not from empty array?

File: sdk/core/System.ClientModel/tests/TestFramework/Mocks/MockPipelineResponse.cs [hunk 10]
```diff
@@ -73,4 +101,48 @@ protected void Dispose(bool disposing)
...
+    public override BinaryData ReadContent(CancellationToken cancellationToken = default)
+    {
+        if (_bufferedContent is not null)
+        {
+            return _bufferedContent;
+        }
+
+        if (_contentStream is null)
+        {
+            _bufferedContent = BinaryData.FromString(string.Empty);
```
Comment (KrzysztofCwalina) [inline sdk/core/System.ClientModel/tests/TestFramework/Mocks/MockPipelineResponse.cs:114]: why not from empty array?

File: sdk/core/System.ClientModel/tests/TestFramework/Mocks/MockPipelineResponse.cs [hunk 11]
```diff
@@ -73,4 +101,48 @@ protected void Dispose(bool disposing)
...
+            return _bufferedContent;
+        }
+
+        MemoryStream bufferStream = new();
+        _contentStream.CopyTo(bufferStream);
+        _contentStream.Dispose();
+        _contentStream = bufferStream;
+
+        _bufferedContent = BinaryData.FromStream(bufferStream);
```
Comment (KrzysztofCwalina) [inline sdk/core/System.ClientModel/tests/TestFramework/Mocks/MockPipelineResponse.cs:123]: is FromStream optimized for MemoryStream? If not, this does unnecessary copy/stream-read.

File: sdk/core/System.ClientModel/tests/TestFramework/Mocks/MockPipelineResponse.cs [hunk 12]
```diff
@@ -73,4 +101,48 @@ protected void Dispose(bool disposing)
...
+
+        if (_contentStream is null)
+        {
+            _bufferedContent = BinaryData.FromString(string.Empty);
+            return _bufferedContent;
+        }
+
+        MemoryStream bufferStream = new();
+        await _contentStream.CopyToAsync(bufferStream).ConfigureAwait(false);
+        _contentStream.Dispose();
```
Comment (KrzysztofCwalina) [inline sdk/core/System.ClientModel/tests/TestFramework/Mocks/MockPipelineResponse.cs:142]: can we call DisposeAsync in async methods?

File: sdk/core/System.ClientModel/src/Convenience/ClientResultException.cs (hunk 6 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/src/Convenience/ClientResultException.cs:70]: This is called from the exception constructor, so it does not.

File: sdk/core/System.ClientModel/src/Pipeline/HttpClientPipelineTransport.Response.cs (hunk 8 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/src/Pipeline/HttpClientPipelineTransport.Response.cs:125]: Good suggestion

File: sdk/core/System.ClientModel/tests/TestFramework/Mocks/MockPipelineResponse.cs (hunk 9 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/tests/TestFramework/Mocks/MockPipelineResponse.cs:62]: This was a mock so I was being lazy, but I can change it.

File: sdk/core/System.ClientModel/src/Internal/StreamExtensions.cs (hunk 7 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/src/Internal/StreamExtensions.cs:93]: It is not available on netstandard2.0: https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.copytoasync?view=net-8.0#system-io-stream-copytoasync(system-io-stream-system-threading-cancellationtoken)

File: sdk/core/System.ClientModel/src/Convenience/ClientResultException.cs (hunk 6 above)
Comment (KrzysztofCwalina) [reply sdk/core/System.ClientModel/src/Convenience/ClientResultException.cs:70]: Should we have an async factory instead using this ctor?

File: sdk/core/System.ClientModel/src/Pipeline/HttpClientPipelineTransport.Response.cs (hunk 8 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/src/Pipeline/HttpClientPipelineTransport.Response.cs:125]: This is also not available on netstandard2.0.  Depending on how strongly you feel about this, we can polyfil it, but I'd prefer not to block the PR on it.

Comment (annelo-msft) [reply sdk/core/System.ClientModel/src/Pipeline/HttpClientPipelineTransport.Response.cs:130]: Good suggestion - I will do this

File: sdk/core/System.ClientModel/src/Internal/ReadTimeoutStream.cs (hunk 1 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/src/Internal/ReadTimeoutStream.cs:62]: Tracking with https://github.com/Azure/azure-sdk-for-net/issues/41932

File: sdk/core/System.ClientModel/src/Internal/ReadTimeoutStream.cs (hunk 2 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/src/Internal/ReadTimeoutStream.cs:92]: https://github.com/Azure/azure-sdk-for-net/issues/41932

File: sdk/core/System.ClientModel/tests/TestFramework/Mocks/MockPipelineResponse.cs (hunk 11 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/tests/TestFramework/Mocks/MockPipelineResponse.cs:123]: Since this is a mock, I'll leave this, but I'll add a comment to refer anyone wishing to copy it to a more performant implementation.

File: sdk/core/System.ClientModel/tests/TestFramework/Mocks/MockPipelineResponse.cs (hunk 10 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/tests/TestFramework/Mocks/MockPipelineResponse.cs:114]: Will fix

File: sdk/core/System.ClientModel/tests/TestFramework/Mocks/MockPipelineResponse.cs (hunk 12 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/tests/TestFramework/Mocks/MockPipelineResponse.cs:146]: Addressed

File: sdk/core/System.ClientModel/src/Convenience/ClientResultException.cs (hunk 6 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/src/Convenience/ClientResultException.cs:70]: Let me see what this looks like with the Azure.Core integration

Comment (annelo-msft) [reply sdk/core/System.ClientModel/src/Convenience/ClientResultException.cs:70]: Yeah, I think it's good.  We have some shared source files that can't move to it immediately in the Core integration PR, but I was able to port pipeline instances to this factory method.  I'll update this PR now with the ClientModel side of the change and LMK if the API looks like something we're happy with

**Review by KrzysztofCwalina — APPROVED** [review]

File: sdk/core/System.ClientModel/tests/Convenience/ClientRequestExceptionTests.cs [hunk 13]
```diff
@@ -24,6 +25,20 @@ public void CanCreateFromResponse()
             exception.Message);
     }
 
+    [Test]
+    public async Task CanCreateFromAsyncFactory()
```
Comment (m-nash) [inline sdk/core/System.ClientModel/tests/Convenience/ClientRequestExceptionTests.cs:29]: I don't see any other tests added here, does this validate all the different scenarios about buffer and non buffering that the issue discusses?

Comment (annelo-msft) [reply sdk/core/System.ClientModel/tests/Convenience/ClientRequestExceptionTests.cs:29]: Yeah, good call-out.  We have a lot of test coverage in the Azure.Core integration branch (and full CI coverage that client functionality is correct).  Tracking getting to parity with ClientModel tests as part of https://github.com/Azure/azure-sdk-for-net/issues/40560

Comment (annelo-msft) [reply sdk/core/System.ClientModel/tests/Convenience/ClientRequestExceptionTests.cs:29]: Added a comment to that one to track these cases specifically.  Thanks @m-nash!
