### PR TITLE
Tracing batch fix

### LINKED ISSUE #19053: [BUG] [Servicebus|Azure.Messaging.ServiceBus] SendMEssage MessageSizeExeeded in Azure
**Describe the bug**
I have an Azure function app that uses the Azure.Messaging.ServiceBus. Trying to send multiple messages in batch using CreateMessageBatchAsync. I'm adding messages with TryAddMesage and sends the batch if it returns false. This works localy but when I publish it to azure I get a MessageSizeExceeded when calling SendMessagesAsync.

It looks similar to this issue https://github.com/Azure/azure-sdk-for-net/issues/18038

**Expected behavior**
SendMessagesAsync should be able to send the message,

**Actual behavior (include Exception or Stack Trace)**
Getting this error in the azure function log: The message (id:37495150, size:296449 bytes) is larger than is currently allowed (262144 bytes). (MessageSizeExceeded)

**To Reproduce**

```csharp
public async Task<IEnumerable<QueueMessage>> SendMessagesAsync(IEnumerable<QueueMessage> messages)
        {
            var failedMessages = new List<QueueMessage>();
            ServiceBusMessageBatch batch = await _sender.CreateMessageBatchAsync();
            try
            {
                for (var i = 0; i < messages.Count(); i++)
                {
                    var json = JsonConvert.SerializeObject(messages.ElementAt(i), Formatting.None, new JsonSerializerSettings
                    {
                        NullValueHandling = NullValueHandling.Ignore
                    });
                    var serviceBusMessage = new ServiceBusMessage(json);


                    if (!batch.TryAddMessage(serviceBusMessage))
                    {
                        _logger.LogInformation("ServiceBusService, batch full. Messages: {Messages}, Size: {Size}", batch.Count, batch.SizeInBytes);
                        // Send the current batch as it is full and create a new one
                        await _sender.SendMessagesAsync(batch);

                        batch.Dispose();
                        batch = await _sender.CreateMessageBatchAsync();

                        if (!batch.TryAddMessage(serviceBusMessage))
                        {
                            _logger.LogInformation("ServiceBusService, Could not send message. MessageId: {MessgeId}", serviceBusMessage.MessageId);
                            failedMessages.Add(messages.ElementAt(i));
                        }
                    }

                }
                _logger.LogInformation("ServiceBusService, send last batch. Messages: {Messages}, Size: {Size}", batch.Count, batch.SizeInBytes);
                // send the final batch
                await _sender.SendMessagesAsync(batch);
            }
            finally
            {
                batch.Dispose();
            }

            return failedMessages;
        }
```

And here is the log output
```
2021-02-26 06:00:01.839
UploadMessagesToQueueAsync: SendMessagesAsync: 702
Information
2021-02-26 06:00:01.859
ServiceBusService, batch full. Messages: 440, Size: 262137
Information
2021-02-26 06:00:01.888
at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(Func`1 messageFactory, TimeSpan timeout, CancellationToken cancellationToken) at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(Func`1 messageFactory, TimeSpan timeout, CancellationToken cancellationToken) at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<>c__DisplayClass18_0.<<SendBatchAsync>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation(Func`2 operation, TransportConnectionScope scope, CancellationToken cancellationToken) at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation(Func`2 operation, TransportConnectionScope scope, CancellationToken cancellationToken) at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchAsync(ServiceBusMessageBatch messageBatch, CancellationToken cancellationToken) at Azure.Messaging.ServiceBus.ServiceBusSender.SendMessagesAsync(ServiceBusMessageBatch messageBatch, CancellationToken cancellationToken) at Obo.Messages.ApiClient.Services.ServiceBusService.SendMessagesAsync(IEnumerable`1 messages) in C:\Projects\SXBoendeApp\Backend\Tenants\OBO\OBO.Messages\Obo.Messages.ApiClient\Services\ServiceBusService.cs:line 57 at Obo.Messages.ApiClient.Services.MessagesApiClient.UploadMessagesToQueueAsync(IEnumerable`1 messages, IEnumerable`1 deletedIds) in C:\Projects\SXBoendeApp\Backend\Tenants\OBO\OBO.Messages\Obo.Messages.ApiClient\Services\MessagesApiClient.cs:line 201 at OBO.Messages.Booking.AptusFunction.BookingSync(TimerInfo myTimer, ILogger log, ExecutionContext context) in C:\Projects\SXBoendeApp\Backend\Tenants\OBO\OBO.Messages\FunctionApps\OBO.Messages.FunctionApps.Booking\AptusFunction.cs:line 128
Error
2021-02-26 06:00:01.892
The message (id:7331010, size:296449 bytes) is larger than is currently allowed (262144 bytes). (MessageSizeExceeded)
Error
2021-02-26 06:00:01.893
Executed 'BookingSync' (Failed, Id=64ba3ce0-b7b2-457b-8c46-80376a86c65d, Duration=1892ms)
Error
2021-02-26 06:00:01.899
The message (id:7331010, size:296449 bytes) is larger than is currently allowed (262144 bytes). (MessageSizeExceeded)
```

**Environment:**
Azure.Messaging.ServiceBus 7.1.0
.Net core 3.1
Azure Functions on Windows

### PR DESCRIPTION
**Pull request by JoshLove-msft**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/19053

### CODE REVIEW

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Sender/ServiceBusMessageBatch.cs [hunk 1]
```diff
@@ -91,7 +96,9 @@ public bool TryAddMessage(ServiceBusMessage message)
             lock (_syncGuard)
             {
                 AssertNotLocked();
-                return InnerBatch.TryAddMessage(message);
+
+                _scopeFactory.InstrumentMessage(message);
```
Comment (JoshLove-msft) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Sender/ServiceBusMessageBatch.cs:100]: I didn't see any issues with just instrumenting the message here as opposed to waiting for the send. In either case we mutate the message itself (not just the underlying AMQP message), so there doesn't seem to be a downside to potentially doing it a bit earlier.

Comment (jsquire) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Sender/ServiceBusMessageBatch.cs:100]: With this approach, the batch can be manipulated and the size exceeded.  

Event Hubs clones the message as a defensive measure to prevent changes after the measurement was done.   The clone, not the original event, is stored in the batch because the caller holds a reference to the original and can modify it which invalidates the measurement.    If the caller adds a message using `TryAdd` and then adds several user properties to the message, the size of the batch is now invalid and larger than was calculated.

Comment (jsquire) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Sender/ServiceBusMessageBatch.cs:100]: Ideally, we would be serializing to AMQP here and not cloning the event/message model, but we ran into issues with the AMQP library when retrying using that approach.    #9569 tracks revisiting this and, hopefully, avoiding the need for paying the serialization cost twice.

Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Sender/ServiceBusMessageBatch.cs:100]: So my understanding is that we either risk letting the batch get too large, or we ignore the changes a user makes to a message after they have added to the batch. I would prefer the former because if the batch gets too large, the user will be made aware of it via exception, whereas in the latter, they may not realize that the data they are setting is being ignored.

Comment (jsquire) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Sender/ServiceBusMessageBatch.cs:100]: I disagree and would recommend the first.   My thoughts:

- Cloning keeps the behavior consistent with the Service Bus behavior in _most_ of the other languages.  JS and Python store the AMQP message.  I think Java holds a reference to the message if I'm reading correctly. 

- Cloning keeps the behavior consistent with T1 and T2 Event Hubs in .NET.

- Cloning allows us to performance tune by caching the AMQP message instead of the model type, reducing the cost to a single serialization instead of paying it twice.

- Not cloning violates the guarantee made by the batch that `TryAdd` offers a safe operation; if it says `true` then you won't have an exception later.

- Not cloning leads to potential data corruption if the message is added to two different batches at the same time, as the instrumentation will fight for the same property slot.

Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Sender/ServiceBusMessageBatch.cs:100]: The risk of data loss by cloning seems like a bigger issue than cross language or cross service consistency.

Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Sender/ServiceBusMessageBatch.cs:100]: > Not cloning leads to potential data corruption if the message is added to two different batches at the same time, as the instrumentation will fight for the same property slot.

Wouldn't this be the case if you do a simultaneous sends with the same message? This doesn't seem like a valid scenario.

Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Sender/ServiceBusMessageBatch.cs:100]: Discussed offline and came to the conclusion that either behavior has its tradeoffs. I prefer leaving it as is especially since this has already GA'ed.

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Sender/ServiceBusMessageBatch.cs [hunk 2]
```diff
@@ -91,7 +96,9 @@ public bool TryAddMessage(ServiceBusMessage message)
             lock (_syncGuard)
             {
                 AssertNotLocked();
-                return InnerBatch.TryAddMessage(message);
+
```
Comment (jsquire) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Sender/ServiceBusMessageBatch.cs:99]: Regarding that discussion, should we add the documentation here to detail the behavior or did you have another place in mind?

**Review by jsquire — APPROVED** [review]

**Comment by Stabzs** [comment]
I know this is an old issue, but I just ran into the exact same problem in 7.11.1. 

In my example, messageBatch.TryAddMessage should stop just short of the 262144 byte threshold and attempt to send a batch. However, when the batch sent, it would fail with the following error message:

> {"The message (id:15939002, size:265268 bytes) is larger than is currently allowed (262144 bytes). (MessageSizeExceeded). For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot."}

I confirmed that rolling back to 7.1.1 fixed the problem. It would seem that there have been metadata additions between 7.1.1 and 7.11.1 that are not properly accounted for. I didn't test any versions in between.

**Comment by JoshLove-msft** [comment]
@Stabzs are you possibly mutating the message body after adding it to the batch?

**Comment by Stabzs** [comment]
@JoshLove-msft no there is no mutation in this case. The message is first serialized to Json before adding it to the batch, so a completely separate copy of the data is used.

**Comment by JoshLove-msft** [comment]
Ok, I'd suggest filing a separate issue with repro instructions so that we can investigate.
