### PR TITLE
fixed issue

### LINKED ISSUE #36058: [BUG] Failing test cases
### Library name and version

Azure.ResourceManager.DataShare

### Describe the bug

2 test cases are failing in main https://dev.azure.com/azure-sdk/public/_build/results?buildId=2753824&view=logs&j=5c1c6b8d-4c43-56d0-23a6-720b383b6e9d&t=c0689a97-7641-5aa2-9bbf-6a4650990a4c&l=406

### Expected behavior

expected that they don't fail :-)

### Actual behavior

They fail

### Reproduction Steps

See linked pipeline

### Environment

_No response_

### PR DESCRIPTION
**Pull request by mcgallan**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/36058

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

File: sdk/datashare/Azure.ResourceManager.DataShare/tests/TestCase/SynchronizationSettingTests.cs [hunk 1]
```diff
@@ -39,15 +39,14 @@ private async Task<DataShareSynchronizationSettingCollection> GetHronizationSett
...
-        [Ignore("https://github.com/Azure/azure-sdk-for-net/issues/36058")]
         public async Task HronizationSettingApiTests()
         {
             //1.CreateorUpdate
             var collection = await GetHronizationSettingCollectionAsync();
             var name = Recording.GenerateAssetName("TestHronization-");
             var name2 = Recording.GenerateAssetName("TestHronization-");
             var name3 = Recording.GenerateAssetName("TestHronization-");
-            var input = ResourceDataHelpers.GetSynchronizationData();
+            var input = ResourceDataHelpers.GetSynchronizationData(Recording.UtcNow);
```
Comment (ArcturusZhang) [inline sdk/datashare/Azure.ResourceManager.DataShare/tests/TestCase/SynchronizationSettingTests.cs:49]: instead of using data related with real life, could we just hard code a date here? For instance the date of today.

Comment (mcgallan) [reply sdk/datashare/Azure.ResourceManager.DataShare/tests/TestCase/SynchronizationSettingTests.cs:49]: fixed

**Review by ArthurMa1978 — APPROVED** [review]
