### PR TITLE
[Mgmt Generator] Flatten required value-type from optional parent as Nullable<T>

### LINKED ISSUE #58288: [Mgmt Generator] PropertyFlatten drops Nullable<T> wrapper on required value-type properties flattened from optional properties?: parent
## Problem

In [`FlattenPropertyVisitor.PropertyFlatten`](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/FlattenPropertyVisitor.cs#L650-L702), a required value-type property on an **optional** inner `properties?:` model is flattened as a **non-nullable** property on the outer model, which is unsafe (the getter will `NullReferenceException` if the inner `Properties` backing field is null) and inconsistent with the companion `SafeFlatten` code path, which correctly wraps such properties in `Nullable<T>`.

## Scenario (from Compute)

TypeSpec:

```tsp
model ProxyResourceCommunity<Properties extends {}> extends PirCommunityGalleryResource {
  properties?: Properties;                     // OPTIONAL parent
}

model CommunityGalleryImage
  is ProxyResourceCommunity<CommunityGalleryImageProperties> { ... }

model CommunityGalleryImageProperties {
  osType: OperatingSystemTypes;                // REQUIRED value-type child
  osState: OperatingSystemStateTypes;          // REQUIRED value-type child
  endOfLifeDate?: utcDateTime;                 // OPTIONAL child
  hyperVGeneration?: HyperVGeneration;         // OPTIONAL child
  ...
}
```

Generated (incorrect):

```csharp
public partial class CommunityGalleryImageData : ...
{
    internal CommunityGalleryImageProperties Properties { get; }   // may be null

    // BUG: required value-type in optional parent - generated non-nullable, NRE risk
    public SupportedOperatingSystemType OSType => Properties.OSType;
    public OperatingSystemStateType OSState => Properties.OSState;

    // OK: optional child - already nullable at the inner level
    public DateTimeOffset? EndOfLifeOn => Properties.EndOfLifeOn;
    public HyperVGeneration? HyperVGeneration => Properties.HyperVGeneration;
}
```

Expected:

```csharp
public SupportedOperatingSystemType? OSType => Properties?.OSType;
public OperatingSystemStateType?      OSState => Properties?.OSState;
```

This also matches the old AutoRest SDK's contract (e.g. `Azure.ResourceManager.Compute` historically exposed these as `Nullable<T>`), so the bug is a breaking ApiCompat regression across every `properties?:` + required-value-type-child combination in the compute migration.

## Root cause

`PropertyFlatten` computes `isOverriddenValueType` but **never applies it** to the flattened property's type:

```csharp
// FlattenPropertyVisitor.cs:650-702 (PropertyFlatten)
private void PropertyFlatten(ModelProvider model, ModelProvider propertyModel, ...)
{
    // dead: this tuple-list is declared but never populated
    var flattenedProperties = new List<(bool IsOverriddenValueType, PropertyProvider FlattenedProperty)>();

    foreach (var innerProperty in innerProperties)
    {
        ...
        // computed but never consumed
        var isOverriddenValueType = innerProperty.Type.IsValueType && !innerProperty.Type.IsNullable;
        var flattenedProperty =
            new FlattenedPropertyProvider(
                innerProperty.Description,
                innerProperty.Modifiers,
                innerProperty.Type,                  // <-- BUG: should use WithNullable when isOverriddenValueType
                ...);
        ...
    }
}
```

Compare to the sibling `SafeFlatten` at [lines 739-744](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/FlattenPropertyVisitor.cs#L739-L744), which applies it correctly:

```csharp
var isOverriddenValueType = innerProperty.Type.IsValueType && !innerProperty.Type.IsNullable;
var flattenedProperty =
    new FlattenedPropertyProvider(
        innerProperty.Description,
        innerProperty.Modifiers,
        isOverriddenValueType ? innerProperty.Type.WithNullable(true) : innerProperty.Type,
        ...);
```

The `IsOverriddenValueType` helper is also correctly consumed for **model factory method parameters** at [line 273](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/FlattenPropertyVisitor.cs#L273):

```csharp
if (IsOverriddenValueType(flattenedProperty))
{
    updatedParameter.Update(type: updatedParameter.Type.WithNullable(true));
}
```

So model factory parameters are generated as `Nullable<T>` but the corresponding flattened property is generated as `T`. The types are internally inconsistent within a single generated model.

## Proposed fix

Apply the same `WithNullable(true)` transform in `PropertyFlatten` that `SafeFlatten` already does:

```diff
-                var isOverriddenValueType = innerProperty.Type.IsValueType && !innerProperty.Type.IsNullable;
+                var isOverriddenValueType = innerProperty.Type.IsValueType && !innerProperty.Type.IsNullable;
                 var flattenedProperty =
                     new FlattenedPropertyProvider(
                         innerProperty.Description,
                         innerProperty.Modifiers,
-                        innerProperty.Type,
+                        isOverriddenValueType ? innerProperty.Type.WithNullable(true) : innerProperty.Type,
                         flattenPropertyName,
                         ...);
```

The getter bodies produced by `PropertyHelpers.BuildGetter` already null-propagate through the internal backing property when the inner model is nullable - the change is purely to align the public API surface with the existing runtime behavior and with the ModelFactory signature.

## Impact

This affects **every management RP** that:
- uses `properties?:` (optional inner, which is the common ARM pattern), AND
- has at least one required value-type (enum, `int`, `bool`, `DateTimeOffset`, closed struct-enum, ...) child inside `properties`, AND
- flattens `properties` (either implicitly via ARM resource templates or explicitly via `@flattenProperty`).

In the Compute migration alone this fix accounts for a large share of the remaining `ApiCompat MembersMustExist` errors (`OSType`, `OSState`, various `HyperVGeneration*`, sku-related flags, etc.). Fixing it in the generator avoids fanning out customization shims into every affected RP.

## Repro / verification

Run `Generate.ps1` in `eng/packages/http-client-csharp-mgmt/` after the fix and diff the generated `CommunityGalleryImageData.cs` (or any test project that flattens a `properties?:` with required value-type children). The only expected changes are `T` → `T?` on the affected flattened properties.

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Fixes #58288.

### Problem
`FlattenPropertyVisitor.PropertyFlatten` emitted required value-type inner properties (enum or primitive) as non-nullable on the flattened wrapper, even when the parent `properties?:` reference is optional. The public getter is null-guarded and returns `default` when the backing `Properties` is null, so callers observe a silent zero-value instead of a real `null`. The shape also diverged from the `ModelFactory` parameter type produced by `IsOverriddenValueType`.

Concrete repro was Compute's `CommunityGalleryImageData.OSType` (required `OperatingSystemType` flattened from optional `properties?:`) generating as non-nullable after migration.

### Fix
1. `PropertyFlatten` now applies `WithNullable(true)` to the `FlattenedPropertyProvider` type when the inner is a non-nullable value type — mirroring what `SafeFlatten` already does and what `PatchModelFactoryParameterTypes` already emits.
2. `BuildSetterForPropertyFlatten` now keys off `isOverriddenValueType` (inner is non-nullable value type) to decide whether to unwrap `value.Value`. The previous `isNullableValueType` branch was never true post-flatten and was incorrectly unwrapping when the inner was already `T?`, producing a latent NRE on `value.Value` for already-nullable inner properties (see diffs in `ClusterData.cs` / `IssueTest*.cs`).

### Validation
- Added unit test `TestFlattenMakesRequiredValueTypeNullable` in `FlattenPropertyVisitorTests`.
- All 160 mgmt generator tests pass.
- Regenerated TestProjects show the expected `int? MiddleProp1` / `int? Prop2` on `BarSettingsResourceData` and the corrected setter bodies on existing nullable-inner flatten sites.

---
🤖 arcturus-copilot

### CODE REVIEW

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Utilities/PropertyHelpers.cs [hunk 1]
```diff
@@ -154,7 +154,7 @@ public static MethodBodyStatement BuildGetter(bool? includeGetterNullCheck, Prop
                 {
                         internalPropertyExpression.Assign(New.Instance(innerModel.Type!)).Terminate()
                 });
-            setter.Add(internalPropertyExpression.Property(innerProperty.Name).Assign(isNullableValueType ? Value.Property(nameof(Nullable<int>.Value)) : Value).Terminate());
+            setter.Add(internalPropertyExpression.Property(innerProperty.Name).Assign(isOverriddenValueType ? Value.Property(nameof(Nullable<int>.Value)) : Value).Terminate());
```
Comment (live1206) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Utilities/PropertyHelpers.cs]: this seems wrong, when it is a non-nullable value type, we are assigning a nullable value.

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Primitives/FlattenedPropertyProvider.cs [hunk 2]
```diff
@@ -21,11 +21,21 @@ internal class FlattenedPropertyProvider : PropertyProvider
...
 
-        public FlattenedPropertyProvider(FormattableString? description, MethodSignatureModifiers modifiers, CSharpType type, string name, PropertyBody body, TypeProvider enclosingType, PropertyProvider flattenedFrom, PropertyProvider originalProperty, CSharpType? explicitInterface = null, PropertyWireInformation? wireInfo = null, bool isRef = false, IEnumerable<AttributeStatement>? attributes = null)
+        /// <summary>
+        /// True when this flattened property's type was lifted to <c>Nullable&lt;T&gt;</c>
+        /// because the inner is a non-nullable value type but the wrapping parent
+        /// (e.g. <c>properties?:</c>) may be absent at runtime. The public property
+        /// surface is <c>T?</c>, but the public constructor parameter is kept as the
+        /// original non-nullable <c>T</c> to enforce that required leaves are provided.
+        /// </summary>
+        public bool IsLiftedFromValueType { get; }
```
Comment (live1206) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Primitives/FlattenedPropertyProvider.cs]: From the xml doc, this flag means the property is lifted from value type, and it original property is non-nullable, but its flattened property is nullable because the nesting property is optional? There is a lot of information for this property, we need a better name for it.

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/FlattenPropertyVisitor.cs [hunk 3]
```diff
@@ -266,11 +266,19 @@ private void UpdateModelFactoryMethod(MethodProvider method, Dictionary<string,
...
+                        // existing InputType-based path.
+                        var newParamType = liftedToNullable
+                            ? propertyParameter.Type.WithNullable(true)
+                            : propertyParameter.Type.InputType;
+                        var updatedParameter = new ParameterProvider(propertyParameter.Name, propertyParameter.Description, newParamType, propertyParameter.DefaultValue,
                             propertyParameter.IsRef, propertyParameter.IsOut, propertyParameter.IsIn, propertyParameter.IsParams, propertyParameter.Attributes, propertyParameter.Property,
                             propertyParameter.Field, propertyParameter.InitializationValue, propertyParameter.Location, propertyParameter.WireInfo, propertyParameter.Validation);
 
-                        if (IsOverriddenValueType(flattenedProperty))
+                        if (!liftedToNullable && IsOverriddenValueType(flattenedProperty))
```
Comment (live1206) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/FlattenPropertyVisitor.cs]: liftedToNullable means the flattened property is non-nullable value type and its nesting property type is nullable or optional, it already covers IsOverriddenValueType. We can just keep liftedToNullable

Comment (live1206) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/FlattenPropertyVisitor.cs]: And should this be liftedToNullable instead of !lifttedToNullable?
I don't see what the current condition means.

File: eng/packages/http-client-csharp-mgmt/docs/property-flatten-nullability.md [hunk 4]
```diff
@@ -0,0 +1,193 @@
...
+| Variant | Trigger |
+| --- | --- |
+| **Property flatten** | The wrapper has a single inner property; the wrapper is fully replaced by it. |
+| **Safe flatten** | The wrapper has multiple inner properties; selected ones are surfaced on the parent. |
+
+---
+
+## 1. When is the flattened public property `T?`?
+
+**A flattened property is lifted to `Nullable<T>` / nullable reference iff the wrapping parent (e.g. `properties?:`) may be absent at runtime.** That is, when the wrapper is either declared nullable or declared optional (not required) on the wire.
```
Comment (live1206) [inline eng/packages/http-client-csharp-mgmt/docs/property-flatten-nullability.md]: does iff mean if and only if here? but there is only 1 condition here, the parent may be absent.

File: eng/packages/http-client-csharp-mgmt/docs/property-flatten-nullability.md [hunk 5]
```diff
@@ -0,0 +1,193 @@
...
+
+---
+
+## 3. Setter behavior
+
+Setters are emitted only when both the wrapper and the inner property had a setter, and never for collections (collections expose mutability through the returned list).
+
+For non-collection inners the canonical pattern is **lazy-create the wrapper, then assign the leaf**:
+
+```csharp
```
Comment (live1206) [inline eng/packages/http-client-csharp-mgmt/docs/property-flatten-nullability.md]: should we reflect the null setter case explaining below in this example?
only non-null value will be set, null value will be skipped as no-op.
or should we skip this example since we have a more complete example below?

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Utilities/PropertyHelpers.cs [hunk 6]
```diff
@@ -138,60 +138,90 @@ public static MethodBodyStatement BuildGetter(bool? includeGetterNullCheck, Prop
...
+            // lifted non-nullable value-type inner the public setter receives Nullable<T>.
+            // When the caller passes null we have no T to assign and no original value to
+            // preserve, so we simply no-op; assigning default(T) would silently erase the
+            // inner leaf to 0/None. For already-nullable inners and reference types, the
+            // public type matches the inner type and we pass the value through directly.
+            // Setting a leaf to null does NOT clear sibling leaves on the same parent.
             var internalPropertyExpression = This.Property(internalProperty.Name);
-
-            setter.Add(
+            var needsUnwrap = isPropertyLiftedToNullable && innerProperty.Type.IsValueType && !innerProperty.Type.IsNullable;
```
Comment (live1206) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Utilities/PropertyHelpers.cs:197]: this code block seems redundant with safe-flatten except the else branch, can we make it reusable somehow?

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Primitives/FlattenedPropertyProvider.cs (hunk 2 above)
Comment (ArcturusZhang) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Primitives/FlattenedPropertyProvider.cs]: Kept the `IsLiftedToNullable` name — I've taken your description ("flattened property's nesting property is optional/nullable while inner is non-nullable value type") and made it the canonical definition in the new docs file `eng/packages/http-client-csharp-mgmt/docs/property-flatten-nullability.md` (sections 1 + Terminology), so the term is now well-defined and used consistently across the visitor, the property provider, and the docs.

---
🤖 arcturus-copilot

File: eng/packages/http-client-csharp-mgmt/docs/property-flatten-nullability.md (hunk 4 above)
Comment (ArcturusZhang) [reply eng/packages/http-client-csharp-mgmt/docs/property-flatten-nullability.md]: Reworded in 83a4e62 — dropped `iff` since it's a single condition. Now reads: "**A flattened property is lifted to `Nullable<T>` / nullable reference when the wrapping parent (e.g. `properties?:`) may be absent at runtime** — i.e. when the wrapper is declared either nullable or optional (not required) on the wire."

---
🤖 arcturus-copilot

File: eng/packages/http-client-csharp-mgmt/docs/property-flatten-nullability.md (hunk 5 above)
Comment (ArcturusZhang) [reply eng/packages/http-client-csharp-mgmt/docs/property-flatten-nullability.md]: Removed in 83a4e62 — agreed, the canonical-pattern code block was redundant with the more complete examples in section 5 (5.1 / 5.3 show the exact same shape with all variants of the HasValue guard). The prose now points at section 5 for concrete output.

---
🤖 arcturus-copilot

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Utilities/PropertyHelpers.cs (hunk 6 above)
Comment (ArcturusZhang) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Utilities/PropertyHelpers.cs:197]: Refactored in 83a4e62 — extracted the shared "lazy-create wrapper + assign leaf (with optional HasValue guard)" body into a private `BuildLazyCreateAndAssignSetter` helper. Both `BuildSetterForPropertyFlatten` and the `includeSetterCheck=true` branch of `BuildSetterForSafeFlatten` now delegate to it; only the `includeSetterCheck=false` else-branch (the wrap-or-null pattern unique to safe-flatten without a parameterless ctor) stays separate. Verified behavior-preserving by regenerating test projects: no C# diff.

---
🤖 arcturus-copilot

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/FlattenPropertyVisitor.cs (hunk 3 above)
Comment (ArcturusZhang) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/FlattenPropertyVisitor.cs]: Addressed in the centralization: `ShouldLiftToNullable` in `FlattenPropertyVisitor.cs` is the single decision point and incorporates both "parent optional/nullable" and "inner non-nullable value type"; the older `IsOverriddenValueType` predicate is no longer used in this control flow. Behavior + naming are documented in `docs/property-flatten-nullability.md`.

---
🤖 arcturus-copilot

**Review by live1206 — APPROVED** [review]
