### PR TITLE
[EventHubs] Improving Event Hubs unit tests coverage

### LINKED ISSUE #9227: Address gaps in Event Processor test coverage
## Issue

The `Azure.Messaging.EventHubs.Processor` package is lacking in test coverage. There are already multiple tests, but they are not enough to ensure proper behavior.

## Goal

Tests for the following scenarios need to be added:
- [x] A `CancellationToken` that has already been cancelled makes `StartProcessingAsync` and `StopProcessingAsync` throw a `TaskCanceledException` (include tests for synchronous methods as well).
- [x] `StartProcessing` and `StopProcessing` synchronous implementations should still start and stop the processor successfully (it should be enough to assert they delegate to the asynchronous implementations. Useful for the previous item as well).
- [x] `StartProcessingAsync` should take no action when processor has already started and hasn't been explicitly stopped. `StopProcessingAsync` should take no action when processor hasn't been started / has already stopped (however, `StopProcessingAsync` resets state when load balancing task is not running because of a failure).
- [x] Processor should allow starting / stopping / starting again.
- [x] ~Processor should be able to recover from a disconnection~ Simulating a disconnection would be difficult without injecting at the AMQP level. It's not worth it given that the processor would deal with it like any other consumer exception.
- [x] `StopProcessingAsync` should surface any load balancing exceptions.
- [x] `StopProcessingAsync` should stop processing for every partition the processor owns and invoke the close handler for each one of them (with reason = `Shutdown`). We need to somehow verify that processing is not taking place anymore. Simply checking the stop handler wouldn't be enough.
- [x] `ToString` should return a string that contains the processor's identifier.
- [x] The processor should renew its ownership every cycle.
- [x] Error handler should be triggered when ownership renewal has failed (make sure there is no partition id).
- [x] The processor should stop processing partitions it doesn't own anymore. Ensure the close handler is called with `OwnershipLost` reason as well.
- [x] The processor should restart processing partitions whose processing tasks have failed (except when the failure has been triggered by user code: #9228). Ensure the close handler is called with `OwnershipLost` reason and the init handler has been called for this same partition. Error handler should be called with the appropriate partition id as well.
- [x] The error handler should be triggered with no partition id when ownership list retrieval from the `StorageManager` fails.
- [x] The error handler should be triggered with no partition id when partitions list retrieval fails.
- [x] The init handler should be triggered with the correct partition id when a new ownership is claimed.
- [x] The error handler should be triggered with the correct partition id when a call to `ListCheckpointAsync` in the `StorageManager` fails. This happens only when starting the processing of a partition.
- [x] Even in case a shutdown has been requested, stopping the processing of a partition should trigger the stop handler with reason = `OwnershipLost` if the processing task has coincidentally failed (properly coordinating the timing is important in this test). We are basically testing this piece of code:
https://github.com/Azure/azure-sdk-for-net/blob/f234423f8615ea1934e5af042589799a82fd6e49/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L1294-L1296
- [x] The error handler should be triggered with the correct partition id when a new ownership claim has failed. This test will fail because the current code mistakenly passes a null partition id:
https://github.com/Azure/azure-sdk-for-net/blob/f234423f8615ea1934e5af042589799a82fd6e49/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L1358
- [x] An exception thrown by `StorageManager.ClaimOwnershipAsync` while relinquishing ownership should not trigger the error handler and be surfaced to the user.
- [x] When processing a partition, the process handler should be called once for every received event.
- [x] When a maximum wait time is not specified in the options, the process handler should not be triggered while events are not being received. It should be periodically triggered with a `null` partition context otherwise. Edit: partially solved by `ProcessEventAsyncReceivesAnEmptyPartitionContextForNoData`. A new test will be included.
- [x] When triggered with no data, `ProcessEventArgs.UpdateCheckpointAsync` throws an `InvalidOperationException`.
- [x] Calling `ProcessEventArgs.UpdateCheckpointAsync` with a canceled token should throw a `TaskCanceledException`.
- [x] `ProcessEventArgs.UpdateCheckpointAsync` surfaces the exception when `StorageManager.UpdateCheckpointAsync` throws. It would be nice to assert it does not call the error handler as well.
- [x] Throwing from ~any handler~ initialize or process handler should bubble the exception up and make the processor stop working. ~We should include tests for every possible error handler call, even though it's a bit overwhelming~. Currently this will fail for the process handler (tracked by #9228).
- [x] When processing is requested to stop, every handler still in execution should have its `CancellationToken` canceled.
- [x] Constructor test (include tests for both constructors): `RetryPolicy` should be passed to the `BlobsCheckpointStore` constructor.
- [x] `BlobsCheckpointStore` methods should throw a `TaskCanceledException` when cancellation has been requested before calling them.
- [x] `BlobsCheckpointStore` calls to the Storage SDK should delegate the `RetryPolicy` and the `CancellationToken`.
- [x] Publish a set of events and then process them, creating a checkpoint for the last event.   Create a new processor and begin processing.  No exception should occur.  Publish a set of events and verify that only these new events are seen by the second processor.

### PR DESCRIPTION
**Pull request by kinelski**
Fixes #9227.

- Multiple test scenarios added.
- I reordered some tests in `EventProcessorClientTests` to keep them more organized.
- Some tests removed from `EventProcessorClientLiveTests` because they were duplicates of the new tests.

### CODE REVIEW

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs [hunk 1]
```diff
@@ -952,7 +952,7 @@ private async Task RunAsync(CancellationToken cancellationToken)
                     }
                     catch (EventHubsException ex)
                     {
-                        var errorEventArgs = new ProcessErrorEventArgs(null, ex.Message, ex, cancellationToken);
+                        var errorEventArgs = new ProcessErrorEventArgs(null, ex.Message, ex.InnerException ?? ex, cancellationToken);
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs]: Should we not us the same exception for the message?

File: sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Processor/PartitionLoadBalancer.cs [hunk 2]
```diff
@@ -167,9 +167,10 @@ protected PartitionLoadBalancer()
                 cancellationToken.ThrowIfCancellationRequested<TaskCanceledException>();
 
                 // If ownership list retrieval fails, give up on the current cycle.  There's nothing more we can do
-                // without an updated ownership list.
+                // without an updated ownership list.  Set the EventHubName to null so it doesn't modify the exception
+                // message.
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Processor/PartitionLoadBalancer.cs]: Not sure that I understand why this is a concern.

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs [hunk 3]
```diff
@@ -700,113 +674,1998 @@ public async Task IsRunningReturnsTrueWhileStopProcessingAsyncIsNotCalled()
...
+        public async Task StopProcessingAsyncDoesNothingWhenProcessorIsNotRunning()
         {
-            var mockProcessor = new Mock<EventProcessorClient>(Mock.Of<StorageManager>(), "consumerGroup", "namespace", "eventHub", Mock.Of<Func<EventHubConnection>>(), default, default) { CallBase = true };
-            var completionSource = new TaskCompletionSource<bool>();
+            var mockStorage = new Mock<MockCheckPointStorage>(default(Action<string>)) { CallBase = true };
+            var mockConsumer = new Mock<EventHubConsumerClient>("consumerGroup", Mock.Of<EventHubConnection>(), default);
+            var mockProcessor = new InjectableEventSourceProcessorMock(mockStorage.Object, "consumerGroup", "namespace", "eventHub", Mock.Of<Func<EventHubConnection>>(), default, mockConsumer.Object);
 
-            // This should be called right before the first load balancing cycle.
+            // Ownership claim attempts with an empty owner identifier are actually relinquish requests. This should happen once
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs]: Is this comment still accurate?   I thought that there was a dedicated method for this now.

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs [hunk 4]
```diff
@@ -700,113 +674,1998 @@ public async Task IsRunningReturnsTrueWhileStopProcessingAsyncIsNotCalled()
...
             await mockProcessor.Object.StartProcessingAsync(cancellationSource.Token);
 
-            Assert.That(mockProcessor.Object.IsRunning, Is.True);
+            Assert.That(mockProcessor.Object.IsRunning, Is.False, "StartProcessingAsync should not be able to reset processor state.");
+
+            try
+            {
+                await mockProcessor.Object.StopProcessingAsync(cancellationSource.Token);
+            }
+            catch (Exception) { }
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs]: This seems dangerous.   Is there a specific exception that we expect?

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs [hunk 5]
```diff
@@ -700,113 +674,1998 @@ public async Task IsRunningReturnsTrueWhileStopProcessingAsyncIsNotCalled()
...
+
+            mockConsumer
+                .Setup(consumer => consumer.ReadEventsFromPartitionAsync(
+                    It.IsAny<string>(),
+                    It.IsAny<EventPosition>(),
+                    It.IsAny<ReadEventOptions>(),
+                    It.IsAny<CancellationToken>()))
+                .Callback(() =>
+                {
+                    if (Interlocked.Increment(ref partitionsBeingProcessed) == partitionIds.Length)
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs]: Should we consider `>=` for safety here?

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs [hunk 6]
```diff
@@ -700,113 +674,1998 @@ public async Task IsRunningReturnsTrueWhileStopProcessingAsyncIsNotCalled()
...
+        ///   method.
+        /// </summary>
+        ///
+        [Test]
+        public async Task StopProcessingAsyncShouldSurfaceLoadBalancingException()
+        {
+            var mockProcessor = new Mock<EventProcessorClient>(Mock.Of<StorageManager>(), "consumerGroup", "namespace", "eventHub", Mock.Of<Func<EventHubConnection>>(), default, default) { CallBase = true };
+            var completionSource = new TaskCompletionSource<bool>();
+
+            mockProcessor
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs]: Is that considered a load balancing exception or is the name a bit misleading?

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs [hunk 7]
```diff
@@ -1713,14 +3444,30 @@ private static EventHubConnectionOptions GetConnectionOptionsSample(EventProcess
...
+            }
+        }
+
         /// <summary>
         ///   Allows for injecting a consumer client to use as the source of events to be processed.
         /// </summary>
         ///
         private class InjectableEventSourceProcessorMock : EventProcessorClient
         {
+            public Func<string, EventPosition, CancellationToken, bool> CatchNUnitRunnerException = (id, pos, token) => true;
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs]: Maybe consider making this a bit more generic?  `IgnoreTestRunnerException`?

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs [hunk 8]
```diff
@@ -700,113 +674,1998 @@ public async Task IsRunningReturnsTrueWhileStopProcessingAsyncIsNotCalled()
...
+                    return MockEndlessPartitionEventEnumerable(options.MaximumWaitTime, token);
+                });
+
+            // Use the close handler to keep track of the partitions that have been closed.
+
+            var closingEventArgs = new ConcurrentDictionary<string, PartitionClosingEventArgs>();
+
+            mockProcessor.PartitionClosingAsync += eventArgs =>
+            {
+                closingEventArgs[eventArgs.PartitionId] = eventArgs;
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs]: maybe try another completion source here to avoid the delay loop after?

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs (hunk 1 above)
Comment (kinelski) [reply sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs]: This is the exception thrown by the `PartitionLoadBalancer` class. We talked about it while reviewing Chris' PR. Basically, the load balancer wraps the actual exception in an `EventHubsException` before throwing it to the processor. We are using the inner exception here to remove the unnecessary wrapper around it.

File: sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Processor/PartitionLoadBalancer.cs (hunk 2 above)
Comment (kinelski) [reply sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Processor/PartitionLoadBalancer.cs]: Any exception encountered in the `PartitionLoadBalancer` class is wrapped in an `EventHubsException` before being thrown, so we pass the operation string as the error message. The processor catches this exception, unwraps it and passes it to the error handler.

In this point of the code we are wrapping the exception. If we set the event hub name, the error message will be: `$"{ Operation } ({ EventHubName })"`, and we won't be able to capture the operation string in the format we want. Other places in the code are simply `${ Operation }`.

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs (hunk 3 above)
Comment (kinelski) [reply sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs]: We have a dedicated method in the `PartitionLoadBalancer` class, but it basically makes a call to the storage's `ClaimOwnershipAsync` method. We are overriding the storage here.

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs (hunk 4 above)
Comment (kinelski) [reply sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs]: Kinda...? In this test we forced an exception to happen in order to test the `IsRunning` property. So an exception is expected here, but it's not exactly what we are testing. I tried using an `Assert.That(..., Throws...)`, but for some reason it makes the test hang indefinitely (certainly an issue with NUnit, that's not the first time something like this happened). I could use a boolean variable to make sure the method has thrown, if you prefer.

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs (hunk 5 above)
Comment (kinelski) [reply sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs]: It won't hurt. I'll update the `SetResult` to `TrySetResult` as well just in case.

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs (hunk 1 above)
Comment (jsquire) [reply sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs]: ooohhhh.... right.   My bad.  Forgot about that.

File: sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Processor/PartitionLoadBalancer.cs (hunk 2 above)
Comment (jsquire) [reply sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Processor/PartitionLoadBalancer.cs]: Fair enough.   Can we just call out that we're expecting the raw operation in the comment?   Otherwise, I'm likely to forget again.

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs (hunk 4 above)
Comment (jsquire) [reply sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs]: I'm fine leaving the try/catch to ignore, I'm just thinking that if we can lock it down to just a specific exception or set of exception types, we don't risk ignoring an issue because the catch swallowed something unexpected.

**Review by jsquire — APPROVED** [review]

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs (hunk 6 above)
Comment (kinelski) [reply sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs]: The name is misleading. I didn't have the `PartitionLoadBalancer` in mind when I wrote this method. What do you think about `BackgroundRunningTaskException`?

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs (hunk 8 above)
Comment (kinelski) [reply sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs]: I've been using the delay loop in my tests so we don't end up hanging indefinitely in case of unexpected behavior. You can see I have multiple tests in which I'm using the completion source AND the delay loop. This flaky test, in particular, hangs sometimes if I don't use the loop, so I think leaving it like this is fine.

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs (hunk 4 above)
Comment (kinelski) [reply sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs]: I've updated the code to save the caught exception instance and make sure it's the exception we've thrown.

File: sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Processor/PartitionLoadBalancer.cs (hunk 2 above)
Comment (kinelski) [reply sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Processor/PartitionLoadBalancer.cs]: Just updated the comments.

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs (hunk 6 above)
Comment (jsquire) [reply sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs]: Works for me.   I think it better represents the scenario.

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs (hunk 8 above)
Comment (jsquire) [reply sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs]: If we're seeing consistent results across environments, I'm good with leaving it.   I've been slowly trying to root out the timing-based things as I babysit tests as they tend to be cranky when the nightly runs are under load and there's a lot of delays.
