### PR TITLE
Thread backcompat provider through ClientProviderExtensions.GetConvenienceMethodByOperation

### LINKED ISSUE #56502: Code Generator change well-known paging method parameter top to maxCount
Custom code is required to revert the unexpected change, as shown the PR
https://github.com/Azure/azure-sdk-for-net/pull/55531. Management plain Generator or it's upstream Generator should fix the issue at the first place.

### PR DESCRIPTION
**Pull request by JoshLove-msft**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/56502

### CODE REVIEW

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/test/Utilities/ClientProviderExtensionsTests.cs [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+
+            var syncMethod = restClient.GetConvenienceMethodByOperation(operation, false);
+            var asyncMethod = restClient.GetConvenienceMethodByOperation(operation, true);
+
+            Assert.IsNotNull(syncMethod);
+            Assert.IsNotNull(asyncMethod);
+            Assert.AreNotEqual(syncMethod.Signature.Name, asyncMethod.Signature.Name);
+        }
+
+        private static (InputClient Client, ClientProvider RestClient) SetupClientProvider()
```
Comment (live1206) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/test/Utilities/ClientProviderExtensionsTests.cs]: Don't feel like the set up tests are related to the fixing case, it mostly verified the sync/async naming. Can we let copilot to set up a test that actually reflect the scenario in #56502?

Comment (JoshLove-msft) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/test/Utilities/ClientProviderExtensionsTests.cs]: I don't think we have the necessary test infrastructure for back compat testing.

Comment (JoshLove-msft) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/test/Utilities/ClientProviderExtensionsTests.cs]: @copilot is there any way for you to create a test of the actual scenario being fixed. In the scenario, we need to simulate a LastContractView that contains method with a "top" parameter and validate it doesn't get renamed to maxCount after this fix.

Comment (live1206) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/test/Utilities/ClientProviderExtensionsTests.cs]: > I don't think we have the necessary test infrastructure for back compat testing.

If so, I guess we can skip this testing for now. It doesn't add much value here. We can verify the fix in the specific RP sdk generation.

Comment (live1206) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/test/Utilities/ClientProviderExtensionsTests.cs]: We can setup something for this in mgmt local spec test to verify this, but we are thinking about cleaning that up as well and leverage the sdk regen.

Comment (JoshLove-msft) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/test/Utilities/ClientProviderExtensionsTests.cs]: Ok deleted

**Review by live1206 — APPROVED** [review]
