### PR TITLE
Fix FlattenPropertyVisitor name-based matching for custom code overrides

### LINKED ISSUE #57525: [Mgmt Generator] Model factory generates public methods with internal type parameters
## Bug Description

The management generator emits public model factory methods that accept internal types as parameters. This produces code that won't compile without `CodeGenSuppress` workarounds.

## Reproduction

When a resource data model has a `Properties` property that is suppressed via `CodeGenSuppress` and re-exposed as `internal` in custom code (a common pattern for backward-compat during migration), the generator still emits factory methods referencing the internal properties type.

**Example from `Azure.ResourceManager.NewRelicObservability`:**

The generated `NewRelicAccountResourceData` has:
```csharp
internal partial class AccountProperties { ... }
```

Custom code suppresses the generated `Properties` property and re-exposes it as internal:
```csharp
[CodeGenSuppress("Properties")]
public partial class NewRelicAccountResourceData
{
    [WirePath("properties")]
    internal AccountProperties Properties { get; set; }
}
```

But the generator still emits a public factory method:
```csharp
// Generated - won't compile because AccountProperties is internal
public static NewRelicAccountResourceData NewRelicAccountResourceData(
    ResourceIdentifier id, string name, ResourceType resourceType,
    SystemData systemData, AccountProperties properties) // <-- internal type exposed publicly
```

## Expected Behavior

The generator should **not** emit public model factory methods where any parameter type is `internal`. It should either:
1. Skip factory methods entirely when a parameter type is internal, or
2. Generate the flattened version only (which it also does, but without default parameter values — see secondary issue below)

## Secondary Issue

The generated flattened factory methods (e.g. with individual `string organizationId, string accountId, ...\ parameters) are emitted **without default parameter values**, unlike other factory methods. This forces SDK authors to suppress those too and provide custom overloads with defaults to maintain API compatibility.

## Workaround

Use `CodeGenSuppress` on the model factory class:
```csharp
[CodeGenSuppress("NewRelicAccountResourceData", typeof(ResourceIdentifier), typeof(string), typeof(ResourceType), typeof(SystemData), typeof(AccountProperties))]
public static partial class ArmNewRelicObservabilityModelFactory { ... }
```

## Affected Component

`eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/ModelFactoryVisitor.cs`

### PR DESCRIPTION
**Pull request by live1206**
## Fix FlattenPropertyVisitor to use name-based matching for custom code overrides

Fixes #57525

### Problem

When custom code overrides a flattened property (e.g. to add backward-compatible setters), the `PropertyProvider` instance from `CustomCodeView` differs from the one cached in `OutputFlattenPropertyMap`. The `Contains` check at line 524 of `FlattenPropertyVisitor.cs` used **reference equality**, causing flatten detection to fail silently.

This resulted in the generator emitting public factory methods with internal type parameters (`AccountProperties`, `OrganizationProperties`, `PlanDataProperties`), producing **CS0051** compilation errors. SDK authors had to work around this with `CodeGenSuppress` attributes on the model factory.

### Root Cause

`OutputFlattenPropertyMap` is built via `TypeFactory.CreateProperty()`, which caches `PropertyProvider` instances by input property. When custom code overrides the same property in a partial class, the model's `CustomCodeView.Properties` contains a **different object** than the cached one. The `HashSet<PropertyProvider>.Contains()` check (default reference equality) fails, so the property is not recognized as a flatten target.

### Fix

Changed the `Contains` check to **name-based matching**:

`csharp
// Before (reference equality — fails with custom code overrides)
propertiesToFlatten.Contains(internalProperty)

// After (name-based matching — works regardless of property source)
propertiesToFlatten.Any(p => p.Name == internalProperty.Name)
`

### Validation

- Removed the `CodeGenSuppress` workaround from `NewRelicObservability`'s custom model factory
- Regenerated the SDK using `RegenSdkLocal.ps1` with the local generator fix
- Build passes without any CS0051 errors

### CODE REVIEW

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/FlattenPropertyVisitor.cs [hunk 1]
```diff
@@ -521,7 +521,10 @@ private void FlattenModel(ModelProvider model)
                 var innerProperties = PropertyHelpers.GetAllProperties(modelProvider);
 
                 // handle `@flattenProperty`
-                if (ManagementClientGenerator.Instance.OutputLibrary.OutputFlattenPropertyMap.TryGetValue(model, out var propertiesToFlatten) && propertiesToFlatten.Contains(internalProperty))
+                // Use name-based matching instead of reference equality because custom code
+                // may override the property, creating a different PropertyProvider instance
+                // than the one cached in OutputFlattenPropertyMap.
+                if (ManagementClientGenerator.Instance.OutputLibrary.OutputFlattenPropertyMap.TryGetValue(model, out var propertiesToFlatten) && propertiesToFlatten.Any(p => p.Name == internalProperty.Name))
```
Comment (live1206) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/FlattenPropertyVisitor.cs:527]: verified the fix in https://github.com/Azure/azure-sdk-for-net/blob/01fb4a7daa17c5855f5a4b750327f02be28deb9a/sdk/newrelicobservability/Azure.ResourceManager.NewRelicObservability/src/Custom/Models/ArmNewRelicObservabilityModelFactory.cs#L20-L22, we can remove the workaround suppression

**Review by ArcturusZhang — APPROVED** [review]
