### PR TITLE
[AppContainers] Fix for issue #42663

### LINKED ISSUE #42663: [BUG] when put resource input empty string, get resource via SDK met "Value cannot be an empty string. (Parameter 'resourceId')" error
### Library name and version

Azure.ResourceManager.AppContainers Version=1.1.0-beta.1

### Describe the bug

when PUT containerApp env contains property equal to empty string, then get containerApp env via SDK will fail with error  "Value cannot be an empty string. (Parameter 'resourceId')"

### Expected behavior

SDK get containerApp env succeed.

### Actual behavior

get containerApp env via SDK will fail with error  "Value cannot be an empty string. (Parameter 'resourceId')"

### Reproduction Steps

- PUT containerAPp env with below sample payload
```
https://management.azure.com/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.App/managedEnvironments/xxxx?api-version=2022-10-01

{"location": "eastus2", "tags": null, "properties": {"daprAIInstrumentationKey": null, "vnetConfiguration": {"infrastructureSubnetId": "", "runtimeSubnetId": "", "internal": false}, "appLogsConfiguration": {"destination": "log-analytics", "logAnalyticsConfiguration": {"customerId": "xxxxx", "sharedKey": "xxxxx"}}, "customDomainConfiguration": null, "workloadProfiles": null, "InfrastructureResourceGroup": null, "zoneRedundant": false}}

```

- Get via SDK
```
ContainerAppManagedEnvironmentResource env = client.GetContainerAppManagedEnvironmentResource(envId);
```

response with stacktrace
```
System.ArgumentException: Value cannot be an empty string. (Parameter 'resourceId')
   at Azure.Core.Argument.AssertNotNullOrEmpty(String value, String name)
   at Azure.Core.ResourceIdentifier..ctor(String resourceId)
   at Azure.ResourceManager.AppContainers.Models.ContainerAppVnetConfiguration.DeserializeContainerAppVnetConfiguration(JsonElement element)
   at Azure.ResourceManager.AppContainers.ContainerAppManagedEnvironmentData.DeserializeContainerAppManagedEnvironmentData(JsonElement element)
   at Azure.ResourceManager.AppContainers.ManagedEnvironmentsRestOperations.GetAsync(String subscriptionId, String resourceGroupName, String environmentName, CancellationToken cancellationToken)
   at Azure.ResourceManager.AppContainers.ContainerAppManagedEnvironmentResource.GetAsync(CancellationToken cancellationToken)
```

### Environment

_No response_

### PR DESCRIPTION
**Pull request by melina5656**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/42663.
Modify the deserialization method of ContainerAppVnetConfiguration to prompt that infrastructureSubnetId cannot be empty or null.

### CODE REVIEW

**Comment by melina5656** [comment]
This is a fix PR for issue: #42663

File: sdk/containerapps/Azure.ResourceManager.AppContainers/src/Custom/Models/ContainerAppVnetConfiguration.Serialization.cs [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+        [MethodImpl(MethodImplOptions.AggressiveInlining)]
+        internal static void DeserializeInfrastructureSubnetIdValue(JsonProperty property, ref ResourceIdentifier infrastructureSubnetId)
+        {
+            if (property.Value.ValueKind != JsonValueKind.Null && !string.IsNullOrEmpty(property.Value.GetString()))
+            {
+                infrastructureSubnetId = new ResourceIdentifier(property.Value.GetString());
+            }
+            else
+            {
+                throw new ArgumentNullException("infrastructureSubnetId cannot be null or empty.");
```
Comment (ArthurMa1978) [inline sdk/containerapps/Azure.ResourceManager.AppContainers/src/Custom/Models/ContainerAppVnetConfiguration.Serialization.cs:24]: Don't throw exception here otherwise it's still failed when retrieve empty subnet id from service.
And here please try using `models-to-treat-empty-string-as-null`

Comment (melina5656) [reply sdk/containerapps/Azure.ResourceManager.AppContainers/src/Custom/Models/ContainerAppVnetConfiguration.Serialization.cs]: Resolved

File: sdk/containerapps/Azure.ResourceManager.AppContainers/src/Custom/Models/ContainerAppVnetConfiguration.Serialization.cs [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+    [CodeGenSerialization(nameof(InfrastructureSubnetId), DeserializationValueHook = nameof(DeserializeInfrastructureSubnetIdValue))]
+    public partial class ContainerAppVnetConfiguration : IUtf8JsonSerializable, IJsonModel<ContainerAppVnetConfiguration>
+    {
+        [MethodImpl(MethodImplOptions.AggressiveInlining)]
+        internal static void DeserializeInfrastructureSubnetIdValue(JsonProperty property, ref ResourceIdentifier infrastructureSubnetId)
+        {
+            if (property.Value.ValueKind != JsonValueKind.Null && !string.IsNullOrEmpty(property.Value.GetString()))
+            {
+                infrastructureSubnetId = new ResourceIdentifier(property.Value.GetString());
+            }
```
Comment (ArcturusZhang) [inline sdk/containerapps/Azure.ResourceManager.AppContainers/src/Custom/Models/ContainerAppVnetConfiguration.Serialization.cs:21]: we could introduce a bit optimization:
```suggestion
            if (property.Value.ValueKind == JsonValueKind.Null)
            	return;
            var str = property.Value.GetString();
            if (!string.IsNullOrEmpty(str))
            {
                infrastructureSubnetId = new ResourceIdentifier(property.Value.GetString());
            }
```

Comment (ArcturusZhang) [reply sdk/containerapps/Azure.ResourceManager.AppContainers/src/Custom/Models/ContainerAppVnetConfiguration.Serialization.cs:21]: Or if there is a method `property.Value.TryGetString()` we could use it to avoid that we call `GetString` twice

**Review by ArcturusZhang — APPROVED** [review]

File: sdk/containerapps/Azure.ResourceManager.AppContainers/src/Custom/Models/ContainerAppVnetConfiguration.Serialization.cs (hunk 2 above)
Comment (melina5656) [reply sdk/containerapps/Azure.ResourceManager.AppContainers/src/Custom/Models/ContainerAppVnetConfiguration.Serialization.cs]: It seems that there is no method `property.Value.TryGetString()`.
