### PR TITLE
[MPG Generator] Fix paging action resource wrapping to check shared data types

### LINKED ISSUE #57110: [MPG C# Generator] Paging action operations should not resource-wrap return types
## Bug Description

The MPG C# generator incorrectly wraps paging results in resource types for **action** operations. When a paging operation is an ARM **action** (not a list), the generator should return the raw data type (e.g., `Pageable<ServerConfigurationData>`), not the resource-wrapped type (e.g., `Pageable<NodeConfigurationResource>`).

**Example TypeSpec:** [ServerConfiguration.tsp](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresqlhsc/resource-manager/Microsoft.DBforPostgreSQL/PostgresqlHsc/ServerConfiguration.tsp) — the `listByServer` operation is an `ArmResourceActionSync` (action on `ClusterServer`), not a resource list on `ServerConfiguration`.

## tspCodeModel evidence

The emitter correctly identifies the operation as an **Action** in the resource metadata:

```json
{
    "methodId": "Microsoft.DBforPostgreSQL.Configurations.listByServer",
    "kind": "Action",
    "operationPath": ".../{clusterName}/servers/{serverName}/configurations",
    "resourceScope": ".../{clusterName}/servers/{serverName}"
}
```

However, the method-level metadata only says `kind: "paging"` — the Action vs List distinction is only in the resource operation metadata.

## Expected behavior

Since the operation is an **Action** (not a **List**), the generated method should return:

```csharp
public virtual Pageable<CosmosDBForPostgreSqlServerConfigurationData> GetConfigurations(...)
```

## Actual behavior

The generator sees the `paging` kind + a matching `NodeConfigurationResource` class, and produces:

```csharp
public virtual Pageable<CosmosDBForPostgreSqlNodeConfigurationResource> GetConfigurations(...)
```

## Root cause

The generator does not check the ARM resource operation `kind` (Action vs List) when deciding whether to resource-wrap paging results. It only checks the method-level `kind: "paging"` and the existence of a matching resource class.

## Current workaround

Use `CodeGenSuppress` in a `Customized/` file to suppress the generated method and replace it with a hand-written version returning the raw data type.

### PR DESCRIPTION
**Pull request by haiyuazhang**
## Description

Corrects the fix from PR #57112 for issue #57110. The previous fix only skipped resource wrapping for paging action operations. The correct rule is universal across all operation types:

- If the data type is used by **exactly one** resource → wrap to resource type
- If the data type is **shared by multiple resources** → return the raw data type (to avoid arbitrarily picking one resource)

### Approach

The logic is centralized in **ManagementOutputLibrary.TryGetResourceClientProvider** — it now returns alse when the data type is shared by multiple resources. All callers benefit automatically without needing any isResourceAction plumbing.

IsResourceModelType is decoupled from TryGetResourceClientProvider so that namespace transforms still apply correctly to shared data types.

### Changes

| File | Change |
|------|--------|
| ManagementOutputLibrary.cs | Centralized shared-data check in TryGetResourceClientProvider; decoupled IsResourceModelType |
| PageableOperationMethodProvider.cs | Removed isResourceAction param (no longer needed) |
| ResourceClientProvider.cs | Removed isResourceAction plumbing |
| MockableResourceProvider.cs | Removed isResourceAction plumbing |
| PageableOperationMethodProviderTests.cs → ResourceWrappingTests.cs | Replaced with 8 comprehensive tests covering all operation types |

### Testing

- **8 new unit tests** covering paging actions, paging lists, and non-paging actions — each with single-resource (wraps) and shared-data (does not wrap) scenarios
- All **127 tests pass**

### Validation: GuestConfiguration SDK

Validated by regenerating Azure.ResourceManager.GuestConfiguration, which has GuestConfigurationAssignmentData shared by **4 resources** (VM, HCRP, VMSS, VMware vSphere assignments — all representing Microsoft.GuestConfiguration/guestConfigurationAssignments under different parent scopes).

**Before this fix**: The generator arbitrarily wrapped RGList return type to Pageable<GuestConfigurationVmAssignmentResource>, even though the operation returns assignments from all 4 resource types. The SDK had a PageableWrapper customization to undo this and expose Pageable<GuestConfigurationAssignmentData>.

**After this fix**: The generator correctly returns Pageable<GuestConfigurationAssignmentData> directly, since the data type is shared. The PageableWrapper workaround in the customization can be simplified to a direct pass-through.

Fixes #57110

> **Note:** This PR was authored with GitHub Copilot.

### CODE REVIEW

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/OperationMethodProviders/PageableOperationMethodProvider.cs [hunk 1]
```diff
@@ -85,6 +81,14 @@ private static void InitializeTypeInfo(
             }
             else if (ManagementClientGenerator.Instance.OutputLibrary.TryGetResourceClientProvider(itemType, out resourceClient))
             {
+                // For action operations, only wrap when the data type is exclusively used by one resource.
+                // When multiple resources share the same data type, wrapping would pick an arbitrary resource,
+                // so we skip wrapping and return the raw data type instead.
+                if (isResourceAction && ManagementClientGenerator.Instance.OutputLibrary.IsDataTypeSharedByMultipleResources(itemType))
```
Comment (ArcturusZhang) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/OperationMethodProviders/PageableOperationMethodProvider.cs]: I think it is not for just resource actions.
For any operation, if it is returning a data corresponding to one single resource, we should wrap. if it is returning a data corresponding to multiple, we should not wrap.

Comment (ArcturusZhang) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/OperationMethodProviders/PageableOperationMethodProvider.cs]: and I think the bug is in this operation: `TryGetResourceClientProvider`
this method itself should track if the `itemType` corresponds to multiple resources, if so, we should not add it into the dictionary in the first place.

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/ManagementOutputLibrary.cs [hunk 2]
```diff
@@ -434,26 +434,60 @@ private void ProcessLroMethod(InputServiceMethod inputMethod, Dictionary<CSharpT
             }
         }
 
-        internal bool IsResourceModelType(CSharpType type) => TryGetResourceClientProvider(type, out _);
+        internal bool IsResourceModelType(CSharpType type) => GetResourceDataTypes().ContainsKey(type);
 
         private IReadOnlyDictionary<CSharpType, ResourceClientProvider>? _resourceDataTypes;
-        internal bool TryGetResourceClientProvider(CSharpType resourceDataType, [MaybeNullWhen(false)] out ResourceClientProvider resourceClientProvider)
+        private IReadOnlyDictionary<CSharpType, ResourceClientProvider> GetResourceDataTypes()
```
Comment (ArcturusZhang) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/ManagementOutputLibrary.cs]: would it be more valuable if this dictionary would track `CSharpType` -> `List<ResourceClientProvider>`?
then we could remove the method `IsDataTypeSharedByMultipleResources` because its implementation is not very sufficient and has a risk of causing stack overflow.

Comment (haiyuazhang) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/ManagementOutputLibrary.cs]: updated

**Review by ArcturusZhang — APPROVED** [review]
