### PR TITLE
Fix for API version cache

### LINKED ISSUE #34973: [BUG] InvalidOperationException thrown while set API version in ArmClientOption
### Library name and version

Azure.ResrouceManager 1.4.0

### Describe the bug

When user sets Api version for specific resource type like below:
options.SetApiVersion(new ResourceType("Microsoft.Compute/test"), "2022-09-01");

It throws `InvalidOperationException` while creating GenericResource for "Microsoft.Compute/availabilitySets"

### Expected behavior

The GenericResource creation should not throw

### Actual behavior

It throws `InvalidOperationException` while creating GenericResource for "Microsoft.Compute/availabilitySets"

### Reproduction Steps

options.SetApiVersion(new ResourceType("Microsoft.Compute/test"), "2022-09-01");

Then create a generic resource for "Microsoft.Compute/availabilitySets"

### Environment

_No response_

### PR DESCRIPTION
**Pull request by live1206**
Fix for #34973 
Right now, we are combining [`ApiVersionOverrides`](https://github.com/Azure/azure-sdk-for-net/blob/2cea55dfc84bad74826ca7e531f36c5f89e0c957/sdk/resourcemanager/Azure.ResourceManager/src/ArmClient.cs#L30) into [`ResourceApiVersionCache`](https://github.com/Azure/azure-sdk-for-net/blob/2cea55dfc84bad74826ca7e531f36c5f89e0c957/sdk/resourcemanager/Azure.ResourceManager/src/ArmClient.cs#L31) before fetching from remote. 
Since the key of `ResourceApiVersionCache` is namespace of the resource type, even we only set API versions for a small portion of the namespace, we will not fetch from remote anymore. Then there will be resource types missing from the specified namespace.

Change the behavior to search in `ApiVersionOverrides` firstly, if not found fetch from remote and store into `ResourceApiVersionCache`.

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

File: sdk/resourcemanager/Azure.ResourceManager/tests/Scenario/ArmClientTests.cs [hunk 1]
```diff
@@ -203,7 +203,7 @@ public async Task GetUsedResourceApiVersionWithOverride()
             var subscription = await client.GetDefaultSubscriptionAsync();
             var version = await subscription.GetResourceProviders().GetApiVersionAsync(computeResourceType);
             Assert.AreEqual(expectedVersion, version);
-            Assert.AreEqual(0, policy.GetCount("Microsoft.Compute"));
+            Assert.AreEqual(1, policy.GetCount("Microsoft.Compute"));
```
Comment (live1206) [inline sdk/resourcemanager/Azure.ResourceManager/tests/Scenario/ArmClientTests.cs:206]: After the change, there will be one more API request to fetch API versions for `Microsoft.Compute`

File: sdk/resourcemanager/Azure.ResourceManager/tests/SessionRecords/ArmClientTests/GetUsedResourceApiVersionWithOverride.json [hunk 2]
```diff
@@ -55,15 +55,6320 @@
         }
       }
     },
+    {
+      "RequestUri": "https://management.azure.com/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/providers/Microsoft.Compute?api-version=2022-09-01",
```
Comment (live1206) [inline sdk/resourcemanager/Azure.ResourceManager/tests/SessionRecords/ArmClientTests/GetUsedResourceApiVersionWithOverride.json:59]: After the change, 1 more API call to fetch API versions for the namespace. Same as the other change of recordings.

**Comment by live1206** [comment]
@m-nash Could you help to review this fix? Thanks!

File: sdk/resourcemanager/Azure.ResourceManager/src/ArmClient.cs [hunk 3]
```diff
@@ -114,12 +113,6 @@ private void CopyApiVersionOverrides(ArmClientOptions options)
             foreach (var keyValuePair in options.ResourceApiVersionOverrides)
             {
                 ApiVersionOverrides.Add(keyValuePair.Key, keyValuePair.Value);
-                if (!ResourceApiVersionCache.TryGetValue(keyValuePair.Key.Namespace, out var apiVersionCache))
-                {
-                    apiVersionCache = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
-                    ResourceApiVersionCache.TryAdd(keyValuePair.Key.Namespace, apiVersionCache);
```
Comment (archerzz) [inline sdk/resourcemanager/Azure.ResourceManager/src/ArmClient.cs:120]: What's the impact if `ResourceApiVersionCache` is not updated here?

File: sdk/resourcemanager/Azure.ResourceManager/tests/Scenario/ArmClientTests.cs (hunk 1 above)
Comment (archerzz) [reply sdk/resourcemanager/Azure.ResourceManager/tests/Scenario/ArmClientTests.cs:206]: Can this be avoided (in some cases)?

Comment (live1206) [reply sdk/resourcemanager/Azure.ResourceManager/tests/Scenario/ArmClientTests.cs:206]: Yes, it can if the required resource type is in the override already.

File: sdk/resourcemanager/Azure.ResourceManager/src/ArmClient.cs (hunk 3 above)
Comment (live1206) [reply sdk/resourcemanager/Azure.ResourceManager/src/ArmClient.cs:120]: More details can be found in the PR description, instead of updating `ResourceApiVersionCache` here which is before fetching from remote, we should update it after fetching from remote.

**Review by m-nash — APPROVED** [review]
