### PR TITLE
[EventHubs] Distributed Tracing: Do not populate schema in peer.address attribute (Track Two)

### LINKED ISSUE #9631: Distributed tracing for Event Hub: do not populate schema in peer.address attribute
**Describe the bug**
Azure SDKs for EventHub populate peer.adress (EventHub endpoint) inconsistently using different schemas (or no schemas). 

**Expected behavior**
Assuming schema is an implementation detail and not particularly important for tracing, let's stop populating schema everywhere. I.e. use FQDN instead of endpoint (e.g. azuresdkdemo.servicebus.windows.net)

**Actual behavior (include Exception or Stack Trace)**
Example: 
- .NET: amqps://azuresdkdemo.servicebus.windows.net
- JS: sb://azuresdkdemo.servicebus.windows.net
- Python: azuresdkdemo.servicebus.windows.net
- Java: azuresdkdemo.servicebus.windows.net

**To Reproduce**
1. Send message to EventHub with  EventHubProducerClient.Send
2. enable tracing and capture traces using ApplicationInsights or OpenTelemetry 

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.EventHubs 5.0.0.
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): any
 - IDE and version : any

### PR DESCRIPTION
**Pull request by kinelski**
Fixes #9631.

Simplified the diagnostics test file a bit because we don't need a `Uri` anymore.

### CODE REVIEW

File: sdk/eventhub/Azure.Messaging.EventHubs/tests/Diagnostics/DiagnosticsTests.cs [hunk 1]
```diff
@@ -237,28 +237,17 @@ public async Task EventHubProducerAppliesDiagnosticIdToEventsOnBatchSend()
...
         private class MockConnection : EventHubConnection
         {
-            private const string MockConnectionString = "Endpoint=value.com;SharedAccessKeyName=[value];SharedAccessKey=[value];";
-            private Uri _serviceEndpoint;
+            private const string MockConnectionStringFormat = "Endpoint={0};SharedAccessKeyName=[value];SharedAccessKey=[value];";
 
-            public MockConnection(Uri serviceEndpoint,
-                                  string eventHubName) : base(MockConnectionString, eventHubName)
+            public MockConnection(string serviceEndpoint,
+                                  string eventHubName) : base(String.Format(MockConnectionStringFormat, serviceEndpoint), eventHubName)
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs/tests/Diagnostics/DiagnosticsTests.cs]: nit:  `string.Format`

**Review by jsquire — APPROVED** [review]
LGTM

**Review by pakrym — APPROVED** [review]
