### PR TITLE
fix the array/object type output parameter issue

### LINKED ISSUE #52458: [Provisioning] Output parameter with type of an array or dictionary cannot properly compile
If we do this:
```
ProvisioningOutput result = new(nameof(result), typeof(IEnumerable))
{
    Value = new IdentifierExpression(ipArray.BicepIdentifier)
};
infra.Add(result);
```
or use any other types as the type here, we will always get an error:
```
System.NotSupportedException : Failed to automatically map System.Collections.IEnumerable into a TypeExpression.  Please explicitly choose a primitive type like bool, int, string, object, array, etc.
```

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/52458

### CODE REVIEW

File: sdk/provisioning/Azure.Provisioning/tests/Infrastructure/InfrastructureTests.cs [hunk 1]
```diff
@@ -2,7 +2,10 @@
 // Licensed under the MIT License.
 
 using System;
+using System.Collections;
```
Comment (m-nash) [inline sdk/provisioning/Azure.Provisioning/tests/Infrastructure/InfrastructureTests.cs]: are these needed?

File: sdk/provisioning/Azure.Provisioning/tests/Primitives/ProvisioningOutputTests.cs [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+// Licensed under the MIT License.
+
+using System.Collections.Generic;
+using System.Threading.Tasks;
+using Azure.Provisioning.Expressions;
+using NUnit.Framework;
+
+namespace Azure.Provisioning.Tests.Primitives;
+
+public class ProvisioningOutputTests
```
Comment (m-nash) [inline sdk/provisioning/Azure.Provisioning/tests/Primitives/ProvisioningOutputTests.cs:12]: Is there some tests that validate the enum change?

Comment (ArcturusZhang) [reply sdk/provisioning/Azure.Provisioning/tests/Primitives/ProvisioningOutputTests.cs:12]: let me add one.

**Comment by ArcturusZhang** [comment]
Hey @m-nash I updated the PR with a new test using the enum type, could you take another review?

File: sdk/provisioning/Azure.Provisioning/tests/Primitives/ProvisioningOutputTests.cs (hunk 2 above)
Comment (ArcturusZhang) [reply sdk/provisioning/Azure.Provisioning/tests/Primitives/ProvisioningOutputTests.cs:12]: test added

**Review by m-nash — APPROVED** [review]
