### PR TITLE
Addressed Error for Events Missing Required Fields  

### LINKED ISSUE #15062: Partial events deserialize but don't return data.
```
EventGridEvent.Parse(@"{""data"":""""}").Single().GetData<string>();
```

Would fail with the argument null exception during GetData call

Related to: https://github.com/Azure/azure-sdk-for-net/pull/15058
cc @ellismg

### PR DESCRIPTION
**Pull request by kerri-lee**
Should throw an `ArgumentNullException` if required fields for `EventGridEvent` are missing when `EventGridEvent.Parse` is called (matches the behavior for CloudEvents). Before, no error would be thrown (and would throw an error when trying to access event data).

### CODE REVIEW

**Comment by JoshLove-msft** [comment]
Can we add a test for this?

File: sdk/eventgrid/Azure.Messaging.EventGrid/src/Customization/CloudEvent.cs [hunk 1]
```diff
@@ -85,6 +85,18 @@ public CloudEvent(string source, string type, BinaryData data, string dataConten
...
+        {
+            Argument.AssertNotNull(id, nameof(id));
+            Argument.AssertNotNull(source, nameof(source));
+            Argument.AssertNotNull(type, nameof(type));
+
+            Id = id;
+            Source = source;
+            Type = type;
+            ExtensionAttributes = new Dictionary<string, object>();
+        }
```
Comment (kerri-lee) [inline sdk/eventgrid/Azure.Messaging.EventGrid/src/Customization/CloudEvent.cs:98]: I made this constructor private because the publishing tests started calling this constructor rather than `CloudEvent(string source, string type, object data)`, but that means that the BinaryData extension method `ToCloudEvent` can't call this constructor, so it won't throw an error if `Id` is null. I wasn't really sure how to approach this problem without changing all of the CloudEvent tests.

Comment (JoshLove-msft) [reply sdk/eventgrid/Azure.Messaging.EventGrid/src/Customization/CloudEvent.cs:98]: why does the other constructor not have an Id param?

Comment (kerri-lee) [reply sdk/eventgrid/Azure.Messaging.EventGrid/src/Customization/CloudEvent.cs:98]: We set the id by default

Comment (JoshLove-msft) [reply sdk/eventgrid/Azure.Messaging.EventGrid/src/Customization/CloudEvent.cs]: ah ok, I think we were going to remove the extension methods anyway.

Comment (kerri-lee) [reply sdk/eventgrid/Azure.Messaging.EventGrid/src/Customization/CloudEvent.cs]: Nvm I just changed the constructor to accept all of the CloudEvent properties so it wouldn't conflict with the other constructor

Comment (kerri-lee) [reply sdk/eventgrid/Azure.Messaging.EventGrid/src/Customization/CloudEvent.cs]: Oh in that case, should I just remove them now?

Comment (JoshLove-msft) [reply sdk/eventgrid/Azure.Messaging.EventGrid/src/Customization/CloudEvent.cs]: I think so.

Comment (JoshLove-msft) [reply sdk/eventgrid/Azure.Messaging.EventGrid/src/Customization/CloudEvent.cs]: That's fine too. We can address it later if you are unblocked.

**Review by JoshLove-msft — APPROVED** [review]
