### PR TITLE
[CodeGen] Fix: Ensure output directory exists before writing metadata.json

### LINKED ISSUE #10036: [Bug]: http-client-csharp throw error is no `metadata.json` file exists
### Describe the bug

Image

Text from the image:
```
Error: ENOENT: no such file or directory, open 'C:\w\typespec-azure\tmp\tsp-output\TestService\metadata.json'
    at open (node:internal/fs/promises:639:25)
    at writeFile (node:internal/fs/promises:1213:14)
    at generateMetadataFile (file:///C:/w/typespec-azure/tmp/node_modules/@azure-typespec/http-client-csharp/emitter/src/emitter.ts:96:3)
    at Object.$onEmit [as emitFunction] (file:///C:/w/typespec-azure/tmp/node_modules/@azure-typespec/http-client-csharp/emitter/src/emitter.ts:39:3)
    at runEmitter (file:///C:/w/typespec-azure/tmp/node_modules/@typespec/compiler/src/core/program.ts:1007:5)
    at file:///C:/w/typespec-azure/tmp/node_modules/@typespec/compiler/src/core/program.ts:979:33
    at trackAction (file:///C:/w/typespec-azure/tmp/node_modules/@typespec/compiler/src/core/logger/console-sink.ts:188:20)
    at emit (file:///C:/w/typespec-azure/tmp/node_modules/@typespec/compiler/src/core/program.ts:977:10)
    at compile (file:///C:/w/typespec-azure/tmp/node_modules/@typespec/compiler/src/core/program.ts:195:26)
    at compileOne (file:///C:/w/typespec-azure/tmp/node_modules/@typespec/compiler/src/core/cli/actions/compile/compile.ts:71:21)
```

### Reproduction

Run `tsp compile . --emit @azure-typespec/http-client-csharp` without `metadata.json` file under output folder will get the above error. If add an empty `metadata.json` file, it could emit the code.

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by JonathanCrd**
## Problem

The Azure C# emitter crashes with \ENOENT: no such file or directory\ when running \	sp compile\ if the output directory does not already exist. This happens because \generateMetadataFile\ calls \writeFile\ without first ensuring the target directory exists.

Fixes: https://github.com/microsoft/typespec/issues/10036

## Solution

- Call \context.program.host.mkdirp(context.emitterOutputDir)\ before \writeFile\ to create the output directory if it doesn't exist.
- Wrap the directory creation and file write in a try-catch that reports a clear TypeSpec diagnostic (\metadata-file-write-error\) instead of crashing with a raw Node.js error.

## Changes

| File | Change |
|------|--------|
| \mitter/src/emitter.ts\ | Added \mkdirp\ call + try-catch with diagnostic reporting |
| \mitter/src/lib/lib.ts\ | Added \metadata-file-write-error\ diagnostic definition |
| \mitter/test/Unit/metadata.test.ts\ | Added 2 tests: mkdirp call order verification, error handling |

## Validation

- ✅ All 5 metadata tests pass
- ✅ Lint passes (0 warnings)
- ✅ Prettier passes

---

🤖 Made with JonathanCrd's copilot

### CODE REVIEW

File: eng/packages/http-client-csharp/emitter/src/emitter.ts [hunk 1]
```diff
@@ -125,8 +125,20 @@ async function generateMetadataFile(
   };
 
   const outputPath = resolvePath(context.emitterOutputDir, "metadata.json");
-  await context.program.host.writeFile(
-    outputPath,
-    JSON.stringify(metadata, null, 2)
-  );
+  try {
```
Comment (JoshLove-msft) [inline eng/packages/http-client-csharp/emitter/src/emitter.ts]: I don't think we need to try/catch creating a directory. If this fails, then there is something very wrong with the environment and we can't continue.

**Review by JoshLove-msft — APPROVED** [review]
