### PR TITLE
Fix the string interpolation issue

### LINKED ISSUE #48493: [BUG] Bicep Expressions don't work in Interpolated strings
### Library name and version

Azure.Provisioning

### Describe the bug

When trying to use an expression in an interpolated string, the expression doesn't get interpolated correctly.

### Expected behavior

The output bicep should look like:

```bicep
output connectionString string = 'Endpoint=${ai.properties.endpoints['Azure AI Model Inference API']}'
```

### Actual behavior

```bicep
output connectionString string = 'Endpoint=ai.properties.endpoints[\'Azure AI Model Inference API\']'
```

### Reproduction Steps

```C#
using Azure.Provisioning;
using Azure.Provisioning.CognitiveServices;
using Azure.Provisioning.Expressions;

CognitiveServicesAccount ai = new(nameof(ai));

Infrastructure infra = new();
infra.Add(ai);

var inferenceEndpoint = new IndexExpression(
    (BicepExpression)ai.Properties.Endpoints!,
    "Azure AI Model Inference API");
infra.Add(new ProvisioningOutput("connectionString", typeof(string))
{
    Value = Interpolate($"Endpoint={inferenceEndpoint}")
});

ProvisioningPlan plan = infra.Build();
string bicep = plan.Compile().First().Value;
Console.WriteLine(bicep);
```

NOTE: If I cast the `IndexExpression` to a `BicepValue<string>` explicitly, then it does produce the right bicep.

```C#
var inferenceEndpoint = (BicepValue<string>)new IndexExpression(
    (BicepExpression)ai.Properties.Endpoints!,
    "Azure AI Model Inference API");
infra.Add(new ProvisioningOutput("connectionString", typeof(string))
{
    Value = Interpolate($"Endpoint={inferenceEndpoint}")
});
```

### Environment

cc @tg-msft @m-nash

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/48493
and introduce a few test cases for `BicepFunction.Interpolate`

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

File: sdk/provisioning/Azure.Provisioning/tests/Expressions/InterpolatedStringExpressionTest.cs [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+
+            // test index expression in interpolation
+            yield return new TestCaseData(
+                BicepFunction.Interpolate(
+                    $"Endpoint={new IndexExpression(
+                        new IdentifierExpression("foo"),
+                        new StringLiteralExpression("bar")
+                    )}"))
+                .Returns("'Endpoint=${foo['bar']}'");
+        }
```
Comment (tg-msft) [inline sdk/provisioning/Azure.Provisioning/tests/Expressions/InterpolatedStringExpressionTest.cs:35]: Style nit - I generally avoid TestCaseSource like this because it makes it harder to debug when something fails.  Sometimes it can be worth it if you have _a lot_ of test data, but in this case I don't think there's too much repetition with just:

```suggestion
    [Test]
    public void ValidateBicepFunctionInterpolate()
    {
        // test provisionable variable
        Assert.AreEqual(
            "'Var=${foo}'",
            BicepFunction.Interpolate($"Var={new ProvisioningVariable("foo", typeof(string))}").ToString());

        // test index expression in interpolation
        Assert.AreEqual(
            "'Endpoint=${foo['bar']}'",
            BicepFunction.Interpolate($"Endpoint={
                new IndexExpression(
                    new IdentifierExpression("foo"),
                    "bar")
                }").ToString());
    }
```

**Review by tg-msft — APPROVED** [review]
The change looks good!
