### PR TITLE
Relax entity name validation for the case of a pre-formatted subscription path

### LINKED ISSUE #26837: [BUG] Service Bus Extensions: Potential issue with entity path for subscriptions
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.1

### Describe the bug

I have created a web job function for service bus topic trigger ,as I obtain the connection string from azure (the connection string will contain a entity path).

I have looked into the source code of service bus and found out, during the `ServiceBusTriggerAttributeBindingProvider` is creating `ServiceBusListener`, it is using `EntityNameFormatter.FormatSubscriptionPath(topicName, subscriptionName)` to build a entity path in a format of "{topic-name}/Subscription/{subscription-name}"

so I trace it back to this method `CreateBatchMessageReceiver()` is having the issue, when it is creating the `client.CreateReceiver(entityPath, options))`, 

if you look at the override of that method, it treats the `entitypath` as queue name.

Shouldn't it be using 

`CreateReceiver(string topicName, string subscriptionName, ServiceBusReceiverOptions options);`

### Expected behavior

`CreateReceiver(string topicName, string subscriptionName, ServiceBusReceiverOptions options);`

### Actual behavior

`CreateReceiver(string queueName, ServiceBusReceiverOptions options);`

### Reproduction Steps

as described in the description

### Environment

windows 10, dotnet 6

### PR DESCRIPTION
**Pull request by JoshLove-msft**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/26837

### CODE REVIEW

File: sdk/servicebus/Azure.Messaging.ServiceBus/tests/Client/ServiceBusClientTests.cs [hunk 1]
```diff
@@ -406,6 +406,37 @@ public void ValidateClientProperties()
...
+        [TestCase("queue1", "Endpoint=sb://not-real.servicebus.windows.net/;SharedAccessKeyName=DummyKey;SharedAccessKey=[not_real];EntityPath=queue1")]
+        [TestCase("queue1", "Endpoint=sb://not-real.servicebus.windows.net/;SharedAccessKeyName=DummyKey;SharedAccessKey=[not_real];")]
+        [TestCase("topic1", "Endpoint=sb://not-real.servicebus.windows.net/;SharedAccessKeyName=DummyKey;SharedAccessKey=[not_real];")]
+        [TestCase("topic1/Subscriptions/sub1", "Endpoint=sb://not-real.servicebus.windows.net/;SharedAccessKeyName=DummyKey;SharedAccessKey=[not_real];")]
+        [TestCase("topic1/Subscriptions/sub1", "Endpoint=sb://not-real.servicebus.windows.net/;SharedAccessKeyName=DummyKey;SharedAccessKey=[not_real];EntityPath=topic1")]
+        [TestCase("topic1/Subscriptions/sub1", "Endpoint=sb://not-real.servicebus.windows.net/;SharedAccessKeyName=DummyKey;SharedAccessKey=[not_real];EntityPath=topic1/Subscriptions/sub1")]
+        public void ValidateEntityNameAllowsValidPaths(string entityName, string connectionString)
+        {
+            var client = new ServiceBusClient(connectionString);
+            client.ValidateEntityName(entityName);
```
Comment (jsquire) [inline sdk/servicebus/Azure.Messaging.ServiceBus/tests/Client/ServiceBusClientTests.cs:419]:
```suggestion
            Assert.That(
                () => client.ValidateEntityName(entityName), 
                Throws.Nothing);
```
Functionally the same, but I believe this better conveys the intent to validate there isn't an exception.   Without the assert, I always ask myself if we forgot to finish implementing.

**Review by jsquire — APPROVED** [review]
