### PR TITLE
Fix stack overflow in management generator for discriminated Resource models

### LINKED ISSUE #56505: Autorest Code Generation Failure Caused by request-path-is-non-resource Misclassification Leading to Memory Overflow
In `autorest`, there is a definition of `request-path-is-non-resource`, and an error occurred during the generation process. Here is a partial error log.

Image

The following code added in the "client" can solve the memory overflow problem shown in the screenshot

``` typescript
@@alternateType(UsageDetail, ConsumptionUsageDetail, "csharp");
@@alternateType(ChargeSummary, ConsumptionChargeSummary, "csharp");

/**
 * An usage detail resource.
 */
@discriminator("kind")
model ConsumptionUsageDetail {
  ...Azure.ResourceManager.Foundations.Resource;

  /**
   * Specifies the kind of usage details.
   */
  kind: UsageDetailsKind;

  /**
   * The etag for the resource.
   */
  @visibility(Lifecycle.Read)
  etag?: Azure.Core.EtagProperty.etag;

  /**
   * Resource tags.
   */
  #suppress "@azure-tools/typespec-azure-resource-manager/arm-no-record" "FIXME: Update justification, follow aka.ms/tsp/conversion-fix for details"
  @visibility(Lifecycle.Read)
  tags?: Record<string>;
}

/**
 * A charge summary resource.
 */
@discriminator("kind")
model ConsumptionChargeSummary {
  ...Azure.ResourceManager.Foundations.ProxyResource;

  /**
   * Specifies the kind of charge summary.
   */
  kind: ChargeSummaryKind;

  /**
   * eTag of the resource. To handle concurrent update scenario, this field will be used to determine whether the user is updating the latest version or not.
   */
  eTag?: Azure.Core.EtagProperty.etag;
}
```

### PR DESCRIPTION
**Pull request by live1206**
### Issue
Fixes #56505

### Root Cause
When a discriminated model (e.g., `UsageDetail` with `@discriminator`) extends an ARM `Resource`/`ProxyResource` type, the `InheritableSystemObjectModelVisitor`'s `UpdateSerialization` method accesses `serializationTypeDefinition.Methods` during `PreVisitModel`. This triggers lazy building of `DerivedModels`, which calls `TypeFactory.CreateModel` for derived types. Those derived types need the base model (via `BaseModelProvider`), but the base model is **not yet cached** in `TypeFactory` since `PreVisitModel` hasn't returned yet. This creates an infinite recursion cycle:

```
CreateModel(UsageDetail) -> PreVisitModel -> Update -> UpdateSerialization
  -> .Methods -> BuildDerivedModels -> CreateModel(LegacyUsageDetail)
    -> constructor needs BaseModelProvider -> CreateModel(UsageDetail) [NOT CACHED]
      -> PreVisitModel -> Update -> UpdateSerialization -> ... (infinite)
```

### Fix
Defer `UpdateSerialization` to `VisitType` (called after all models are cached in `TypeFactory`) only for models that have a `DiscriminatorProperty`. Non-discriminated models continue to have their serialization updated immediately during `PreVisitModel` as before, preserving existing behavior.

### Validation
- All 114 existing generator unit tests pass
- `Generate.ps1` regenerates the test project successfully with no regressions
- Verified the fix prevents the stack overflow with a minimal reproduction case (discriminated model extending Resource with derived subtypes)

### CODE REVIEW

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/InheritableSystemObjectModelVisitor.cs [hunk 1]
```diff
@@ -29,7 +29,10 @@ internal class InheritableSystemObjectModelVisitor : ScmLibraryVisitor
 
         if (type is not InheritableSystemObjectModelProvider && type?.BaseModelProvider is InheritableSystemObjectModelProvider baseSystemType)
         {
-            Update(baseSystemType, type);
+            // Defer serialization update for discriminated models to avoid infinite recursion.
+            // Accessing Methods triggers building DerivedModels, which calls CreateModel for
+            // derived types whose base model is not yet cached in TypeFactory during PreVisitModel.
+            Update(baseSystemType, type, deferSerialization: model.DiscriminatorProperty != null);
```
Comment (live1206) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/InheritableSystemObjectModelVisitor.cs:38]: why not always defer the serialization update to keep things in expected order?

Comment (live1206) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Visitors/InheritableSystemObjectModelVisitor.cs:38]: I tried always deferring, but it causes regressions for non-discriminated models (Employee, PrivateLink, etc.) with build errors like `CS0103: 'additionalBinaryDataProperties0' does not exist`.

**Root cause**: `UpdateSerialization` accesses `serializationTypeDefinition.Methods`, which **lazily generates** the serialization code at that moment. The generated code depends on the model's current property/field state. In `Update()`, the serialization must be accessed **before** properties are filtered and `rawDataField` is added (lines below). When deferred to `VisitType`, the model state has already been modified by `Update()` in `PreVisitModel`, so the lazy serialization code is generated with incorrect assumptions.

For discriminated models specifically, accessing `.Methods` during `PreVisitModel` triggers building `DerivedModels` -> `CreateModel` for derived types -> infinite recursion (the original bug). So those **must** defer. But non-discriminated models **must not** defer.

I've added comments in the code explaining this constraint and pushed.

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/InheritableSystemObjectModelProvider.cs [hunk 2]
```diff
@@ -18,11 +18,13 @@ public InheritableSystemObjectModelProvider(Type type, InputModelType inputModel
...
-        protected override string BuildName() => _type.Name;
+        protected override string BuildName() => _type?.Name ?? string.Empty;
 
         protected override string BuildRelativeFilePath()
             => throw new InvalidOperationException("This type should not be writing in generation");
 
-        protected override string BuildNamespace() => _type.Namespace!;
+        // _type may be null when called from base constructor before field assignment.
+        // The visitor's UpdateNamespace corrects this to _type.Namespace after construction.
+        protected override string BuildNamespace() => _type?.Namespace ?? string.Empty;
```
Comment (ArcturusZhang) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/InheritableSystemObjectModelProvider.cs:28]: the process described here looks very problematic.
would the effort of introducing this type into the MTG core library resolve this?

Comment (live1206) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/InheritableSystemObjectModelProvider.cs:28]: That needs quite some refactoring, would prefer a quick fix for this for now.

Comment (live1206) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/InheritableSystemObjectModelProvider.cs:28]: And there is another fix for system base type customization in https://github.com/Azure/azure-sdk-for-net/pull/56634. Again, it is a temp fix.

Comment (live1206) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/InheritableSystemObjectModelProvider.cs:28]: https://github.com/Azure/azure-sdk-for-net/pull/56498 is another fix for this.

**Review by ArcturusZhang — APPROVED** [review]

**Comment by live1206** [comment]
CI got stuck, the previous run passed
