### PR TITLE
Avoid disposing already disposed cancellation token source

### LINKED ISSUE #30553: [ServiceBus] CanUpdateSessionConcurrency failing in nightly runs
ServiceBus nightly test runs are failing with:

> Error message
> System.ObjectDisposedException : The CancellationTokenSource has been disposed.
> 
> 
> Stack trace
>    at System.Threading.CancellationTokenSource.Cancel()
>    at Azure.Messaging.ServiceBus.SessionReceiverManager.CloseReceiver(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\src\Processor\SessionReceiverManager.cs:line 242
>    at Azure.Messaging.ServiceBus.SessionReceiverManager.CloseReceiverIfNeeded(CancellationToken processorCancellationToken, Boolean forceClose) in D:\a\_work\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\src\Processor\SessionReceiverManager.cs:line 174
>    at Azure.Messaging.ServiceBus.ServiceBusProcessor.CloseAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\src\Processor\ServiceBusProcessor.cs:line 1006
>    at Azure.Messaging.ServiceBus.ServiceBusSessionProcessor.CloseAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\src\Processor\ServiceBusSessionProcessor.cs:line 317
>    at Azure.Messaging.ServiceBus.ServiceBusSessionProcessor.DisposeAsync() in D:\a\_work\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\src\Processor\ServiceBusSessionProcessor.cs:line 325
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.CanUpdateSessionConcurrency() in D:\a\_work\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\tests\Processor\SessionProcessorLiveTests.cs:line 2100
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.CanUpdateSessionConcurrency() in D:\a\_work\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\tests\Processor\SessionProcessorLiveTests.cs:line 2100
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.CanUpdateSessionConcurrency() in D:\a\_work\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\tests\Processor\SessionProcessorLiveTests.cs:line 2101
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1780818&view=results

@jsquire for notification.

### PR DESCRIPTION
**Pull request by JoshLove-msft**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/30553

### CODE REVIEW

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs [hunk 1]
```diff
@@ -693,7 +693,9 @@ private void ReconcileReceiverManagers(int maxConcurrentSessions)
                             // but we will track them so that they can be explicitly closed when stopping, just like we do with
                             // _receiverManagers.
                             _orphanedReceiverManagers.Add(_receiverManagers[0]);
-                            ((SessionReceiverManager) _receiverManagers[0]).CancelSession();
+
+                            // these tasks will be awaited when closing the orphaned receivers as part of CloseAsync
+                            _ = ((SessionReceiverManager) _receiverManagers[0]).CancelSessionAsync();
```
Comment (jsquire) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs:698]: Should we consider attaching a `ContinueWith` scoped to exceptions to capture any problems in the logs?

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessSessionEventArgs.cs [hunk 2]
```diff
@@ -139,7 +139,8 @@ public class ProcessSessionEventArgs : EventArgs
         /// </summary>
         public virtual void ReleaseSession() =>
             // manager will be null if instance created using the public constructor which is exposed for testing purposes
-            _manager?.CancelSession();
+            // This will be awaited when closing the receiver.
+            _ = _manager?.CancelSessionAsync();
```
Comment (jsquire) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessSessionEventArgs.cs:143]: Should we consider attaching a `ContinueWith` scoped to exceptions to capture any problems in the logs?

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessSessionMessageEventArgs.cs [hunk 3]
```diff
@@ -231,7 +231,8 @@ await _sessionReceiver.AbandonMessageAsync(message, propertiesToModify, cancella
         /// </summary>
         public virtual void ReleaseSession() =>
             // manager will be null if instance created using the public constructor which is exposed for testing purposes
-            _manager?.CancelSession();
+            // This will be awaited when closing the receiver.
+            _ = _manager?.CancelSessionAsync();
```
Comment (jsquire) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessSessionMessageEventArgs.cs:235]: Should we consider attaching a `ContinueWith` scoped to exceptions to capture any problems in the logs?

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs [hunk 4]
```diff
@@ -410,13 +406,18 @@ protected override async Task RaiseExceptionReceived(ProcessErrorEventArgs event
...
-        internal void CancelSession()
+        internal async Task CancelSessionAsync()
         {
             if (_sessionCancellationSource is { IsCancellationRequested: false })
             {
                 _sessionCancellationSource.Cancel();
                 _sessionCancellationSource.Dispose();
             }
+
+            if (_sessionLockRenewalTask != null)
```
Comment (jsquire) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs:417]: Alternatively, we could consider an exception block here that logs to avoid unobserved exceptions when we're fire-n-forget calling.

**Review by jsquire — APPROVED** [review]

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs (hunk 4 above)
Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs:417]: The lock renewal task itself has logging for non TCE - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs#L378

For TCE, these are expected and therefore not logged.

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessSessionMessageEventArgs.cs (hunk 3 above)
Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessSessionMessageEventArgs.cs:235]: We will end up awaiting this task when the session is closed, which would happen either when switching to a new session or when closing the processor. If for some reason the application crashes and we never await the task, we would still log non-TCE errors within the [RenewSessionLock](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs#L378) task. I think using ContinueWith would be equivalent to the current behavior as it would still only execute once the task completes.
