### PR TITLE
Fix for tags operation generation

### LINKED ISSUE #52381: Error thrown during tags operation generation
```
Error: Error: Failed to generate the library. Exit code: 1.
StackTrace:
The given key 'Microsoft.TypeSpec.Generator.Input.InputOperation' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.TypeSpec.Generator.ClientModel.Providers.RestClientProvider.GetCreateRequestMethod(InputOperation operation)
   at Azure.Generator.Management.Extensions.ClientProviderExtensions.GetRequestMethodByOperation(ClientProvider clientProvider, InputOperation operation) in C:\temp\azure-sdk-for-net\eng\packages\http-client-csharp-mgmt\generator\Azure.Generator.Management\src\Extensions\ClientProviderExtensions.cs:line 20
   at Azure.Generator.Management.Providers.TagMethodProviders.BaseTagMethodProvider.CreateRequestContextAndProcessMessage(ResourceClientProvider resourceClientProvider, Boolean isAsync, ParameterProvider cancellationTokenParam, ScopedApi`1& responseVariable) in C:\temp\azure-sdk-for-net\eng\packages\http-client-csharp-mgmt\generator\Azure.Generator.Management\src\Providers\TagMethodProviders\BaseTagMethodProvider.cs:line 119
   at Azure.Generator.Management.Providers.TagMethodProviders.BaseTagMethodProvider.BuildIfStatements(ParameterProvider cancellationTokenParam, Func`2 tagOperation, Boolean includeDeleteOperation) in C:\temp\azure-sdk-for-net\eng\packages\http-client-csharp-mgmt\generator\Azure.Generator.Management\src\Providers\TagMethodProviders\BaseTagMethodProvider.cs:line 301
   at Azure.Generator.Management.Providers.TagMethodProviders.AddTagMethodProvider.BuildBodyStatements() in C:\temp\azure-sdk-for-net\eng\packages\http-client-csharp-mgmt\generator\Azure.Generator.Management\src\Providers\TagMethodProviders\AddTagMethodProvider.cs:line 52
```

### PR DESCRIPTION
**Pull request by live1206**
Resolves https://github.com/Azure/azure-sdk-for-net/issues/52381

### CODE REVIEW

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/ResourceClientProvider.cs [hunk 1]
```diff
@@ -444,11 +444,11 @@ protected override MethodProvider[] BuildMethods()
...
             {
-                // Find the update method to get its rest client
-                var updateMethod = _resourceMetadata.Methods.FirstOrDefault(m => m.Kind == ResourceOperationKind.Update || m.Kind == ResourceOperationKind.Create);
-                if (updateMethod is not null)
+                // Find the update input client, which should have both get and update methods
+                var client = GetUpdateClient();
+                if (client is not null)
                 {
-                    var updateRestClientInfo = _clientInfos[updateMethod.InputClient];
+                    var updateRestClientInfo = _clientInfos[client];
```
Comment (ArcturusZhang) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/ResourceClientProvider.cs]: so all these stuff is here to determine the corresponding rest client provider for this updateMethodProvider?
Instead of doing this stuff, how about we just use another local variable to store it like what we have done for this update, and here we could do:
```
if (HasTags() && _resourceMetadata.Methods.Any(m => m.Kind == ResourceOperationKind.Get) && updateMethodProvider is not null && updateRestClient is not null)
```

Comment (ArcturusZhang) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/ResourceClientProvider.cs]: if possible we could define a private struct here for simplicity.

Comment (live1206) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/ResourceClientProvider.cs]: We only try to get the update client when the first if condition meets, it saves the effort of getting the update client.
private struct may not help much here, because we need instance private methods and fields to get the update method and update client.

Comment (live1206) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Providers/ResourceClientProvider.cs]: left a TODO for struct

**Review by ArcturusZhang — APPROVED** [review]
