### PR TITLE
Add back partition tests; fix bug in envelope generation

### LINKED ISSUE #13717: Re-enable session partition peek tests after root cause is determined
These tests started failing last night and appear to be either a service issue or an issue with AMQP library. I tested against earlier versions of the AMQP library and it still occurred, so service issue seems more likely. I've reached out to the service team to see if there are any recent deployments that could have caused this.
We should re-enable the tests once the root issue is fixed.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=470240&view=ms.vss-test-web.build-test-results-tab

### PR DESCRIPTION
**Pull request by JoshLove-msft**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/13717
- The service made an update to require that sessionId matches partitionKey even on non-partitioned entities.

While fixing the test, I ran into a bug where our batch envelope was not correctly setting properties based on the first message. The fix is to force the Select enumeration before calling the `BuildAmpMessageFromBatch` method, because otherwise `firstMessage` is always passed as null.

### CODE REVIEW

**Review by jsquire — APPROVED** [review]

File: sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/SessionReceiverLiveTests.cs [hunk 1]
```diff
@@ -16,24 +16,22 @@ namespace Azure.Messaging.ServiceBus.Tests.Receiver
...
-        [TestCase(10000, null)]
-        [TestCase(null, null)]
-        public async Task PeekSession(long? sequenceNumber, string partitionKey)
+        [TestCase(1)]
+        [TestCase(10000)]
+        [TestCase(null)]
+        public async Task PeekSession(long? sequenceNumber)
         {
-            await using (var scope = await ServiceBusScope.CreateWithQueue(enablePartitioning: false, enableSession: true))
+            await using (var scope = await ServiceBusScope.CreateWithQueue(enablePartitioning: true, enableSession: true))
```
Comment (MiYanni) [inline sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/SessionReceiverLiveTests.cs:24]: Before, because this test was failing, it was testing this:
> The service made an update to require that sessionId matches partitionKey even on non-partitioned entities.

Since you enabled partitioning now, do we have a test to test this situation for non-partitioned entities?

**Review by MiYanni — APPROVED** [review]

File: sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/SessionReceiverLiveTests.cs (hunk 1 above)
Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/SessionReceiverLiveTests.cs:24]: Woops I missed this comment. The test cases we had before didn't really make sense because you shouldn't set the session and partition to different things. As far as non-partitioned tests go, the majority of our tests are on non-partitioned entities.
