### PR TITLE
Sb cross entity fix

### LINKED ISSUE #20180: When reconnecting a sender with cross entity transactions enabled, make sure to reconnect receiver first
When using the EnableCrossEntityTransactions property, if the connection drops, we need to be careful about reconnecting. If there is a receiver involved in the connection, we should make sure that it is reconnected before the sender so that the inferred send-via will be correct. If there are multiple receive entities, things wouldn't work anyway. If there are multiple send entities, it doesn't matter which one is chosen as the send-via entity.

### PR DESCRIPTION
**Pull request by JoshLove-msft**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/20180

### CODE REVIEW

File: sdk/servicebus/Azure.Messaging.ServiceBus/tests/Transactions/TransactionLiveTests.cs [hunk 1]
```diff
@@ -958,6 +964,83 @@ public async Task CrossEntityTransactionSessionProcessor()
...
+                await receiverA.CompleteMessageAsync(receivedMessage);
+                await senderB.SendMessageAsync(new ServiceBusMessage());
+                ts.Complete();
+            }
+
+            var receiverB = noTxClient.CreateReceiver(queueB.QueueName);
+            Assert.IsNotNull(await receiverB.ReceiveMessageAsync());
+        }
+
+        private static void SimulateNetworkFailure(ServiceBusClient client, ServiceBusReceiver receiver)
```
Comment (JoshLove-msft) [inline sdk/servicebus/Azure.Messaging.ServiceBus/tests/Transactions/TransactionLiveTests.cs:1005]: Just know that I feel bad about this..

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs [hunk 2]
```diff
@@ -819,6 +829,33 @@ private async Task<AmqpSession> CreateAndOpenSessionAsync(AmqpConnection connect
...
         }
 
+        private void ValidateCanCreateSenderLink(string entityPath)
+        {
+            if (_useSingleSession)
+            {
+                lock (_syncLock)
+                {
+                    // The send-via entity is a receiver and there are no active links. We are reconnecting the connection.
+                    if (_sendViaReceiverEntityPath != null && !ActiveLinks.Any())
```
Comment (jsquire) [inline sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs:839]:
```suggestion
                    if (_sendViaReceiverEntityPath != null && ActiveLinks.Count == 0)
```

Using LINQ with a concurrent collection type forfeits thread-safety as a general rule.  There may be a special case for `Any()` but probably safer and more efficient to use the `Count` directly.

File: sdk/servicebus/Azure.Messaging.ServiceBus/tests/Transactions/TransactionLiveTests.cs (hunk 1 above)
Comment (jsquire) [reply sdk/servicebus/Azure.Messaging.ServiceBus/tests/Transactions/TransactionLiveTests.cs:1005]: You have my sympathies, sir.

I don't normally have much of an issue reflecting on our own types to avoid leaking a ton of private state as `internal` just for a couple of tests.   The reaching into the AMQP library types is regrettable, but the library is pretty much entirely unmockable... so this does avoid a ton of indirection by helper methods.

**Review by jsquire — APPROVED** [review]

File: sdk/servicebus/Azure.Messaging.ServiceBus/tests/Transactions/TransactionLiveTests.cs (hunk 1 above)
Comment (pakrym) [reply sdk/servicebus/Azure.Messaging.ServiceBus/tests/Transactions/TransactionLiveTests.cs:1005]: You should.

File: sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs (hunk 2 above)
Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs:839]: Looks like IsEmpty is preferred:
  AmqpConnectionScope.cs(838, 63): [CA1836] Prefer 'IsEmpty' over 'Count' to determine whether the object contains or not any items

File: sdk/servicebus/Azure.Messaging.ServiceBus/tests/Transactions/TransactionLiveTests.cs (hunk 1 above)
Comment (JoshLove-msft) [reply sdk/servicebus/Azure.Messaging.ServiceBus/tests/Transactions/TransactionLiveTests.cs]: I feel less bad about now after https://github.com/Azure/azure-sdk-for-net/pull/21531/commits/b621e7046411e616d81cc736df9112d1e28c70ea

Thanks @pakrym for pointing out AbortInternal!
