### PR TITLE
fix bug in safe flatten

### LINKED ISSUE #54483: Generated code tries to set a property without 'set' modifer
the new MPG generates following code for service 'computeSchedule' which is trying to set the ```Resources``` property  which is not settable.

Image

### PR DESCRIPTION
**Pull request by haiyuazhang**
fix https://github.com/Azure/azure-sdk-for-net/issues/54483

### CODE REVIEW

**Review by ArcturusZhang — APPROVED** [review]

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Utilities/PropertyHelpers.cs [hunk 1]
```diff
@@ -87,6 +87,11 @@ public static MethodBodyStatement BuildGetter(bool? includeGetterNullCheck, Prop
             // For collection types, we initialize the internal property if it's null and return the inner property.
             if (innerProperty.Type.IsCollection && internalProperty.WireInfo?.IsRequired == true)
             {
+                if (internalProperty.Body.HasSetter == false)
```
Comment (ArcturusZhang) [inline eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Utilities/PropertyHelpers.cs]: is the type of `HasSetter` property `bool?`? if so I think we should open an issue for MTG because this does not make any sense - a property with or without setter, this fact does not have the third state.
if it is bool, I think we should simplify this to
```suggestion
                if (!internalProperty.Body.HasSetter)
```

Comment (ArcturusZhang) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Utilities/PropertyHelpers.cs]: or are you missing a question mark in the chain?

**Review by ArcturusZhang — APPROVED** [review]

**Review by live1206 — APPROVED** [review]

File: eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Utilities/PropertyHelpers.cs (hunk 1 above)
Comment (haiyuazhang) [reply eng/packages/http-client-csharp-mgmt/generator/Azure.Generator.Management/src/Utilities/PropertyHelpers.cs]: changed to  if (!internalProperty.Body.HasSetter)
