### PR TITLE
Fix NullReferenceException for flattened collection properties

### LINKED ISSUE #56421: [Azure Mgmt Generator] Flattened collection property has possibility of returning null value
We have this typespec:
```
// this is a resource model
model UpdateRun is ProxyResource<UpdateRunProperties> {
// omit its name property here
}

model UpdateRunProperties {
  // optional property, which would be safe flattened
  strategy?: UpdateRunStrategy;
}

model UpdateRunStrategy {
  // required collection
  stages: UpdateStage[];
}
```
but in the generated code:
```
public partial class UpdateRun
{
        internal UpdateRunProperties Properties { get; set; }
        public IList<ContainerServiceFleetUpdateStage> StrategyStages
        {
            get
            {
                return Properties is null ? default : Properties.StrategyStages;
            }
        }
}

public partial class UpdateRunProperties
{
    internal ContainerServiceFleetUpdateRunStrategy Strategy { get; set; }
    public IList<ContainerServiceFleetUpdateStage> StrategyStages
        {
            get
            {
                return Strategy is null ? default : Strategy.Stages;
            }
        }
}
```
both of them are returning null value when the corresponding internal property is null.

In real cases (like in our test cases), users cannot assign those internal properties in the first place, therefore they will always get a null value for this collection, and it does not have a setter, they cannot set values into it.
Also this null collection will cause our serialization to throw NullReferenceException.

### PR DESCRIPTION
**Pull request by live1206**
fixes #56421

## Description

Fixes a NullReferenceException that occurs when accessing flattened collection properties on management-plane SDK models. When the internal backing property is null, the getter would return \default\ (null), causing NRE when users try to add items to the collection or during serialization.

### Generator source (\Azure.Generator.Management\)

- **\PropertyHelpers.cs\**: Updated \BuildGetter\ to lazily initialize the internal property when a flattened collection property is accessed and the backing object is null. Instead of returning \default\, it creates a new instance of the inner model so the collection is always accessible.

- **\FlattenPropertyVisitor.cs\**: Added \UpdateFlattenTypeCollectionProperty\ call in the \SafeFlatten\ path (was previously only called in \PropertyFlatten\), ensuring collection properties in safe-flattened types are also initialized with \ChangeTrackingList<T>\.

### Generated test projects (\Mgmt-TypeSpec\)

- 8 model files updated with \ChangeTrackingList<T>\ initialization on collection properties
- \BarSettingsResourceData.cs\ getter updated to use lazy initialization pattern

## Validation

- ✅ Generator builds successfully (0 errors, 0 warnings)
- ✅ All 114 unit tests pass
- ✅ Test project regeneration produces consistent output

### CODE REVIEW

File: eng/packages/http-client-csharp-mgmt/generator/TestProjects/Local/Mgmt-TypeSpec/src/Generated/Models/SafeFlattenModel.cs [hunk 1]
```diff
@@ -34,6 +34,6 @@ internal SafeFlattenModel(IList<string> flattenedProperty, IDictionary<string, B
 
         /// <summary> Gets the FlattenedProperty. </summary>
         [WirePath("flattenedProperty")]
-        public IList<string> FlattenedProperty { get; }
+        public IList<string> FlattenedProperty { get; } = new ChangeTrackingList<string>();
```
Comment (ArcturusZhang) [inline eng/packages/http-client-csharp-mgmt/generator/TestProjects/Local/Mgmt-TypeSpec/src/Generated/Models/SafeFlattenModel.cs]: I think this is not a required change for the issue we want to solve right now - because the initialization ctor will always assign this property with the same value.
The changes in `BarSettingsResourceData.cs` solve the issue nicely.

**Review by ArcturusZhang — APPROVED** [review]
