### PR TITLE
ClientModel: Get test coverage parity with Azure.Core

### LINKED ISSUE #40560: ClientModel: Add test coverage for ClientModel types
### Foundational pieces
- [x] Allow System.ClientModel test projects to use Azure.Core test framework where appropriate

### Root Namespace
- [x] ApiKeyCredential
- [x] BinaryContent
- [x] ClientResult
- [x] ClientResult\<T\>
- [x] ClientResultException

### .Primitives Namespace
- [x] ClientPipelineOptions
- [x] RequestOptions
- [x] ApiKeyAuthenticationPolicy
- [x] ClientPipeline
- [x] ClientRetryPolicy
- [x] HttpClientPipelineTransport
- [x] PipelineMessage
- [x] PipelineMessageClassifier
- [x] PipelinePolicy
- [x] PipelineRequest
- [x] PipelineRequestHeaders
- [x] PipelineResponse
- [x] PipelineResponseHeaders
- [x] PipelineTransport

### Other
- [x] Identify if there are internal types we want to add test coverage for
- [x] Move validations in types under ToBeDeleted/ into tests and remove those types

### PR DESCRIPTION
**Pull request by annelo-msft**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/40560

### CODE REVIEW

File: sdk/core/System.ClientModel/tests/Pipeline/ClientPipelineTests.cs [hunk 1]
```diff
@@ -311,11 +312,13 @@ public async Task RequestOptionsCanCustomizePipeline()
         List<string> observations = ObservablePolicy.GetData(message);
 
         int index = 0;
-        Assert.AreEqual(7, observations.Count);
+        Assert.AreEqual(9, observations.Count);
```
Comment (AlexanderSher) [inline sdk/core/System.ClientModel/tests/Pipeline/ClientPipelineTests.cs:315]: Why 9?

File: sdk/core/System.ClientModel/tests/Options/PipelineMessageClassifierTests.cs [hunk 2]
```diff
@@ -11,6 +11,82 @@ namespace System.ClientModel.Tests.Options;
...
+    [TestCase(500)]
+    [TestCase(429)]
+    [TestCase(408)]
+    [TestCase(502)]
+    [TestCase(503)]
+    [TestCase(504)]
+    public void RetriesStatusCodes(int code)
+    {
+        MockPipelineMessage message = new MockPipelineMessage();
+        message.SetResponse(new MockPipelineResponse(code));
```
Comment (christothes) [inline sdk/core/System.ClientModel/tests/Options/PipelineMessageClassifierTests.cs:24]: To keep these as pure unit test, could we eliminate `MockPipelineMessage` from this test and operate directly with `PipelineMessageClassifier`? If the implementation of `MockPipelineMessage` or `PipelineMessage` ever changes, this test may end up inadvertently testing some other implementation.

File: sdk/core/System.ClientModel/tests/Pipeline/HttpClientPipelineTransportTests.cs [hunk 3]
```diff
@@ -138,6 +139,364 @@ public async Task SettingResponseContentStreamPreservesHeaders(string headerName
...
+        message.Request.Method = "GET";
+        message.Request.Uri = new Uri("http://example.com");
+
+        await transport.ProcessSyncOrAsync(message, IsAsync);
+
+        Assert.AreEqual(0, message.Response!.ContentStream!.Length);
+    }
+
+    [Test]
+    public async Task BufferedResponseContentStreamCanBeReadMultipleTimes()
```
Comment (christothes) [inline sdk/core/System.ClientModel/tests/Pipeline/HttpClientPipelineTransportTests.cs:258]: nit: some of these tests seem to only address behavior of `HttpClientTransportResponse` that is agnostic to the transport. Should those tests be simplified and moved to `HttpClientTransportResponseTests`?

File: sdk/core/System.ClientModel/tests/Pipeline/ClientPipelineTests.cs (hunk 1 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/tests/Pipeline/ClientPipelineTests.cs:315]: That is the number of observable policies in the pipeline.  It went from 7->9 in this PR because I wasn't previously testing that we could add policies in the `BeforeTransport` position via `RequestOptions` -- I added such a policy in this test.

File: sdk/core/System.ClientModel/tests/Options/PipelineMessageClassifierTests.cs (hunk 2 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/tests/Options/PipelineMessageClassifierTests.cs:24]: That is fair.  I copied these over from Azure.Core, but I also wondered whether it was needed to use the message's classifier here. I'll update to make this consistent with other tests in this file, and reduce the code coverage area to just the classifier.  Thanks!

File: sdk/core/System.ClientModel/tests/Pipeline/HttpClientPipelineTransportTests.cs (hunk 3 above)
Comment (annelo-msft) [reply sdk/core/System.ClientModel/tests/Pipeline/HttpClientPipelineTransportTests.cs:258]: Interesting.  The response implementation is specific to a transport -- note that the response type itself is a private nested class in the transport.  But I see your point that some of the tests in this file are testing transport.Process and other public methods on transport, whereas others are testing the response implementation.  If you feel strongly about this, I can create a separate class that contains tests specific to the transport's response implementation.

Comment (christothes) [reply sdk/core/System.ClientModel/tests/Pipeline/HttpClientPipelineTransportTests.cs:258]: > note that the response type itself is a private nested class in the transport.

I hadn't noticed that - makes sense to me then 😄

**Review by christothes — APPROVED** [review]

**Review by AlexanderSher — APPROVED** [review]
