### PR TITLE
Fix provisioning generator property ordering and child resource location

### LINKED ISSUE #57489: [Provisioning Generator] ARM resource common properties should be emitted before other properties
## Description

The new TypeSpec-based provisioning generator emits ARM resource properties in a different order than the old reflection-based generator. Specifically, `properties` is emitted before `name` and `location`, which changes the Bicep output ordering.

### Expected behavior

The old reflection-based generator sorted properties with this ordering logic (from `Specification.Analyze.cs`):
```csharp
resource.Properties.OrderBy(p => (p.Name == "Name" ? 0 : p.IsReadOnly ? '3' : p.IsRequired ? '1' : '2') + p.Name)
```

This ensured `name` was always first, followed by required properties alphabetically, then read-only/output properties.

Generated `DefineProvisionableProperties()`:
```csharp
_name = DefineProperty<string>("Name", ["name"], isRequired: true);
_location = DefineProperty<AzureLocation>("Location", ["location"], isRequired: true);
_properties = DefineModelProperty<KeyVaultProperties>("Properties", ["properties"], isRequired: true);
```

### Actual behavior

The new generator emits:
```csharp
_properties = DefineModelProperty<KeyVaultProperties>(nameof(Properties), new string[] { "properties" }, isRequired: true);
_name = DefineProperty<string>(nameof(Name), new string[] { "name" }, isRequired: true);
_location = DefineProperty<AzureLocation>(nameof(Location), new string[] { "location" }, isRequired: true);
```

Since the Bicep emitter uses insertion order, this causes `properties:` to appear before `name:` in the Bicep output.

### Impact

All regenerated provisioning libraries will have a different Bicep property ordering than before. While functionally equivalent, this is a behavioral change that breaks existing tests and differs from standard Bicep conventions where `name` and `location` typically appear before `properties`.

### Proposed fix

The provisioning generator should ensure ARM resource common properties (`name`, `location`, `tags`) are always defined before the `properties` bag and other custom properties in `DefineProvisionableProperties()`.

### PR DESCRIPTION
**Pull request by ArcturusZhang**
## Description

Fixes #57489 and #57488

### Property ordering (#57489)

The provisioning generator was collecting properties from the leaf model first, then walking up the base chain. This caused the `properties` bag to appear before `name`/`location` in the generated `DefineProvisionableProperties()` method, which in turn caused Bicep output to emit `properties:` before `name:` — breaking conventional ARM Bicep ordering.

**Fix:** Reversed the property collection order in `CollectAllProperties()` using a `Stack` so that base model properties (`name`, `location`, `tags` from `TrackedResource`/`Resource`) are collected before leaf-defined properties (e.g., the `properties` bag).

### Child resource location (#57488)

The `location` property was unconditionally forced as required via `RequiredInputProperties`, even for child/proxy resources where the TypeSpec marks it as `@visibility(Lifecycle.Read)` (read-only). This caused spurious `location: location` to appear in Bicep output for child resources like `KeyVaultSecret`.

**Fix:** Removed `location` from `RequiredInputProperties`. For tracked resources, `location` is already `optional=false`/`readOnly=false` in the TypeSpec model, so it remains required naturally. For child resources with read-only location, it now correctly becomes output-only.

Also added a `TypeOverride` mechanism in `ProvisioningPropertyInfo` to ensure resource-level `location` properties always use `BicepValue<AzureLocation>` even when the TypeSpec defines them as plain `string`.

### Minor improvements

- Used `Dictionary<InputModelProperty, ResourcePropertyInfo>` for O(1) property lookup in `GetProvisioningPropertyInfo` instead of linear scan.

### CODE REVIEW

File: eng/packages/http-client-csharp-provisioning/generator/Azure.Generator.Provisioning/src/Providers/ProvisioningResourceProvider.cs [hunk 1]
```diff
@@ -420,7 +436,16 @@ private void CollectPropertiesFromModel(
                     defaultValue = _resourceMetadata.SingletonResourceName;
                     isOutput = true;
                 }
-                result.Add(new ResourcePropertyInfo(prop, propertyName, bicepPath, isOutput, isRequired, defaultValue));
+                // Ensure "location" at the resource level always uses AzureLocation,
```
Comment (live1206) [inline eng/packages/http-client-csharp-provisioning/generator/Azure.Generator.Provisioning/src/Providers/ProvisioningResourceProvider.cs:439]: Should we fix the spec instead? think it would be better to get rid of this magic in generator.

Comment (ArcturusZhang) [reply eng/packages/http-client-csharp-provisioning/generator/Azure.Generator.Provisioning/src/Providers/ProvisioningResourceProvider.cs:439]: I prefer this way because there is no guarantee that we always catch this in the typespec.

Comment (live1206) [reply eng/packages/http-client-csharp-provisioning/generator/Azure.Generator.Provisioning/src/Providers/ProvisioningResourceProvider.cs:439]: we should catch them during review using skill and in the future we should have script to guard this in CI.

Comment (ArcturusZhang) [reply eng/packages/http-client-csharp-provisioning/generator/Azure.Generator.Provisioning/src/Providers/ProvisioningResourceProvider.cs:439]: I added a note here so that in the future we might have the chance to remove this.

**Review by live1206 — APPROVED** [review]
