### PR TITLE
fix(appplatform): failed to parse different formats of guid value

### LINKED ISSUE #35061: [BUG] Azure.ResourceManager.AppPlatform can't work due to UUID format
### Library name and version

azure.resourcemanager.appplatform 1.0.1

### Describe the bug

`client.GetAppPlatformServiceResource(id).Get()` get service failed. Maybe it is due to the some service doesn't return UUID in "serviceId" field

for example, here is one of my failed Azure Spring Apps API response:
```JSON
{
    "id": "/subscriptions/***/resourceGroups/***/providers/Microsoft.AppPlatform/Spring/***",
    "location": "eastus2euap",
    "name": "***",
    "properties": {
        "fqdn": "***.azuremicroservices.io",
        "networkProfile": {
            "outboundIPs": {
                "publicIPs": [
                    "20.47.146.102"
                ]
            },
            "outboundType": "loadBalancer"
        },
        "powerState": "Running",
        "provisioningState": "Succeeded",
        "serviceId": "79d502c7359c4afc99095965f28ca37f",
        "version": 3,
        "zoneRedundant": false
    },
    "sku": {
        "name": "B0",
        "tier": "Basic"
    },
    "systemData": {
        "createdAt": "2022-03-21T06:19:40.3152314Z",
        "createdBy": "***",
        "createdByType": "User",
        "lastModifiedAt": "2022-03-21T06:19:40.3152314Z",
        "lastModifiedBy": "***",
        "lastModifiedByType": "User"
    },
    "tags": {},
    "type": "Microsoft.AppPlatform/Spring"
}
```

### Expected behavior

Service should get successfully

### Actual behavior

```
[xUnit.net 00:00:02.28]     test.UnitTest1.Test1 [FAIL]
  Failed test.UnitTest1.Test1 [1 s]
  Error Message:
   System.FormatException : One of the identified items was in an invalid format.
  Stack Trace:
     at System.Text.Json.JsonElement.GetGuid()
   at Azure.ResourceManager.AppPlatform.Models.AppPlatformServiceProperties.DeserializeAppPlatformServiceProperties(JsonElement element)
   at Azure.ResourceManager.AppPlatform.AppPlatformServiceData.DeserializeAppPlatformServiceData(JsonElement element)
   at Azure.ResourceManager.AppPlatform.ServicesRestOperations.Get(String subscriptionId, String resourceGroupName, String serviceName, CancellationToken cancellationToken)
   at Azure.ResourceManager.AppPlatform.AppPlatformServiceCollection.Get(String serviceName, CancellationToken cancellationToken)
   at Azure.ResourceManager.AppPlatform.AppPlatformExtensions.GetAppPlatformService(ResourceGroupResource resourceGroupResource, String serviceName, CancellationToken cancellationToken)
   at test.UnitTest1.Test1() in /root/test/UnitTest1.cs:line 24
   at test.UnitTest1.Test1() in /root/test/UnitTest1.cs:line 16
--- End of stack trace from previous location ---
```

### Reproduction Steps

In above

### Environment

container: mcr.microsoft.com/dotnet/sdk:6.0
```
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.202/

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  6.0.202 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### PR DESCRIPTION
**Pull request by archerzz**
`AppPlatformServiceProperties` could have GUID values with different foramts. One format doesn't follow the RFC UUID spec, so there will be exception when parsing the value.

This commit will fix the issue by:
- add a new property `ServiceInstanceId` with string type so that various formats can be accepted
- use customization codes to keep `ServiceId` property for backward compatibility
  - its value is from parsing `ServiceInstanceId` as UUID
  - mark it as obsolete and editor visiblity to never
- add unit tests
- update api signature
- bump version to `1.0.2`

fix #35061

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by ChenTanyi — APPROVED** [review]
LGTM

File: sdk/appplatform/Azure.ResourceManager.AppPlatform/src/Customize/Models/AppPlatformServiceProperties.cs [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+#nullable disable
+
+using System;
+using System.ComponentModel;
+
+namespace Azure.ResourceManager.AppPlatform.Models
+{
+    public partial class AppPlatformServiceProperties
+    {
+        /// <summary> DEPRECATED: ServiceInstanceEntity GUID which uniquely identifies a created resource. </summary>
```
Comment (m-nash) [inline sdk/appplatform/Azure.ResourceManager.AppPlatform/src/Customize/Models/AppPlatformServiceProperties.cs:13]: nit: can we add something saying it can throw a FormatException if the value from the service is not a Guid

**Review by m-nash — APPROVED** [review]

**Review by ArthurMa1978 — APPROVED** [review]
