### PR TITLE
[SQL] Rename metrics operation group & update swagger readme commit id

### LINKED ISSUE #28387: [BUG] Cannot get SQL databases
### Library name and version

Azure.ResourceManager.Sql 1.0.0-beta.4

### Describe the bug

Following code:
```
await foreach (SqlDatabaseResource resource in sqlServer.GetSqlDatabases().GetAllAsync())
{
    Console.WriteLine("SQL db: " + resource);
}
```
results with a InvalidOperationException:
```
The requested operation requires an element of type 'Number', but the target element has type 'String'.
```

### Expected behavior

Databases are listed

### Actual behavior

Exception is thrown

### Reproduction Steps

Just run this code:
```
try
{
     var subscription = subscriptions.Get(subscriptionId).Value;
     await foreach (var resource in subscription.GetResourceGroups().GetAllAsync())
     {
         Console.WriteLine("RG: " + resource.Data.Name);
     }

     var resourceGroup = subscription.GetResourceGroup(rgName).Value;
     await foreach (var resource in resourceGroup.GetSqlServers().GetAllAsync())
     {
         Console.WriteLine("SQL server: " + resource.Data.Name);
     }

    var sqlServer = resourceGroup.GetSqlServer(serverName).Value;
    await foreach (var resource in sqlServer.GetElasticPools().GetAllAsync())
    {
        Console.WriteLine("SQL ep: " + resource.Data.Name);
    }
    await foreach (SqlDatabaseResource resource in sqlServer.GetSqlDatabases().GetAllAsync())
    {
        Console.WriteLine("SQL db: " + resource);
    }
}
catch (InvalidOperationException e)
{
    Console.WriteLine(e.Message);
}
```

### Environment

_No response_

### PR DESCRIPTION
**Pull request by fengzhou-msft**
Resolve #28387

This PR also updated the swagger readme to the latest to solve the issue that for the same resource type: ReplicationLinks, the tag package-composite-v5 used different API versions in different swagger files:
•	https://raw.githubusercontent.com/Azure/azure-rest-api-specs/4946dbb5b2893a77ce52d08e2a855056e1acd361/specification/sql/resource-manager/Microsoft.Sql/stable/2014-04-01-legacy/replicationLinks_legacy.json
•	https://raw.githubusercontent.com/Azure/azure-rest-api-specs/4946dbb5b2893a77ce52d08e2a855056e1acd361/specification/sql/resource-manager/Microsoft.Sql/preview/2021-02-01-preview/ReplicationLinks.json

The latest readme removed replicationLinks_legacy.json and consolidated its operations in a new version of ReplicationLinks.json

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by ericshape — APPROVED** [review]

File: sdk/sqlmanagement/Azure.ResourceManager.Sql/src/Generated/IPv6FirewallRuleCollection.cs [hunk 1]
```diff
@@ -0,0 +1,333 @@
...
+using Azure.ResourceManager;
+
+namespace Azure.ResourceManager.Sql
+{
+    /// <summary>
+    /// A class representing a collection of <see cref="IPv6FirewallRuleResource" /> and their operations.
+    /// Each <see cref="IPv6FirewallRuleResource" /> in the collection will belong to the same instance of <see cref="SqlServerResource" />.
+    /// To get an <see cref="IPv6FirewallRuleCollection" /> instance call the GetIPv6FirewallRules method from an instance of <see cref="SqlServerResource" />.
+    /// </summary>
+    public partial class IPv6FirewallRuleCollection : ArmCollection, IEnumerable<IPv6FirewallRuleResource>, IAsyncEnumerable<IPv6FirewallRuleResource>
```
Comment (archerzz) [inline sdk/sqlmanagement/Azure.ResourceManager.Sql/src/Generated/IPv6FirewallRuleCollection.cs:27]: maybe `IpV6FirewallRule`?

**Review by archerzz — APPROVED** [review]

**Review by ArthurMa1978 — APPROVED** [review]
