### PR TITLE
Fix floating number issue

### LINKED ISSUE #48249: [BUG] Azure.Provisioning.OperationalInsights DailyQuotaInGB generated as string instead of int
### Library name and version

Azure.Provisioning.OperationalInsights

### Describe the bug

When defining a log analytics workspace like this:
```csharp
var logAnalyticsWorkspace = new OperationalInsightsWorkspace("logAnalyticsWorkspace")
{
	Name = $"log-sample-dev",
	Location = "australiaeast",
	Identity = new ManagedServiceIdentity { ManagedServiceIdentityType = ManagedServiceIdentityType.SystemAssigned },
	Sku = new OperationalInsightsWorkspaceSku { Name = OperationalInsightsWorkspaceSkuName.PerGB2018 },
	WorkspaceCapping = new OperationalInsightsWorkspaceCapping { DailyQuotaInGB = 1 }
};
```

The generated bicep results in:
```bicep
resource logAnalyticsWorkspace 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: 'log-sample-dev'
  location: 'australiaeast'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    sku: {
      name: 'PerGB2018'
    }
    workspaceCapping: {
      dailyQuotaGb: '1' <-------------
    }
  }
}
```

dailyQuotaGb should be an int, instead of a string.

DailyQuotaInGB is actually defined as a double in the SDK, probably needs to be changed to int :)

`private BicepValue<double>? _dailyQuotaInGB;`

### Expected behavior

dailyQuotaGb should be an int in the output bicep

### Actual behavior

dailyQuotaGb is a string in the output bicep

### Reproduction Steps

```csharp
var logAnalyticsWorkspace = new OperationalInsightsWorkspace("logAnalyticsWorkspace")
{
	Name = $"log-sample-dev",
	Location = "australiaeast",
	Identity = new ManagedServiceIdentity { ManagedServiceIdentityType = ManagedServiceIdentityType.SystemAssigned },
	Sku = new OperationalInsightsWorkspaceSku { Name = OperationalInsightsWorkspaceSkuName.PerGB2018 },
	WorkspaceCapping = new OperationalInsightsWorkspaceCapping { DailyQuotaInGB = 1 }
};

var infrastructure = new Infrastructure();
infrastructure.Add(logAnalyticsWorkspace);
var provisioningPlan = infrastructure.Build();
provisioningPlan.Save("./");
```

### Environment

_No response_

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/48249

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

File: sdk/provisioning/Azure.Provisioning/src/Expressions/BicepTypeMapping.cs [hunk 1]
```diff
@@ -96,6 +98,11 @@ public static BicepExpression ToBicep(object? value, string? format)
             // in bicep source and you need to use a parameter file for larger
             // values
             long i => BicepSyntax.Value((int)i),
+            // Note: bicep does not offically support floating numbers
+            // therefore for floating numbers we are taking a workaround from
+            // https://github.com/Azure/bicep/issues/1386#issuecomment-818077233
+            float f => FromFloat(f),
+            double d => FromDouble(d),
```
Comment (tg-msft) [inline sdk/provisioning/Azure.Provisioning/src/Expressions/BicepTypeMapping.cs:105]: I think we can get away with sharing `FromDouble` so we have less code:
```suggestion
            float f => FromDouble(f),
            double d => FromDouble(d),
```

File: sdk/provisioning/Azure.Provisioning/src/Expressions/BicepTypeMapping.cs [hunk 2]
```diff
@@ -121,6 +128,30 @@ IBicepValue v when (v.Kind == BicepValueKind.Unset) => BicepSyntax.Null(),
...
+            }
+            // otherwise we use the workaround from https://github.com/Azure/bicep/issues/1386#issuecomment-818077233
+            return BicepFunction.ParseJson(BicepSyntax.Value(f.ToString())).Compile();
+        }
+
+        BicepExpression FromDouble(double d)
+        {
+            // see if the value is a whole number
+            var i = (int)d;
+            if (d == i)
```
Comment (tg-msft) [inline sdk/provisioning/Azure.Provisioning/src/Expressions/BicepTypeMapping.cs:147]: This isn't the safest way to check for a whole number.   I'd recommend something more like:
```suggestion
            // see if the value is a whole number
            if (Math.Floor(d) == d)
```

File: sdk/provisioning/Azure.Provisioning/tests/BicepValues/BicepValueTests.cs [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+using NUnit.Framework;
+
+namespace Azure.Provisioning.Tests.BicepValues;
+
+public class BicepValueTests
+{
+    [TestCaseSource(nameof(LiteralBicepValueTestCases))]
+    public string ValidateLiteralBicepValue(BicepValue bicepValue)
+    {
+        return bicepValue.Compile().ToString();
```
Comment (tg-msft) [inline sdk/provisioning/Azure.Provisioning/tests/BicepValues/BicepValueTests.cs:14]: Nit - You can just do `.ToString()` because `BicepValue<T>.ToString()` will implicitly call `.Compile()` for you.

File: sdk/provisioning/Azure.Provisioning/src/Expressions/BicepTypeMapping.cs [hunk 4]
```diff
@@ -96,6 +98,11 @@ public static BicepExpression ToBicep(object? value, string? format)
             // in bicep source and you need to use a parameter file for larger
             // values
             long i => BicepSyntax.Value((int)i),
```
Comment (tg-msft) [inline sdk/provisioning/Azure.Provisioning/src/Expressions/BicepTypeMapping.cs:100]: FWIW, I wonder if we'll have the same bug here in the future?  I haven't seen anyone trying to use values larger than `int.MaxValue` by parsing a JSON string though.  I don't think we should fix it now, but keep it in mind if we ever hear any customer issues.

**Review by tg-msft — APPROVED** [review]
Looks great!

File: sdk/provisioning/Azure.Provisioning/src/Expressions/BicepTypeMapping.cs (hunk 4 above)
Comment (ArcturusZhang) [reply sdk/provisioning/Azure.Provisioning/src/Expressions/BicepTypeMapping.cs:100]: yep, I wonder the same thing for long. I will keep it in mind

**Review by ArthurMa1978 — APPROVED** [review]
