### PR TITLE
[EventHubs, Azure.Core Shared] Move enqueuedTime from root activity to linked activity (Track Two)

### LINKED ISSUE #10324: [BUG] EH SDK: Enqueued Time on root activity, not on the links
**Describe the bug**
[This recent PR](https://github.com/Azure/azure-sdk-for-net/pull/10227/files) has added attribute "x-opt-enqueued-time" to the Diagnostic Scope activity.
While debugging this new behavior with new version of Application Insights SDK that reads this attribute, I noticed that there is disconnect between the two SDKs on the expected attribute location:
- AI SDK [looks through the links](https://github.com/microsoft/ApplicationInsights-dotnet/blob/502f001c59f104f2a81bc002b48b909fa57e98ef/WEB/Src/DependencyCollector/Shared/Implementation/AzureSdk/AzureSdkDiagnosticsEventHandler.cs#L149-L151) of the [Activity in Diagnostic Source event](https://github.com/microsoft/ApplicationInsights-dotnet/blob/502f001c59f104f2a81bc002b48b909fa57e98ef/WEB/Src/DependencyCollector/Shared/Implementation/AzureSdk/AzureSdkDiagnosticsEventHandler.cs#L67);
- EH SDK [stores that time in the tags of the main Activity](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L730) instead.

Side note: AI SDK reads ["enqueueTime"](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/DependencyCollector/Shared/Implementation/AzureSdk/AzureSdkDiagnosticsEventHandler.cs#L181) attribute while value is posted to ["x-opt-enqueued-time"](https://github.com/Azure/azure-sdk-for-net/blob/eea84100459b1b97547c3a556fc7491f78afafcb/sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Diagnostics/DiagnosticProperty.cs#L25) attribute, one of the SDKs would need to fix that too (I guess, AI?).

**Expected behavior**
I had a conversation with original developer on AI SDK side and the expected behavior seem to be to store enqueued time in the links of the activity because it's the way to post that time for each separate message. (+ Both SDKs should agree on the attribute name :) )

**Actual behavior (include Exception or Stack Trace)**
EH SDK stores enqueued time on the main Activity propagated with DS event.

**To Reproduce**
- Debug [LineCounter](https://github.com/pakrym/LineCounter) application (make sure both projects are marked as startup). 
- Ensure latest AI SDK is installed (or build from local source)
- Ensure latest EH SDK is installed (or build from local source)
- Set BP on [AI reading EH DS event](https://github.com/microsoft/ApplicationInsights-dotnet/blob/502f001c59f104f2a81bc002b48b909fa57e98ef/WEB/Src/DependencyCollector/Shared/Implementation/AzureSdk/AzureSdkDiagnosticsEventHandler.cs#L67), check that root Activity has tag, not linked activities.

**Environment:**
 - Latest master from source, EH SDK, commit 257703eb88ce733d0d8cbbd22c66339794fa8350.
 - Win10, .NET Core 3.0
 - Visual Studio 16.4.5

### PR DESCRIPTION
**Pull request by kinelski**
Fixes #10324

Event Hubs:
- Renamed enqueued time attribute from `x-opt-enqueued-time` to `enqueuedTime`.
- Removed the enqueued time attribute from the root processing activity and put it in the linked activity instead.
- Created a new test. It's currently being ignored because it's very similar to `RunPartitionProcessingAsyncCreatesScopeForEventProcessing`, so it's expected to be flaky during nightly runs. It's already being tracked by #10067. No issues when running locally.

Core:
- Updated the `ClientDiagnosticListener` test helper to track linked activities as well, not only their parent ids. I'm keeping the `Links` property since it's already being used in multiple tests across the repo.

### CODE REVIEW

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Diagnostics/DiagnosticsTests.cs [hunk 1]
```diff
@@ -171,6 +169,103 @@ async IAsyncEnumerable<PartitionEvent> mockPartitionEventEnumerable()
             }
         }
 
+        /// <summary>
+        ///   Verifies diagnostics functionality of the <see cref="EventProcessorClient.RunPartitionProcessingAsync" />
+        ///   method.
+        /// </summary>
+        ///
+        [Test]
+        [Ignore("Unstable test. (Tracked by: #10067)")]
```
Comment (pakrym) [inline sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Diagnostics/DiagnosticsTests.cs]: ???

**Comment by pakrym** [comment]
Change itself LGTM, the only test being ignored concerns me slightly.

**Comment by kinelski** [comment]
A can enable it for the time being, but I believe it will be flaky during nightly runs for the same (unknown) reason similar tests are. I can put the `Ignore` attribute back later if that's the case.

**Review by pakrym — APPROVED** [review]

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Diagnostics/DiagnosticsTests.cs [hunk 2]
```diff
@@ -100,8 +99,8 @@ async IAsyncEnumerable<PartitionEvent> mockPartitionEventEnumerable()
                     {
                         var context = new MockPartitionContext(partitionId);
 
-                        yield return new PartitionEvent(context, new MockEventData(Array.Empty<byte>(), enqueuedTime: enqueuedTime) { Properties = { { "Diagnostic-Id", "id" } } });
-                        yield return new PartitionEvent(context, new MockEventData(Array.Empty<byte>(), enqueuedTime: enqueuedTime) { Properties = { { "Diagnostic-Id", "id2" } } });
+                        yield return new PartitionEvent(context, new EventData(Array.Empty<byte>()) { Properties = { { "Diagnostic-Id", "id" } } });
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Diagnostics/DiagnosticsTests.cs]: Should the keys for this property be using `DiagnosticProperty.DiagnosticIdAttribute` to avoid the hardcode?

**Review by jsquire — APPROVED** [review]
LGTM.

Which test were we thinking would be a problem?

**Comment by kinelski** [comment]
The new test: `RunPartitionProcessingAsyncAddsAttributesToLinkedActivities`.

It's basically the same as `RunPartitionProcessingAsyncCreatesScopeForEventProcessing`, but the assertions at the end are different. That's why I believe it will be flaky.
