### PR TITLE
Fix flaky tests and discovered bugs for EventProcessorClient

### LINKED ISSUE #10015: [EventHubs] Some unit tests are flaky or fail constantly
### Summary

Four of the Event Processor Client tests are not working as expected: one of them is already tracked by #9228, while the other three are tracked by this issue.

- `PartitionClosingAsyncIsCalledWithOwnershipLostReasonWhenStoppingTheFailedProcessor` is flaky. Sometimes the test hangs for indefinite time until it gets canceled. Sometimes it works. The flakiness is believed to have been introduced after the creation of the `PartitionLoadBalancer` class.
- `PartitionClosingAsyncTokenIsCanceledWhenStopProcessingAsyncIsCalled` always fails. Reason is unknown.
- `ProcessErrorAsyncIsTriggeredWithCorrectArgumentsWhenOwnershipClaimFails` always fails, but the cause is known.

https://github.com/Azure/azure-sdk-for-net/blob/1408ad9db2579f2943043549c6af70b98f9eb7fe/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L949-L957

The Event Processor Client cannot figure out which partition failed during the `RunLoadBalancingAsync` call and it's passing a `null` to `ProcessErrorEventArgs` instead of passing the partition id. Ownership claim failure is the only load balancing scenario in which a partition id is expected (`null` should be kept for other types of failure).

### Goal

- Make the necessary changes to the client to make the tests pass reliably without flakiness. The tests themselves could be the real problem, so changes to the tests might also be necessary.
- Remove the `Ignore` attribute from the aforementioned tests.
- Assert that no other tests fail because of the changes.

### PR DESCRIPTION
**Pull request by christothes**
## Summary of Changes
- `PartitionClosingAsyncIsCalledWithOwnershipLostReasonWhenStoppingTheFailedProcessor`
  - Change test to wait for all partition processors to begin processing before throwing on `ReadEventsFromPartitionAsync`
- `PartitionClosingAsyncTokenIsCanceledWhenStopProcessingAsyncIsCalled`
  - fix `PartitionClosingEventArgs` ctor to set the value of `CancellationToken`
- `ProcessErrorAsyncIsTriggeredWithCorrectArgumentsWhenOwnershipClaimFails`
  - Created `EventHubsExceptionExtensions` to facilitate bubbling extended error information from `PartitionLoadBalancer.ClaimOwnershipAsync` to `EventProcessorClient.RunAsync`

fixes #10015

### CODE REVIEW

**Comment by christothes** [comment]
@jsquire @kinelski The Analyze phase of the build is failing with the below error. I assume this is related to addition of the new exception type `EventHubsClaimPartitionException`. I'm not sure if introduction of a new type like this requires further review or if I should attempt to run the script(s) below. 

`Generated code is not up to date. You may need to run eng\Update-Snippets.ps1 or sdk\storage\generate.ps1 or eng\Export-API.ps1`

**Comment by jsquire** [comment]
> @jsquire @kinelski The Analyze phase of the build is failing with the below error. I assume this is related to addition of the new exception type `EventHubsClaimPartitionException`. I'm not sure if introduction of a new type like this requires further review or if I should attempt to run the script(s) below.
> 
> `Generated code is not up to date. You may need to run eng\Update-Snippets.ps1 or sdk\storage\generate.ps1 or eng\Export-API.ps1`

Any addition of public API changes, including new types, will trigger this.   Now that we've GA'd,  anything that we do to the API surface has to go through architect review, so there's some process and scrutiny around it.

File: sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubsClaimPartitionException.cs [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+// Licensed under the MIT License.
+
+namespace Azure.Messaging.EventHubs
+{
+    using System;
+
+    /// <summary>
+    ///     The exception that is thrown when a call to claim ownership of a partition fails.  Callers retry the operation.
+    /// </summary>
+    public class EventHubsClaimPartitionException : EventHubsException
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubsClaimPartitionException.cs]: Have we considered doing this by adding an additional reason in the `FailureReason` enum embedded in the Event Hubs exception?   Generally speaking, we've been asked not to add custom exceptions without a strong justification around "would a developer using the client library have a need to catch this explicitly and do something special with it?"

In this case, it looks like we're intending this mainly for internal use.   I'm thinking that the failure reason combined with the [`Data`](https://docs.microsoft.com/en-us/dotnet/api/system.exception.data?view=netcore-3.1#System_Exception_Data) property to ferry over the partition identifier would be sufficient.  

Thoughts?

File: sdk/eventhub/Azure.Messaging.EventHubs/src/Processor/PartitionClosingEventArgs.cs [hunk 2]
```diff
@@ -46,6 +46,7 @@ public class PartitionClosingEventArgs
 
             PartitionId = partitionId;
             Reason = reason;
+            CancellationToken = cancellationToken;
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs/src/Processor/PartitionClosingEventArgs.cs]: Well.... yeah.... that would seem to be a pretty big oversight on our part.   Thanks!

File: sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubsClaimPartitionException.cs (hunk 1 above)
Comment (jsquire) [reply sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubsClaimPartitionException.cs]: An alternative would be to make this an `internal` type since the use appears to be intended for processor infrastructure.   For that, we'd need to throw it into the `Shared` project and bundle it with the processor items.

Comment (christothes) [reply sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubsClaimPartitionException.cs]: Thanks for the context and guidance related to type best practices. I agree that tweaking `FailureReason` would be a less impactful change. I had also not considered leveraging the `Data` property. Great suggestion!

I'll incorporate that into the next commit along with some ideas around how to keep some strong typing on the extended data values.

File: sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubsException.cs [hunk 3]
```diff
@@ -208,7 +208,10 @@ public enum FailureReason
             ServiceTimeout,
 
             /// <summary>There was a general communications error encountered when interacting with the Azure Event Hubs service.</summary>
-            ServiceCommunicationProblem
+            ServiceCommunicationProblem,
+
+            /// <summary>The exception was a result of a failed attempt to claim partition ownership.</summary>
+            ClaimPartitionFailed,
```
Comment (christothes) [inline sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubsException.cs]: @jsquire It looks like this change triggered a generated code error as well. Does still need to go through extra review?

Comment (jsquire) [reply sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubsException.cs]: Technically, yes.   If we're only using it internally, we probably want to try to hide a flag in the `Data` bag first... but if we think this is something we want to surface to developers and that they'll need to take action on, I can drive the conversations.   

Since it's a new member to an embedded specialized type, it wouldn't be difficult so long as we have a couple of concrete scenarios to pitch.

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs [hunk 4]
```diff
@@ -845,7 +845,10 @@ private async Task RunAsync(CancellationToken cancellationToken)
                     }
                     catch (EventHubsException ex)
                     {
-                        var errorEventArgs = new ProcessErrorEventArgs(null, ex.Message, ex.InnerException ?? ex, cancellationToken);
+                        var partitionId = ex.Reason == EventHubsException.FailureReason.ClaimPartitionFailed ?
+                            ex.GetFailureReasonData<string>() :
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs]: That's a nice touch.  I like it.

File: sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+    {
+        /// <summary>
+        ///   Gets the data value related to the exception <see cref="EventHubsException.FailureReason" />.
+        /// </summary>
+        ///
+        /// <param name="instance">The instance that this method was invoked on.</param>
+        ///
+        /// <returns>The Data value or null.</returns>
+        ///
+        public static T GetFailureReasonData<T>(this EventHubsException instance) where T: class =>
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs]: Clever.   I think this is great, but it does require that we tie things to a concrete failure reason.   To avoid adding members to that public enum, it may be worth an overload for string-based keys as well.

File: sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Processor/PartitionLoadBalancer.cs [hunk 6]
```diff
@@ -480,9 +480,11 @@ private async Task RenewOwnershipAsync(CancellationToken cancellationToken)
 
                 // Set the EventHubName to null so it doesn't modify the exception message. This exception message is
                 // used so the processor can retrieve the raw Operation string, and adding the EventHubName would append
-                // unwanted info to it.
+                // unwanted info to it. This exception also communicates the PartitionId to the caller.
 
-                throw new EventHubsException(true, null, Resources.OperationClaimOwnership, ex);
+                var exception = new EventHubsException(true, null, Resources.OperationClaimOwnership, EventHubsException.FailureReason.ClaimPartitionFailed, ex);
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Processor/PartitionLoadBalancer.cs]: Maybe we could do a `SetFailureOperation` and use that as the flag having the user-facing `Reason` stay `General`,  since the operation is being set from a resource, it should be a relatively safe check.

File: sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs [hunk 7]
```diff
@@ -0,0 +1,35 @@
+// Copyright (c) Microsoft Corporation. All rights reserved.
+// Licensed under the MIT License.
+
+namespace Azure.Messaging.EventHubs.Core
+{
+    /// <summary>
+    ///   The set of extension methods for the <see cref="EventHubsException" /> class.
+    /// </summary>
+    ///
+    internal static class EventHubsExceptionExtensions
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs]: Echoing a thought that I had elsewhere, maybe instead of extending the failure reason, we could consider another extension method for the associated operation and then could filter based on operation and extract the associated data?

File: sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs (hunk 5 above)
Comment (christothes) [reply sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs]: Thanks for the feedback. The main goal behind associating it with a failure reason was to establish some notion of conflict avoidance and determinism for key values. I considered const string key values as well but I didn't have any great ideas for where those strings would be defined or how they'd be deterministically associated with a given scenario. 

Thoughts?

File: sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Processor/PartitionLoadBalancer.cs (hunk 6 above)
Comment (christothes) [reply sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Processor/PartitionLoadBalancer.cs]: Ah, are you suggesting we use the resource as the `Data` key value? That would solve the problem posed in my other comment.

File: sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs (hunk 7 above)
Comment (christothes) [reply sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs]: I like it, great suggestion!

File: sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs (hunk 5 above)
Comment (jsquire) [reply sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs]: I think that the concept is perfect.... this is the data associated with the failure.   Having a set of consts for the key is probably the way that I'd go, especially if we're considering adding additional metadata about the operation and such.    

That said, I think you're right in that we don't need these methods for any freeform things;  the raw member on `Exception` is fine.   Having additional members here for well-known items is likely a better path than my original thought.

File: sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Processor/PartitionLoadBalancer.cs (hunk 6 above)
Comment (jsquire) [reply sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Processor/PartitionLoadBalancer.cs]: I was thinking the resource becomes the value for another well-known key.    Since these are all locally scoped to the exception, having something like:

```
Data :
    Operation :  --RESOURCE THINGER--
    FailureContext:  -- PARTITION--
```

Naming is arbitrary, of course, just to illustrate.   We may be overthinking in terms of avoiding just adding a key for "partition" since it is such a core concept and not something that is esoteric and only makes sense in this particular context.

File: sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs (hunk 7 above)
Comment (christothes) [reply sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs]: Just to clarify and summarize the various thoughts and suggestions above, here are the options I thing we've raised:

1. Operation specific extension methods
   - No additional `FailureReason`
   - getter/setter extension methods abstract away any notion of key selection and simply get and set an operation specific payload.
   - ex. ` public static string GetPartitionLoadBalancingFailureData(this EventHubsException instance)` and ` public static void SetPartitionLoadBalancingFailureData(this EventHubsException instance, string partitionId)`
2. Data keyed on operation resource
   - No additional `FailureReason`
   - Key the Data based on a known resource such as `Resources.OperationClaimOwnership`
   - ex. ` public static T GetOperationFailureData(this EventHubsException instance, string resource)` and `public static void SetOperationFailureData<T>(this EventHubsException instance, string resource, T data)`
3. Failure code bounded Data values (existing solution)
   - Additional `FailureReason`
   - Key the data based on `FailureReason`

Did I miss or misinterpret any?

Comment (jsquire) [reply sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs]: As usual, thanks for being flexible and talking things through.   Your summary sounds great to me.    I may suggest a very slight twist:

- `public static T GetFailureData<T>(this EventHubsException instance)`
- `public static string GetFailureOperation(this EventHubsException instance)`

_(and, obviously, the associated setter)_

Which would just flip things a bit where a failure could set any kind of data but we assume there is a string that describes an operation.... which is something that is consistent within the core and processor libraries.   Either way, I'm good with the approach.

Comment (christothes) [reply sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs]: I think I'm missing something obvious here, but in your example methods above how does the get operation know which operation is relevant? Is this meant to be just a single example of some more specifically named methods per operation as in # 1 above?

Comment (christothes) [reply sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs]: > The general thing that I was looking to do was make "failure data" some object of unknown type that is set for the failure and "operation" a string value that corresponds to the text labels that we set for logging and such to offer context for the failure.

I believe we may be saying the same thing, but I just want to confirm 😄.  I think my confusion is that your description sounds consistent with # 2 above where the "operation" string is accepted in both the setter and the getter. The caller is then responsible to define or use a consistent operation identifier to key the Data. What threw me off is that your method example didn't accept an "operation".

Comment (jsquire) [reply sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs]: I don't think we're saying the same.  :smile:

I wasn't thinking to key off the operation, I was thinking the option would be the value.    So the `Data` dictionary would look something like:

```
Exception.Data
{
    { "FailureData",  PartitionId },
    { "FailureOeration", Resouces.LoadBalancerClaimFailure }
}
```

Comment (christothes) [reply sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs]: Ah, sorry for the confusion - I get what you are saying now.  So essentially the data dictionary becomes a self describing payload defining the relevant operation and the corresponding FailureData. Assuming I'm not still confused, I'll incorporate this concept into the next commit 😄.

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs [hunk 8]
```diff
@@ -1781,7 +1780,9 @@ public async Task PartitionClosingAsyncIsCalledWithOwnershipLostReasonWhenStoppi
                 })
                 .Returns<string, EventPosition, ReadEventOptions, CancellationToken>((partition, position, options, token) =>
                 {
-                    if (partition == faultedPartitionId)
+                    // Throw for the faultedPartition, but only after each partition processor has has a chance to start.
+
+                    if (partition == faultedPartitionId && partitionsBeingProcessed == partitionIds.Length)
```
Comment (jsquire) [inline sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs]: call me paranoid, but would this be safer as `>=` just in case there's a bug?  That way the test doesn't potentially hang?

File: sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs (hunk 7 above)
Comment (jsquire) [reply sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/EventHubsExceptionExtensions.cs]: Not at all, the problem was all me not being able to explain what was in my head.

**Review by jsquire — APPROVED** [review]
LGTM.   Thank you for bearing with the churn.   When you're ready to merge, please let us know and we'll push the button.

File: sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs (hunk 8 above)
Comment (christothes) [reply sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs]: fixed and ready to merge.

Comment (jsquire) [reply sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientTests.cs]: You got it!
